### ISSUE TITLE
Adding profile with mq-fabric-camel feature to a container fails on 1.1.0.CR3

### ISSUE THREAD

**Issue by umeetiusbaar** [fabric8io/fabric8#2025]
This error did not occur with 1.1.0.CR1 and before.

```
Fabric8:admin@root> mq-create --create-container senint-mq- --client-profile senint-mq-client --group senint senint-mq
MQ profile mq-broker-senint.senint-mq ready
Fabric8:admin@root> wait-for-provisioning -v
Waiting: Container senint-mq-1 is downloading
Waiting: Container senint-mq-1 is installing
Waiting: Container senint-mq-1 is finalizing
Waiting: Container senint-mq-1 is finalizing
Waiting: Container senint-mq-1 is finalizing
Waiting: Container senint-mq-1 is waiting
Waiting: Container senint-mq-2 is waiting
Waiting: Container senint-mq-2 is waiting
Waiting: Container senint-mq-2 is waiting
Waiting: Container senint-mq-2 is waiting
Waiting: Container senint-mq-2 is waiting
Waiting: Container senint-mq-2 is waiting
SUCCESS
Fabric8:admin@root> container-list 
[id]                           [version] [type]     [connected] [profiles]                                                   [provision status]
root*                          1.0       karaf      true        fabric                                                       success
                                                                fabric-ensemble-0000-1                                       
  senint-mq-1                  1.0       karaf      true        mq-broker-senint.senint-mq                                   success
  senint-mq-2                  1.0       karaf      true        mq-broker-senint.senint-mq                                   success
Fabric8:admin@root> container-create-child --profile feature-camel --profile feature-cxf --profile senint-mq-client --jvm-opts '-Xms2048m -Xmx2048m -XX:MaxPermSize=512m' root senint-apps
The following containers have been created successfully:
    Container: senint-apps.
Fabric8:admin@root> wait-for-provisioning -v
Waiting: Container senint-apps is 
Waiting: Container senint-apps is 
Waiting: Container senint-apps is 
Waiting: Container senint-apps is downloading
Waiting: Container senint-apps is downloading
Waiting: Container senint-apps is installing
Waiting: Container senint-apps is finalizing
Waiting: Container senint-apps is finalizing
Waiting: Container senint-apps is waiting
Waiting: Container senint-apps is resolving
Waiting: Container senint-apps is finalizing
SUCCESS
Fabric8:admin@root> profile-create --parents feature-camel --parents feature-cxf --parents senint-mq-client senint-2014
Fabric8:admin@root> profile-edit --features mq-fabric-camel senint-2014
Adding feature:mq-fabric-camel to profile:senint-2014 version:1.0
Fabric8:admin@root> container-add-profile senint-apps senint-2014
Fabric8:admin@root> wait-for-provisioning -v
Waiting: Container senint-apps is error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requirement [dummy/0.0.0] osgi.identity; osgi.identity=mq-fabric-camel; type=karaf.feature; version=0
Error executing command: Error provisioning container senint-apps : error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requirement [dummy/0.0.0] osgi.identity; osgi.identity=mq-fabric-camel; type=karaf.feature; version=0
Fabric8:admin@root> version-list 
[version]       [default] [# containers] [description]
1.0             true      4              
Fabric8:admin@root> container-list 
[id]                           [version] [type]     [connected] [profiles]                                                   [provision status]
root*                          1.0       karaf      true        fabric                                                       success
                                                                fabric-ensemble-0000-1                                       
  senint-apps                  1.0       karaf      true        senint-mq-client                                             error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requir
                                                                feature-camel                                                
                                                                feature-cxf                                                  
                                                                senint-2014                                                  
  senint-mq-1                  1.0       karaf      true        mq-broker-senint.senint-mq                                   success
  senint-mq-2                  1.0       karaf      true        mq-broker-senint.senint-mq                                   success
```

In instances/senint-apps/data/log/karaf.log:

```
...
2014-07-16 07:33:33,887 | INFO  | pool-30-thread-1 | JettyServerImpl                  | 188 - org.ops4j.pax.web.pax-web-jetty - 3.0.6 | Pax Web available at [0.0.0.0]:[8184]
2014-07-16 07:33:33,888 | INFO  | pool-30-thread-1 | HttpServiceFactoryImpl           | 190 - org.ops4j.pax.web.pax-web-runtime - 3.0.6 | Binding bundle: [io.fabric8.fabric-jolokia [101]] to http service
2014-07-16 07:33:33,896 | INFO  | pool-30-thread-1 | fabric-jolokia                   | 101 - io.fabric8.fabric-jolokia - 1.1.0.CR3 | No access restrictor found at classpath:/jolokia-access.xml, access to all MBeans is allowed
2014-07-16 07:33:33,921 | INFO  | pool-30-thread-1 | AbstractComponent                | 64 - io.fabric8.fabric-api - 1.1.0.CR3 | activateComponent: io.fabric8.jolokia.FabricJolokia@5b96ec68
2014-07-16 07:33:33,922 | INFO  | pool-30-thread-1 | HttpServiceFactoryImpl           | 190 - org.ops4j.pax.web.pax-web-runtime - 3.0.6 | Binding bundle: [io.fabric8.fabric-git-server [99]] to http service
2014-07-16 07:33:33,941 | INFO  | pool-30-thread-1 | AbstractComponent                | 64 - io.fabric8.fabric-api - 1.1.0.CR3 | activateComponent: io.fabric8.git.http.GitHttpServerRegistrationHandler@78164c5a
2014-07-16 07:33:33,943 | INFO  | pool-30-thread-1 | HttpServiceFactoryImpl           | 190 - org.ops4j.pax.web.pax-web-runtime - 3.0.6 | Binding bundle: [org.apache.cxf.cxf-rt-transports-http [134]] to http service
2014-07-16 07:33:46,754 | INFO  | admin-2-thread-1 | FabricConfigAdminBridge          | 71 - io.fabric8.fabric-configadmin - 1.1.0.CR3 | Updating configuration io.fabric8.agent
2014-07-16 07:33:46,756 | INFO  | o.fabric8.agent) | DeploymentAgent                  | 65 - io.fabric8.fabric-agent - 1.1.0.CR3 | DeploymentAgent updated with {repository.karaf-enterprise=mvn:org.apache.karaf.assemblies.features/enterpr
ise/2.3.0.redhat-610379/xml/features, feature.fabric-cxf-registry=fabric-cxf-registry, attribute.parents=feature-camel feature-cxf senint-mq-client, feature.insight-log=insight-log, org.ops4j.pax.url.mvn.defaultrepositories=file:/opt/fab
ric8-karaf-1.1.0.CR3/system@snapshots@id=karaf-default,file:/opt/fabric8-karaf-1.1.0.CR3/local-repo@snapshots@id=karaf-local, feature.fabric-jaas=fabric-jaas, attribute.abstract=true, fabric.zookeeper.pid=io.fabric8.agent, feature.camel-
blueprint=camel-blueprint, feature.fabric-core=fabric-core, optional.ops4j-base-lang=mvn:org.ops4j.base/ops4j-base-lang/1.4.0, service.pid=io.fabric8.agent, feature.spring=spring, org.ops4j.pax.url.mvn.repositories=http://repo1.maven.org
/maven2@id=central, https://repo.fusesource.com/nexus/content/groups/public@id=fusepublic, https://repository.jboss.org/nexus/content/repositories/public@id=jbosspublic, https://repo.fusesource.com/nexus/content/repositories/releases@id=
jbossreleases, https://repo.fusesource.com/nexus/content/groups/ea@id=jbossearlyaccess, http://repository.springsource.com/maven/bundles/release@id=ebrreleases, http://repository.springsource.com/maven/bundles/external@id=ebrexternal, fe
ature.fabric-web=fabric-web, repository.activemq=mvn:org.apache.activemq/activemq-karaf/5.10.0/xml/features, feature.fabric-git-server=fabric-git-server, repository.apache-camel=mvn:org.apache.camel.karaf/apache-camel/2.13.2/xml/features
, resolve.optional.imports=false, feature.fabric-cxf=fabric-cxf, repository.fabric8=mvn:io.fabric8/fabric8-karaf/1.1.0.CR3/xml/features, feature.cxf=cxf, feature.war=war, feature.mq-fabric-camel=mq-fabric-camel, feature.mq-fabric=mq-fabr
ic, feature.karaf=karaf, feature.fabric-agent=fabric-agent, feature.jolokia=jolokia, feature.fabric-git=fabric-git, feature.camel-core=camel-core, hash=ProfileImpl[id='senint-mq-client', version='1.0']-ProfileImpl[id='feature-camel', ver
sion='1.0']-ProfileImpl[id='feature-cxf', version='1.0']-ProfileImpl[id='senint-2014', version='1.0']-a823e35-c6192fc-6978364-c6192fc-c6192fc-6978364-c6192fc-c6192fc-6978364-6d8532a-c6192fc-c6192fc-6978364-c6192fc-c6192fc-6978364-a823e35
-c6192fc-6978364, feature.fabric-camel=fabric-camel, repository.karaf-spring=mvn:org.apache.karaf.assemblies.features/spring/2.3.0.redhat-610379/xml/features, repository.apache-cxf=mvn:org.apache.cxf.karaf/apache-cxf/2.7.11/xml/features,
 patch.repositories=https://repo.fusesource.com/nexus/content/repositories/releases, https://repo.fusesource.com/nexus/content/groups/ea, repository.karaf-standard=mvn:org.apache.karaf.assemblies.features/standard/2.3.0.redhat-610379/xml
/features}
2014-07-16 07:33:47,033 | ERROR | agent-1-thread-1 | DeploymentAgent                  | 65 - io.fabric8.fabric-agent - 1.1.0.CR3 | Unable to update agent
org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requirement [dummy/0.0.0] osgi.identity; osgi.identity=mq-fabric-camel; type=karaf.feature; version=0
    at org.apache.felix.resolver.Candidates.populateResource(Candidates.java:285)[65:io.fabric8.fabric-agent:1.1.0.CR3]
    at org.apache.felix.resolver.Candidates.populate(Candidates.java:153)[65:io.fabric8.fabric-agent:1.1.0.CR3]
    at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:148)[65:io.fabric8.fabric-agent:1.1.0.CR3]
    at io.fabric8.agent.DeploymentBuilder.resolve(DeploymentBuilder.java:224)[65:io.fabric8.fabric-agent:1.1.0.CR3]
    at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:572)[65:io.fabric8.fabric-agent:1.1.0.CR3]
    at io.fabric8.agent.DeploymentAgent$2.run(DeploymentAgent.java:298)[65:io.fabric8.fabric-agent:1.1.0.CR3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_51]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744)[:1.7.0_51]

```

**Comment by pinko75** [comment]
Hi there,
     I have installed JBoss Fuse 6.1 onto an Amazon AIM Linux server. When I start the server and /or try to create a container under the root fabric, I get the following exception : 
org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requirement [dummy/0.0.0] osgi.identity; osgi.identity=fabric-webui; type=karaf.feature; version=0

  at org.apache.felix.resolver.Candidates.populateResource(Candidates.java:285)

  at org.apache.felix.resolver.Candidates.populate(Candidates.java:153)

  at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:148)

  at io.fabric8.agent.DeploymentBuilder.resolve(DeploymentBuilder.java:226)

  at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:521)

  at io.fabric8.agent.DeploymentAgent$2.run(DeploymentAgent.java:252)

  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
Any ideas?? 
Thanks in advance for your help.
LC
