### ISSUE TITLE
After remote container created by autoscaler fabric CLI commands are lost

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#2233]
Using CR5 I created a simple container on a vagrant host using the autoscaler.  After 20 seconds of being created I loose the fabric scope CLI commands.  Stacktrace below.  For info I'm not using the quickstarts mentioned in the log...

``````
2014-08-10 12:01:21,102 | INFO  | serviceprofile11 | FabricServiceImpl                | ?                                   ? | 69 - io.fabric8.fabric-core - 1.1.0.CR5 | The container myloggingserviceprofile11 has been successfully created
2014-08-10 12:01:36,848 | WARN  | pool-37-thread-1 | AbstractDataStore                | ?                                   ? | 69 - io.fabric8.fabric-core - 1.1.0.CR5 | Caught: com.google.common.util.concurrent.UncheckedExecutionException: io.fabric8.api.FabricException: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
fabric/profiles/quickstarts/java/cxf.cdi.profile/ReadMe.md
fabric/profiles/quickstarts/karaf/cxf/rest.profile/README.md
com.google.common.util.concurrent.UncheckedExecutionException: io.fabric8.api.FabricException: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
fabric/profiles/quickstarts/java/cxf.cdi.profile/ReadMe.md
fabric/profiles/quickstarts/karaf/cxf/rest.profile/README.md
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)[85:com.google.guava:15.0.0]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3932)[85:com.google.guava:15.0.0]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)[85:com.google.guava:15.0.0]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)[85:com.google.guava:15.0.0]
    at io.fabric8.git.internal.CachingGitDataStore.getVersionData(CachingGitDataStore.java:113)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.CachingGitDataStore.hasProfile(CachingGitDataStore.java:184)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.internal.VersionImpl.getProfile(VersionImpl.java:99)[69:io.fabric8.fabric-core:1.1.0.CR5]
    at io.fabric8.internal.ContainerImpl.getProfiles(ContainerImpl.java:206)[69:io.fabric8.fabric-core:1.1.0.CR5]
    at io.fabric8.api.Containers.containerHasProfile(Containers.java:140)[64:io.fabric8.fabric-api:1.1.0.CR5]
    at io.fabric8.api.Containers.containersForProfile(Containers.java:59)[64:io.fabric8.fabric-api:1.1.0.CR5]
    at io.fabric8.autoscale.AutoScaleController.containersForProfile(AutoScaleController.java:301)[173:io.fabric8.fabric-autoscale:1.1.0.CR5]
    at io.fabric8.autoscale.AutoScaleController.aliveOrPendingContainersForProfile(AutoScaleController.java:289)[173:io.fabric8.fabric-autoscale:1.1.0.CR5]
    at io.fabric8.autoscale.AutoScaleController.autoScaleProfile(AutoScaleController.java:230)[173:io.fabric8.fabric-autoscale:1.1.0.CR5]
    at io.fabric8.autoscale.AutoScaleController.autoScale(AutoScaleController.java:196)[173:io.fabric8.fabric-autoscale:1.1.0.CR5]
    at io.fabric8.autoscale.AutoScaleController.onConfigurationChanged(AutoScaleController.java:185)[173:io.fabric8.fabric-autoscale:1.1.0.CR5]
    at io.fabric8.autoscale.AutoScaleController.access$000(AutoScaleController.java:65)[173:io.fabric8.fabric-autoscale:1.1.0.CR5]
    at io.fabric8.autoscale.AutoScaleController$1.run(AutoScaleController.java:86)[173:io.fabric8.fabric-autoscale:1.1.0.CR5]
    at io.fabric8.service.AbstractDataStore.doRunCallbacks(AbstractDataStore.java:226)[69:io.fabric8.fabric-core:1.1.0.CR5]
    at io.fabric8.service.AbstractDataStore$1.run(AbstractDataStore.java:214)[69:io.fabric8.fabric-core:1.1.0.CR5]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_45]
    at java.lang.Thread.run(Thread.java:744)[:1.7.0_45]
Caused by: io.fabric8.api.FabricException: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
fabric/profiles/quickstarts/java/cxf.cdi.profile/ReadMe.md
fabric/profiles/quickstarts/karaf/cxf/rest.profile/README.md
    at io.fabric8.api.FabricException.launderThrowable(FabricException.java:43)[64:io.fabric8.fabric-api:1.1.0.CR5]
    at io.fabric8.git.internal.GitDataStore.gitOperation(GitDataStore.java:1165)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.GitDataStore.gitOperation(GitDataStore.java:1106)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.GitDataStore.gitOperation(GitDataStore.java:1101)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.CachingGitDataStore$1.load(CachingGitDataStore.java:86)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.CachingGitDataStore$1.load(CachingGitDataStore.java:83)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)[85:com.google.guava:15.0.0]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)[85:com.google.guava:15.0.0]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)[85:com.google.guava:15.0.0]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)[85:com.google.guava:15.0.0]
    ... 23 more
Caused by: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
fabric/profiles/quickstarts/java/cxf.cdi.profile/ReadMe.md
fabric/profiles/quickstarts/karaf/cxf/rest.profile/README.md
    at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:262)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.GitHelpers.checkoutBranch(GitHelpers.java:103)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.GitDataStore.checkoutVersion(GitDataStore.java:1536)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.CachingGitDataStore.populateVersionData(CachingGitDataStore.java:122)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.CachingGitDataStore$1$1.call(CachingGitDataStore.java:90)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.CachingGitDataStore$1$1.call(CachingGitDataStore.java:86)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at io.fabric8.git.internal.GitDataStore.gitOperation(GitDataStore.java:1139)[88:io.fabric8.fabric-git:1.1.0.CR5]
    ... 31 more
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
fabric/profiles/quickstarts/java/cxf.cdi.profile/ReadMe.md
fabric/profiles/quickstarts/karaf/cxf/rest.profile/README.md
    at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:412)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:393)[88:io.fabric8.fabric-git:1.1.0.CR5]
    at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:258)[88:io.fabric8.fabric-git:1.1.0.CR5]
    ... 37 more```
``````

**Comment by geertschuring** [comment]
I'm running into a similar issue now on Fuse 6.2.1 while trying to start a child container that started just fine yesterday. This is the message I got:

```
Caused by: io.fabric8.api.FabricException: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files:
bin/admin
bin/admin.bat
bin/client
bin/client.bat
bin/deletefabric8
bin/fuse
bin/fuse.bat
bin/karaf
...
```

It then continues to list all files in the fuse installation directory.

**Comment by magnosoft** [comment]
I'm having the same issue. After changing the maven repo link in the default profile, I restarted all containers including root but one did not start and got the CheckoutConflictException error. Any advice on how I can resolve it?
