### ISSUE TITLE
installing the fabric8/camel addon to Forge should also install the fabric8 quickstart archetypes

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#2845]
right now if you start 'archetype-list' there are no archetypes installed. it'd be nice to install the fabric8 ones as part of the fabric8 addon

**Comment by davsclaus** [comment]
Not sure how that command is supposed to work. I logged a ticket
https://issues.jboss.org/browse/FORGE-2185

**Comment by davsclaus** [comment]
A related ticket
https://issues.jboss.org/browse/FORGE-2239

**Comment by davsclaus** [comment]
If you use their built in project-new and from archetype, then there is no TAB completion at all. So its kinda hard to spell those types correct
```
[mydemo]$ project-new
***INFO*** Required inputs not satisfied, entering interactive mode
? Project name:  mydemo
? Top level package [org.mydemo]:
? Version [1.0.0-SNAPSHOT]:
? Final name:
? Project location [/opt/forge-distribution-2.14.0.Final/mydemo]:

[0] (x) war
[1] ( ) jar
[2] ( ) parent
[3] ( ) addon
[4] ( ) ear
[5] ( ) resource-jar
[6] ( ) from-archetype
[7] ( ) from-archetype-catalog

Press <ENTER> to confirm, or <CTRL>+C to cancel.
? Project type: [0-7] 6

[0] (x) Maven

Press <ENTER> to confirm, or <CTRL>+C to cancel.
? Build system: [0]
? Archetype Group Id:  org.apache.camel.archetypes
? Archetype Artifact Id:  camel-archetype-java
? Archetype Version:  2.14.1
? Archetype repository URL:
Downloading: http://repo1.maven.org/maven2/org/apache/camel/archetypes/camel-archetype-java/2.14.1/camel-archetype-java-2.14.1.jar
Downloaded: http://repo1.maven.org/maven2/org/apache/camel/archetypes/camel-archetype-java/2.14.1/camel-archetype-java-2.14.1.jar (16 KB at 28.9 KB/sec)
Creating archetype using Maven groupId: org.mydemo, artifactId: mydemo, version: 1.0.0-SNAPSHOT in directory: /opt/forge-distribution-2.14.0.Final/mydemo/mydemo
Using replace properties: {camel-version=2.14.1, maven-resources-plugin-version=2.6, slf4j-version=1.7.7, log4j-version=1.2.17, exec-maven-plugin-version=1.2.1, maven-compiler-plugin-version=2.5.1}
***SUCCESS*** Project named 'mydemo' has been created.
[mydemo]$ ls
```

But when you did it could actually create the project.

**Comment by davsclaus** [comment]
Wonder if you tell forge to use these X archetypes, and have tab completion for those. Then we can install our fabric8 archetypes.

An alternative is maybe to create our own project-new-fabric8 or something command, where we can choose among those archetypes only?

**Comment by davsclaus** [comment]
Got word from irc that you need to add to archetypes first, and it should be possible from a custom plugin. So lets try to add the archetypes for fabric8 / and maybe vanilla camel too?

**Comment by davsclaus** [comment]
Darn get a NPE when trying to find the camel archetypes
```
java.lang.RuntimeException: Could not resolve dependencies from Query [org.apache.camel.archetypes::::[2.4.1] - null] due to underlying exception
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveDependencies(MavenDependencyResolver.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.dependencies.DependencyResolver_$$_javassist_36df1324-352b-440b-b435-85563569053f.resolveDependencies(DependencyResolver_$$_javassist_36df1324-352b-440b-b435-85563569053f.java)
	at io.fabric8.forge.camel.commands.project.CamelArchetypeCatalogFactory.getArchetypeCatalog(CamelArchetypeCatalogFactory.java:54)
	at io.fabric8.forge.camel.commands.project.CamelSetupCommand.initializeUI(CamelSetupCommand.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.camel.commands.project.CamelSetupCommand_$$_javassist_2f95deb5-b267-434b-98f9-ae50c85c7668.initializeUI(CamelSetupCommand_$$_javassist_2f95deb5-b267-434b-98f9-ae50c85c7668.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:57)
	at org.jboss.forge.addon.shell.aesh.ShellSingleCommand.getParser(ShellSingleCommand.java:45)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandRegistry.getForgeCommand(ForgeCommandRegistry.java:116)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandRegistry.getCommand(ForgeCommandRegistry.java:83)
	at org.jboss.aesh.console.AeshConsoleImpl.getCommand(AeshConsoleImpl.java:242)
	at org.jboss.aesh.console.AeshConsoleImpl.access$100(AeshConsoleImpl.java:51)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:304)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveDependencies(MavenDependencyResolver.java:93)
	... 29 more

```

**Comment by davsclaus** [comment]
And btw I dont think we generate any maven archetypes anymore for fabric8 v2 quickstarts

**Comment by davsclaus** [comment]
There is still a few bugs in forge that prevents this from working
https://issues.jboss.org/browse/FORGE-2243

**Comment by davsclaus** [comment]
We have the camel and fabric8 archetypes now
