### ISSUE TITLE
Getting org.apache.cxf.interceptor.Fault: Could not send Message.

### ISSUE THREAD

**Issue by bobquest33** [fabric8io/fabric8#3134]
===== attempting to create pod on host: http://localhost:8585/
Nov 17, 2014 10:29:51 PM org.apache.cxf.phase.PhaseInterceptorChain doDefaultLog
ging
WARNING: Interceptor for {http://localhost:8585/}WebClient has thrown exception,
 unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndi
ngInterceptor.handleMessage(MessageSenderInterceptor.java:64)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseIntercept
orChain.java:307)
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(Abst
ractClient.java:619)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(Clien
tProxyImpl.java:674)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.ja
va:224)
        at com.sun.proxy.$Proxy70.createLocalPod(Unknown Source)
        at io.fabric8.jube.apimaster.KubernetesExtensionsClient.createLocalPod(K
ubernetesExtensionsClient.java:53)
        at io.fabric8.jube.apimaster.ApiMasterKubernetesModel.tryCreatePod(ApiMa
sterKubernetesModel.java:285)
        at io.fabric8.jube.apimaster.ApiMasterKubernetesModel.remoteCreatePod(Ap
iMasterKubernetesModel.java:261)
        at io.fabric8.jube.replicator.Replicator.createMissingContainers(Replica
tor.java:279)
        at io.fabric8.jube.replicator.Replicator.autoScale(Replicator.java:198)
        at io.fabric8.jube.replicator.Replicator$3.run(Replicator.java:309)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.net.SocketException: SocketException invoking http://localhost:8
585/api/v1beta1/local/pods: Connection reset
        at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source
)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapExce
ption(HTTPConduit.java:1359)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(H
TTPConduit.java:1343)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:5
6)
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:638)

        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndi
ngInterceptor.handleMessage(MessageSenderInterceptor.java:62)
        ... 13 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1323)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468
)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionW
rappedOutputStream.getResponseCode(URLConnectionHTTPConduit.java:266)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleR
esponseInternal(HTTPConduit.java:1557)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleR
esponse(HTTPConduit.java:1527)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(H
TTPConduit.java:1330)
        ... 16 more

Nov 17, 2014 10:29:51 PM io.fabric8.jube.apimaster.ApiMasterKubernetesModel remo
teCreatePod
SEVERE: Failed to create pod: fabric8JavaCamelSpring-290 on host: HostNode{id='a
3cdda0d-b01a-4cd8-a85b-341c5b0048b7', hostName='localhost', webUrl='http://local
host:8585/'}. javax.ws.rs.ProcessingException: java.net.SocketException: SocketE
xception invoking http://localhost:8585/api/v1beta1/local/pods: Connection reset

javax.ws.rs.ProcessingException: java.net.SocketException: SocketException invok
ing http://localhost:8585/api/v1beta1/local/pods: Connection reset
        at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(Abstr
actClient.java:552)
        at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractC
lient.java:534)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(Clien
tProxyImpl.java:676)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.ja
va:224)
        at com.sun.proxy.$Proxy70.createLocalPod(Unknown Source)
        at io.fabric8.jube.apimaster.KubernetesExtensionsClient.createLocalPod(K
ubernetesExtensionsClient.java:53)
        at io.fabric8.jube.apimaster.ApiMasterKubernetesModel.tryCreatePod(ApiMa
sterKubernetesModel.java:285)
        at io.fabric8.jube.apimaster.ApiMasterKubernetesModel.remoteCreatePod(Ap
iMasterKubernetesModel.java:261)
        at io.fabric8.jube.replicator.Replicator.createMissingContainers(Replica
tor.java:279)
        at io.fabric8.jube.replicator.Replicator.autoScale(Replicator.java:198)
        at io.fabric8.jube.replicator.Replicator$3.run(Replicator.java:309)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.net.SocketException: SocketException invoking http://localhost:8
585/api/v1beta1/local/pods: Connection reset
        at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source
)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapExce
ption(HTTPConduit.java:1359)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(H
TTPConduit.java:1343)
        at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:5
6)
        at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:638)

        at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndi
ngInterceptor.handleMessage(MessageSenderInterceptor.java:62)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseIntercept
orChain.java:307)
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(Abst
ractClient.java:619)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(Clien
tProxyImpl.java:674)
        ... 10 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1323)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468
)
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionW
rappedOutputStream.getResponseCode(URLConnectionHTTPConduit.java:266)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleR
esponseInternal(HTTPConduit.java:1557)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleR
esponse(HTTPConduit.java:1527)
        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(H
TTPConduit.java:1330)
        ... 16 more

Added new container: fabric8JavaCamelSpring-291-fabric8-java-camel-spring

**Comment by davsclaus** [comment]
Closing as no response
