### ISSUE TITLE
fix test case thats started failing in the release CI process

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3238]
here's the output:
```
2:28:30     Running io.fabric8.etcd.reader.gson.GsonMockWebServerTest
02:28:30     Tests run: 12, Failures: 6, Errors: 6, Skipped: 0, Time elapsed: 0.216 sec <<< FAILURE! - in io.fabric8.etcd.reader.gson.GsonMockWebServerTest
02:28:30     testCompareAndDeleteRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.068 sec  <<< FAILURE!
02:28:30     java.lang.AssertionError: java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:30     	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
02:28:30     	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
02:28:30     	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
02:28:30     	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
02:28:30     	at com.google.mockwebserver.MockWebServer.getHostName(MockWebServer.java:88)
02:28:30     	at io.fabric8.etcd.reader.gson.GsonMockWebServerTest.createClient(GsonMockWebServerTest.java:30)
02:28:30     
02:28:30     testCompareAndDeleteRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.076 sec  <<< ERROR!
02:28:30     java.lang.NullPointerException: null
02:28:30     	at io.fabric8.etcd.core.AbstractMockWebServerTest.tearDown(AbstractMockWebServerTest.java:57)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02:28:30     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:28:30     	at java.lang.reflect.Method.invoke(Method.java:606)
02:28:30     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
02:28:30     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02:28:30     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
02:28:30     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
02:28:30     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
02:28:30     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
02:28:30     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
02:28:30     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
02:28:30     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
02:28:30     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
02:28:30     	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
02:28:30     
02:28:30     testGetAsync(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.006 sec  <<< FAILURE!
02:28:30     java.lang.AssertionError: java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:30     	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
02:28:30     	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
02:28:30     	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
02:28:30     	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
02:28:30     	at com.google.mockwebserver.MockWebServer.getHostName(MockWebServer.java:88)
02:28:30     	at io.fabric8.etcd.reader.gson.GsonMockWebServerTest.createClient(GsonMockWebServerTest.java:30)
02:28:30     
02:28:30     testGetAsync(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.009 sec  <<< ERROR!
02:28:30     java.lang.NullPointerException: null
02:28:30     	at io.fabric8.etcd.core.AbstractMockWebServerTest.tearDown(AbstractMockWebServerTest.java:57)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02:28:30     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:28:30     	at java.lang.reflect.Method.invoke(Method.java:606)
02:28:30     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
02:28:30     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02:28:30     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
02:28:30     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
02:28:30     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
02:28:30     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
02:28:30     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
02:28:30     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
02:28:30     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
02:28:30     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
02:28:30     	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
02:28:30     
02:28:30     testDeleteRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
02:28:30     java.lang.AssertionError: java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:30     	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
02:28:30     	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
02:28:30     	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
02:28:30     	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
02:28:30     	at com.google.mockwebserver.MockWebServer.getHostName(MockWebServer.java:88)
02:28:30     	at io.fabric8.etcd.reader.gson.GsonMockWebServerTest.createClient(GsonMockWebServerTest.java:30)
02:28:30     
02:28:30     testDeleteRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.008 sec  <<< ERROR!
02:28:30     java.lang.NullPointerException: null
02:28:30     	at io.fabric8.etcd.core.AbstractMockWebServerTest.tearDown(AbstractMockWebServerTest.java:57)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02:28:30     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:28:30     	at java.lang.reflect.Method.invoke(Method.java:606)
02:28:30     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
02:28:30     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02:28:30     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
02:28:30     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
02:28:30     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
02:28:30     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
02:28:30     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
02:28:30     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
02:28:30     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
02:28:30     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
02:28:30     	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
02:28:30     
02:28:30     testSetRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
02:28:30     java.lang.AssertionError: java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:30     	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
02:28:30     	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
02:28:30     	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
02:28:30     	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
02:28:30     	at com.google.mockwebserver.MockWebServer.getHostName(MockWebServer.java:88)
02:28:30     	at io.fabric8.etcd.reader.gson.GsonMockWebServerTest.createClient(GsonMockWebServerTest.java:30)
02:28:30     
02:28:30     testSetRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.007 sec  <<< ERROR!
02:28:30     java.lang.NullPointerException: null
02:28:30     	at io.fabric8.etcd.core.AbstractMockWebServerTest.tearDown(AbstractMockWebServerTest.java:57)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02:28:30     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:28:30     	at java.lang.reflect.Method.invoke(Method.java:606)
02:28:30     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
02:28:30     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02:28:30     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
02:28:30     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
02:28:30     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
02:28:30     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
02:28:30     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
02:28:30     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
02:28:30     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
02:28:30     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
02:28:30     	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
02:28:30     
02:28:30     testCompareAndSwapRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.005 sec  <<< FAILURE!
02:28:30     java.lang.AssertionError: java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:30     	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
02:28:30     	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
02:28:30     	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
02:28:30     	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
02:28:30     	at com.google.mockwebserver.MockWebServer.getHostName(MockWebServer.java:88)
02:28:30     	at io.fabric8.etcd.reader.gson.GsonMockWebServerTest.createClient(GsonMockWebServerTest.java:30)
02:28:30     
02:28:30     testCompareAndSwapRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.007 sec  <<< ERROR!
02:28:30     java.lang.NullPointerException: null
02:28:30     	at io.fabric8.etcd.core.AbstractMockWebServerTest.tearDown(AbstractMockWebServerTest.java:57)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02:28:30     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:28:30     	at java.lang.reflect.Method.invoke(Method.java:606)
02:28:30     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
02:28:30     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02:28:30     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
02:28:30     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
02:28:30     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
02:28:30     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
02:28:30     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
02:28:30     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
02:28:30     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
02:28:30     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
02:28:30     	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
02:28:30     
02:28:30     testGetRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.004 sec  <<< FAILURE!
02:28:30     java.lang.AssertionError: java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:30     	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
02:28:30     	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
02:28:30     	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
02:28:30     	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
02:28:30     	at com.google.mockwebserver.MockWebServer.getHostName(MockWebServer.java:88)
02:28:30     	at io.fabric8.etcd.reader.gson.GsonMockWebServerTest.createClient(GsonMockWebServerTest.java:30)
02:28:30     
02:28:30     testGetRequest(io.fabric8.etcd.reader.gson.GsonMockWebServerTest)  Time elapsed: 0.006 sec  <<< ERROR!
02:28:30     java.lang.NullPointerException: null
02:28:30     	at io.fabric8.etcd.core.AbstractMockWebServerTest.tearDown(AbstractMockWebServerTest.java:57)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:28:30     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02:28:30     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:28:30     	at java.lang.reflect.Method.invoke(Method.java:606)
02:28:30     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
02:28:30     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02:28:30     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
02:28:30     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
02:28:30     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
02:28:30     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
02:28:30     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
02:28:30     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
02:28:30     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
02:28:30     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
02:28:30     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
02:28:30     	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
02:28:30     	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
02:28:30     	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
02:28:30     
02:28:30     Running io.fabric8.etcd.reader.gson.GsonResponseReaderTest
02:28:31     Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.168 sec - in io.fabric8.etcd.reader.gson.GsonResponseReaderTest
02:28:31     
02:28:31     Results :
02:28:31     
02:28:31     Failed tests: 
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.setUp:51->createClient:30 java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.setUp:51->createClient:30 java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.setUp:51->createClient:30 java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.setUp:51->createClient:30 java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.setUp:51->createClient:30 java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.setUp:51->createClient:30 java.net.UnknownHostException: jenkins-rhel-6.5-slave.novalocal.localdomain: jenkins-rhel-6.5-slave.novalocal.localdomain: Name or service not known
02:28:31     
02:28:31     Tests in error: 
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.tearDown:57 » NullPointer
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.tearDown:57 » NullPointer
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.tearDown:57 » NullPointer
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.tearDown:57 » NullPointer
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.tearDown:57 » NullPointer
02:28:31       GsonMockWebServerTest>AbstractMockWebServerTest.tearDown:57 » NullPointer
02:28:31     
```

**Comment by davsclaus** [comment]
fabric8-etcd is moved into the sandbox, so I am closing this
