### ISSUE TITLE
Can't access secure Kubernetes API (HTTPS) with self-signed certificate

### ISSUE THREAD

**Issue by pires** [fabric8io/fabric8#3285]
I can't connect hawtio to GKE (Google Container Engine) kube api.

First, one needs to retrieve administrative credentials:
```
gcloud preview container clusters describe <MY_CLUSTER>
```

Get ```user``` and ```password``` and the IP address, of course and execute:
```
docker run -p 8585:8080 -it -e KUBERNETES_MASTER=https://<MY_USER>:<MY_PASSWORD>@<API_IP_ADDRESS> fabric8/hawtio
```

This fails because GKE uses an internal CA for signing the HTTPS certificate.

```
WARN  | Timer-19 | Failed to create snapshot: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://xxxxxx:xxxxxxxxxx@0.0.0.0/api/v1beta1/services: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://xxxxxx:xxxxxxxxxx@0.0.0.0/api/v1beta1/services: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:552)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:534)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:676)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy20.getServices(Unknown Source)
	at io.fabric8.kubernetes.api.KubernetesClient.getServices(KubernetesClient.java:185)
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceMap(KubernetesHelper.java:315)
	at io.fabric8.kubernetes.api.mbeans.AppView.createSnapshot(AppView.java:144)
	at io.fabric8.kubernetes.api.mbeans.AppView.refreshData(AppView.java:134)
	at io.fabric8.kubernetes.api.mbeans.AppView$1.run(AppView.java:76)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

Note: IP address and credentials have been obviously omitted.

**Comment by pires** [comment]
One k8s API Java client (featured [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/client-libraries.md)) [addresses this](https://github.com/nirmal070125/KubernetesAPIJavaClient). Now, just need to import certificate generated when installing k8s.

**Comment by jimmidyson** [comment]
This now works.
