### ISSUE TITLE
KubernetesClient.endpointsForService() NPE

### ISSUE THREAD

**Issue by pires** [fabric8io/fabric8#3319]
Given the following code
```java
private static final String HAZELCAST_SERVICE_NAME = "hazelcast";

public static void main(String... args) {
    final String kubeApiHost = getEnvOrDefault("KUBERNETES_RO_SERVICE_HOST",
        "localhost");
    final String kubeApiPort = getEnvOrDefault("KUBERNETES_RO_SERVICE_PORT",
        "8080");
    final String kubeUrl = "http://" + kubeApiHost + ":" + kubeApiPort;
    log.info("Asking k8s registry at {}..", kubeUrl);
    try {
      final KubernetesClient kube = new KubernetesClient(new KubernetesFactory(
          kubeUrl));
      final Endpoints endpoints = kube.endpointsForService(HAZELCAST_SERVICE_NAME, "");
      final List<String> hazelcastPods = new ArrayList<>(endpoints.
          getEndpoints().
          size());
      endpoints.getEndpoints().parallelStream().forEach(e -> {
        hazelcastPods.add(e.split(":")[0]);
      });
      log.info("Found {} pods running Hazelcast.", hazelcastPods.size());
    } catch (Exception ex) {
      log.error("There was an error while running Hazelcast discovery:", ex);
    }
  }
```

I get the following error
```
[main] ERROR com.github.pires.hazelcast.HazelcastDiscovery - There was an error while running Hazelcast discovery:
java.lang.NullPointerException
	at org.apache.cxf.jaxrs.client.AbstractClient.setupOutInterceptorChain(AbstractClient.java:843)
	at org.apache.cxf.jaxrs.client.AbstractClient.createMessage(AbstractClient.java:911)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:650)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy19.endpointsForService(Unknown Source)
	at io.fabric8.kubernetes.api.KubernetesClient.endpointsForService(KubernetesClient.java:218)
	at com.github.pires.hazelcast.HazelcastDiscovery.main(HazelcastDiscovery.java:65)
```

**Comment by pires** [comment]
Just in case you're wondering about the dependencies within my runnable JAR
```
[INFO] Including io.fabric8:kubernetes-api:jar:2.0.19 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.4.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.4.1 in the shaded jar.
[INFO] Including javax.validation:validation-api:jar:1.1.0.Final in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.4.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0 in the shaded jar.
[INFO] Including io.fabric8:fabric-utils:jar:2.0.19 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.4.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.4.1 in the shaded jar.
[INFO] Including org.apache.cxf:cxf-rt-rs-client:jar:3.0.2 in the shaded jar.
[INFO] Including org.apache.cxf:cxf-rt-transports-http:jar:3.0.2 in the shaded jar.
[INFO] Including org.apache.cxf:cxf-core:jar:3.0.2 in the shaded jar.
[INFO] Including org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1 in the shaded jar.
[INFO] Including org.codehaus.woodstox:stax2-api:jar:3.1.4 in the shaded jar.
[INFO] Including org.apache.ws.xmlschema:xmlschema-core:jar:2.1.0 in the shaded jar.
[INFO] Including org.apache.cxf:cxf-rt-frontend-jaxrs:jar:3.0.2 in the shaded jar.
[INFO] Including javax.ws.rs:javax.ws.rs-api:jar:2.0.1 in the shaded jar.
[INFO] Including javax.annotation:javax.annotation-api:jar:1.2 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.5 in the shaded jar.
[INFO] Including org.slf4j:slf4j-simple:jar:1.7.5 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.5 in the shaded jar.
[INFO] Including org.json:json:jar:20140107 in the shaded jar.
[INFO] Including com.hazelcast:hazelcast:jar:3.3.3 in the shaded jar.
[INFO] Including net.sourceforge.findbugs:annotations:jar:1.3.2 in the shaded jar.
[INFO] Including com.eclipsesource.minimal-json:minimal-json:jar:0.9.1 in the shaded jar.
```

**Comment by pires** [comment]
When I use ```maven-shade-plugin``` or ```maven-assembly-plugin``` the app doesn't work. I've tried setting a non-reachable URL for k8s master and while expecting a timeout, I always get that NPE.

When using ```spring-boot-maven-plugin``` it just works as expected. So I can just assume it's a dependency thing and one should take care on how an app is packaged.

Current runnable JAR dependencies are
```
lib/spring-boot-starter-1.2.0.RELEASE.jar
lib/spring-boot-1.2.0.RELEASE.jar
lib/spring-context-4.1.3.RELEASE.jar
lib/spring-aop-4.1.3.RELEASE.jar
lib/aopalliance-1.0.jar
lib/spring-beans-4.1.3.RELEASE.jar
lib/spring-expression-4.1.3.RELEASE.jar
lib/spring-boot-autoconfigure-1.2.0.RELEASE.jar
lib/spring-boot-starter-logging-1.2.0.RELEASE.jar
lib/jcl-over-slf4j-1.7.7.jar
lib/jul-to-slf4j-1.7.7.jar
lib/log4j-over-slf4j-1.7.7.jar
lib/logback-classic-1.1.2.jar
lib/logback-core-1.1.2.jar
lib/spring-core-4.1.3.RELEASE.jar
lib/snakeyaml-1.14.jar
lib/kubernetes-api-2.0.19.jar
lib/jackson-module-jaxb-annotations-2.4.1.jar
lib/jackson-core-2.4.4.jar
lib/validation-api-1.1.0.Final.jar
lib/jackson-databind-2.4.4.jar
lib/jackson-annotations-2.4.4.jar
lib/fabric-utils-2.0.19.jar
lib/commons-lang-2.6.jar
lib/jackson-jaxrs-json-provider-2.4.1.jar
lib/jackson-jaxrs-base-2.4.1.jar
lib/cxf-rt-rs-client-3.0.2.jar
lib/cxf-rt-transports-http-3.0.2.jar
lib/cxf-core-3.0.2.jar
lib/woodstox-core-asl-4.4.1.jar
lib/stax2-api-3.1.4.jar
lib/xmlschema-core-2.1.0.jar
lib/cxf-rt-frontend-jaxrs-3.0.2.jar
lib/javax.ws.rs-api-2.0.1.jar
lib/javax.annotation-api-1.2.jar
lib/slf4j-api-1.7.7.jar
lib/slf4j-simple-1.7.5.jar
lib/json-20140107.jar
lib/hazelcast-3.3.3.jar
lib/annotations-1.3.2.jar
lib/minimal-json-0.9.1.jar
```

**Comment by jimmidyson** [comment]
CXF has a lot of overlap between it's separate JARs in META-INF. As shown in http://stackoverflow.com/a/9069435 you have to use resource transformers (http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html) if you're going to use the maven shade plugin to create an uber jar containing everything. A good pointer is how the CXF bundle JAR does it - see http://svn.apache.org/repos/asf/cxf/trunk/osgi/bundle/all/pom.xml for details.
