### ISSUE TITLE
fabric8 1.2.0: Maven plugin / ProjectDeployer cannot add a new profile if it didn't exist in version 1.0 (or default version)

### ISSUE THREAD

**Issue by raulk** [fabric8io/fabric8#3409]
Profile `abc` does not exist in the fabric. When using the Maven plugin to deploy the profile specifying version 1.1 or any version other than 1.0, the plugin fails with:

```
[INFO] --- fabric8-maven-plugin:1.2.0.redhat-061:deploy (default-cli) @ fabric8-profile-common ---
[INFO] Uploading to the fabric8 maven repository is disabled
[INFO] Updating profile: rhb-smxpoc-common with parent profile(s): [feature-cxf, feature-camel] using OSGi resolver
[INFO] About to invoke mbean io.fabric8:type=ProjectDeployer on jolokia URL: http://localhost:8182/jolokia with user: admin
[ERROR] Failed to invoke mbean io.fabric8:type=ProjectDeployer on jolokia URL: http://localhost:8182/jolokia with user: admin. Error: java.lang.IllegalArgumentException
[ERROR] Stack: java.lang.IllegalArgumentException: Profile abc is not valid
	at io.fabric8.api.Profiles.assertValidProfileId(Profiles.java:450)
	at io.fabric8.service.FabricServiceImpl.validateProfileRequirements(FabricServiceImpl.java:1148)
	at io.fabric8.service.FabricServiceImpl.validateRequirements(FabricServiceImpl.java:1142)
	at io.fabric8.service.FabricServiceImpl.setRequirements(FabricServiceImpl.java:1123)
	at io.fabric8.deployer.ProjectDeployerImpl.resolveProfileDeployments(ProjectDeployerImpl.java:394)
...
```

**Comment by ingra83** [comment]
I had a similar problem on fuse 6.2.1. The issue was introduced after removed the profile from the container and deleted it. The issue is that the fabric required profile list wasn't update also if the profile was removed successfully. If you perform the command **fabric:require-profile-list** I see the profile deleted and yet required. I resolved removing the profile by the command **fabric:require-profile-delete**. You should pay attention when you write the profile name because the auto completion cannot display the profile name, so you write manually the profile name.

**Comment by rafaeltuelho** [comment]
@ingra83 many thank for sharing this workaround! 
I was facing this same issue on Fuse 6.3
Saved my day o/

**Comment by ingra83** [comment]
I'm very happy that I saved you. 👍
So unfortunatly the issue persist on fuse 6.3.
