### ISSUE TITLE
If an Integration Test fails the tear down doesn't stop all docker containers

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#3485]
Using the Jenkins integration test.

The strange thing here is using 'osc get pods' does not show the running pods but docker ps does...

docker ps | grep itest

```
[fabric8@jrawlings-fabric8 ~]$ docker ps | grep itest
a8c8f547cb01        openshift/origin-pod:v0.3.1                "/pod"                 2 minutes ago       Up 2 minutes                                                                                                         k8s_POD.591e9c9_jenkins-5hrlv.itest-874d66fa-e922-4646-b47d-57771045cf79.api_dc5906f9-b855-11e4-bded-fa163e856018_38844ea1
c582fab306c2        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   2 minutes ago       Up 2 minutes                                                                                                         k8s_jenkins-container.74c6fcb0_jenkins-5hrlv.itest-874d66fa-e922-4646-b47d-57771045cf79.api_dc5906f9-b855-11e4-bded-fa163e856018_72e1de67
[fabric8@jrawlings-fabric8 ~]$ docker ps | grep itest
a93b32fc7769        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   4 minutes ago       Up 4 minutes                                                                                                         k8s_jenkins-container.74c6fcb0_jenkins-befd0.itest-d6b9ee97-ac18-4f7a-8cef-b3312b719ed6.api_f3da1daa-b868-11e4-bded-fa163e856018_05afc688
408d905dc34c        openshift/origin-pod:v0.3.1                "/pod"                 4 minutes ago       Up 4 minutes                                                                                                         k8s_POD.591e9c9_jenkins-befd0.itest-d6b9ee97-ac18-4f7a-8cef-b3312b719ed6.api_f3da1daa-b868-11e4-bded-fa163e856018_23e8c905
a9b55da1d5c7        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   47 minutes ago      Up 47 minutes                                                                                                        k8s_jenkins-container.74c6fcb0_jenkins-69p53.itest-68f873c2-25e4-49e2-a5c8-1ecfebf08ae1.api_ec7c9997-b862-11e4-bded-fa163e856018_0446fe12
6abf2149e4b3        openshift/origin-pod:v0.3.1                "/pod"                 47 minutes ago      Up 47 minutes                                                                                                        k8s_POD.591e9c9_jenkins-69p53.itest-68f873c2-25e4-49e2-a5c8-1ecfebf08ae1.api_ec7c9997-b862-11e4-bded-fa163e856018_426d9ac5
662efa9046a8        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   About an hour ago   Up About an hour                                                                                                     k8s_jenkins-container.74c6fcb0_jenkins-99gp2.itest-07fef8a6-9408-4e3f-8336-2efb2df2df43.api_b29f15fc-b85f-11e4-bded-fa163e856018_5164bc66
b790d0a988b9        openshift/origin-pod:v0.3.1                "/pod"                 About an hour ago   Up About an hour                                                                                                     k8s_POD.591e9c9_jenkins-99gp2.itest-07fef8a6-9408-4e3f-8336-2efb2df2df43.api_b29f15fc-b85f-11e4-bded-fa163e856018_a624820e
10f0ba879503        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   About an hour ago   Up About an hour                                                                                                     k8s_jenkins-container.74c6fcb0_jenkins-kvlw8.itest-72e2c65a-cdb7-49a7-98d0-382b941df3bb.api_7ee50cba-b85c-11e4-bded-fa163e856018_b6813a1d
62a001dea42b        openshift/origin-pod:v0.3.1                "/pod"                 About an hour ago   Up About an hour                                                                                                     k8s_POD.591e9c9_jenkins-kvlw8.itest-72e2c65a-cdb7-49a7-98d0-382b941df3bb.api_7ee50cba-b85c-11e4-bded-fa163e856018_f2817c08
56de9596ed06        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   2 hours ago         Up 2 hours                                                                                                           k8s_jenkins-container.74c6fcb0_jenkins-f3zob.itest-0aca14d2-26ef-4fd5-80c5-3c68812e9ee5.api_7d31c7bd-b857-11e4-bded-fa163e856018_12b5fda6
e5592f3defad        openshift/origin-pod:v0.3.1                "/pod"                 2 hours ago         Up 2 hours                                                                                                           k8s_POD.591e9c9_jenkins-f3zob.itest-0aca14d2-26ef-4fd5-80c5-3c68812e9ee5.api_7d31c7bd-b857-11e4-bded-fa163e856018_37a0eff8
c582fab306c2        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   2 hours ago         Up 2 hours                                                                                                           k8s_jenkins-container.74c6fcb0_jenkins-5hrlv.itest-874d66fa-e922-4646-b47d-57771045cf79.api_dc5906f9-b855-11e4-bded-fa163e856018_72e1de67
a8c8f547cb01        openshift/origin-pod:v0.3.1                "/pod"                 2 hours ago         Up 2 hours                                                                                                           k8s_POD.591e9c9_jenkins-5hrlv.itest-874d66fa-e922-4646-b47d-57771045cf79.api_dc5906f9-b855-11e4-bded-fa163e856018_38844ea1
[fabric8@jrawlings-fabric8 ~]$ docker ps | grep itest | awk 1
a93b32fc7769        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   4 minutes ago       Up 4 minutes                                                                                                         k8s_jenkins-container.74c6fcb0_jenkins-befd0.itest-d6b9ee97-ac18-4f7a-8cef-b3312b719ed6.api_f3da1daa-b868-11e4-bded-fa163e856018_05afc688
408d905dc34c        openshift/origin-pod:v0.3.1                "/pod"                 4 minutes ago       Up 4 minutes                                                                                                         k8s_POD.591e9c9_jenkins-befd0.itest-d6b9ee97-ac18-4f7a-8cef-b3312b719ed6.api_f3da1daa-b868-11e4-bded-fa163e856018_23e8c905
a9b55da1d5c7        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   47 minutes ago      Up 47 minutes                                                                                                        k8s_jenkins-container.74c6fcb0_jenkins-69p53.itest-68f873c2-25e4-49e2-a5c8-1ecfebf08ae1.api_ec7c9997-b862-11e4-bded-fa163e856018_0446fe12
6abf2149e4b3        openshift/origin-pod:v0.3.1                "/pod"                 47 minutes ago      Up 47 minutes                                                                                                        k8s_POD.591e9c9_jenkins-69p53.itest-68f873c2-25e4-49e2-a5c8-1ecfebf08ae1.api_ec7c9997-b862-11e4-bded-fa163e856018_426d9ac5
662efa9046a8        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   About an hour ago   Up About an hour                                                                                                     k8s_jenkins-container.74c6fcb0_jenkins-99gp2.itest-07fef8a6-9408-4e3f-8336-2efb2df2df43.api_b29f15fc-b85f-11e4-bded-fa163e856018_5164bc66
b790d0a988b9        openshift/origin-pod:v0.3.1                "/pod"                 About an hour ago   Up About an hour                                                                                                     k8s_POD.591e9c9_jenkins-99gp2.itest-07fef8a6-9408-4e3f-8336-2efb2df2df43.api_b29f15fc-b85f-11e4-bded-fa163e856018_a624820e
10f0ba879503        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   About an hour ago   Up About an hour                                                                                                     k8s_jenkins-container.74c6fcb0_jenkins-kvlw8.itest-72e2c65a-cdb7-49a7-98d0-382b941df3bb.api_7ee50cba-b85c-11e4-bded-fa163e856018_b6813a1d
62a001dea42b        openshift/origin-pod:v0.3.1                "/pod"                 About an hour ago   Up About an hour                                                                                                     k8s_POD.591e9c9_jenkins-kvlw8.itest-72e2c65a-cdb7-49a7-98d0-382b941df3bb.api_7ee50cba-b85c-11e4-bded-fa163e856018_f2817c08
56de9596ed06        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   2 hours ago         Up 2 hours                                                                                                           k8s_jenkins-container.74c6fcb0_jenkins-f3zob.itest-0aca14d2-26ef-4fd5-80c5-3c68812e9ee5.api_7d31c7bd-b857-11e4-bded-fa163e856018_12b5fda6
e5592f3defad        openshift/origin-pod:v0.3.1                "/pod"                 2 hours ago         Up 2 hours                                                                                                           k8s_POD.591e9c9_jenkins-f3zob.itest-0aca14d2-26ef-4fd5-80c5-3c68812e9ee5.api_7d31c7bd-b857-11e4-bded-fa163e856018_37a0eff8
c582fab306c2        openshift/jenkins-1-centos:latest          "/usr/local/bin/jenk   2 hours ago         Up 2 hours                                                                                                           k8s_jenkins-container.74c6fcb0_jenkins-5hrlv.itest-874d66fa-e922-4646-b47d-57771045cf79.api_dc5906f9-b855-11e4-bded-fa163e856018_72e1de67
a8c8f547cb01        openshift/origin-pod:v0.3.1                "/pod"                 2 hours ago         Up 2 hours                                                                                                           k8s_POD.591e9c9_jenkins-5hrlv.itest-874d66fa-e922-4646-b47d-57771045cf79.api_dc5906f9-b855-11e4-bded-fa163e856018_38844ea1
```

osc get pods doesn't show the running itest containers from above.

```
[fabric8@jrawlings-fabric8 ~]$ osc get pods
POD                                IP                  CONTAINER(S)                IMAGE(S)                                   HOST                                             LABELS                     STATUS
elasticsearch-pod                  172.17.0.10         elasticsearch               dockerfile/elasticsearch                   jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   app=elasticsearch          Running
fabric8-console-controller-mhemx   172.17.0.5          fabric8-console-container   fabric8/hawtio-kubernetes:latest           jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   component=fabric8Console   Running
grafana-rc-hpmav                   172.17.0.8          grafana-image               jimmidyson/grafana:latest                  jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   app=grafana-viewer         Running
influxdb                           172.17.0.9          influxdb                    tutum/influxdb                             jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   name=influxdb              Running
kibana-pod                         172.17.0.6          kibana-image                jimmidyson/kibana4:latest                  jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   app=kibana-viewer          Running
logspout                           172.17.0.11         logspout                    jimmidyson/logspout-kube:latest            jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   app=logspout               Running
model-generator-o6pf7              172.17.0.13         model-generator-container   rawlingsj/origin-schema-generator:latest   jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   name=model-generator       Running
openshift-router                   172.17.0.12         origin-haproxy-router       openshift/origin-haproxy-router:latest     jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   <none>                     Running
registry-controller-0q71a          172.17.0.7          registry-container          registry                                   jrawlings-fabric8.osop.rhcloud.com/172.18.65.3   name=registry-pod          Running
```

If I kill the integration test docker containers `docker kill $(docker ps | grep itest | awk '{ print $1 }')` they are recreated.. 

straight away `docker ps | grep itest`
0 results found

wait 30 secs `docker ps | grep itest`
14 results found which matches the number of times the integration test failed

which suggests there's an RC but..

`osc get replicationController`

```
[fabric8@jrawlings-fabric8 ~]$ osc get replicationController
CONTROLLER                   CONTAINER(S)                IMAGE(S)                                   SELECTOR                   REPLICAS
fabric8-console-controller   fabric8-console-container   fabric8/hawtio-kubernetes:latest           component=fabric8Console   1
grafana-rc                   grafana-image               jimmidyson/grafana:latest                  app=grafana-viewer         1
model-generator              model-generator-container   rawlingsj/origin-schema-generator:latest   name=model-generator       1
registry-controller          registry-container          registry                                   name=registry-pod          1
```

**Comment by rawlingsj** [comment]
This is related to #3476, seems to be an issue with using the namespace to find the pods / RC's to clear down.

**Comment by jimmidyson** [comment]
Is this still happening with latest master? We made some fixes on Friday that should solve this.

**Comment by rawlingsj** [comment]
Yeah still happening.  Just retested on a clean rebuilt environment with both the Jenkins and Console tests..

```
➜  console git:(master) mvn test -Dtest=ConsoleKubernetesTest
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Console 2.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ console ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ console ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ console ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/jamesrawlings/fabric8/quickstarts/apps/console/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ console ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ console ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/jamesrawlings/fabric8/quickstarts/apps/console/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ console ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- fabric8-maven-plugin:2.0.29:json (json) @ console ---
[INFO] Configured with file: /Users/jamesrawlings/fabric8/quickstarts/apps/console/target/classes/kubernetes.json
[INFO] Generated port mappings: {http=io.fabric8.kubernetes.api.model.Port@7400e99e[containerPort=9090,hostIP=<null>,hostPort=<null>,name=<null>,protocol=<null>,additionalProperties={}], jolokia=io.fabric8.kubernetes.api.model.Port@7840e96c[containerPort=8778,hostIP=<null>,hostPort=<null>,name=<null>,protocol=<null>,additionalProperties={}]}
[INFO] No environment schemas found for file: io/fabric8/environment/schema.json
[INFO] Generated env mappings: {}
[INFO] Attaching kubernetes json file: /Users/jamesrawlings/fabric8/quickstarts/apps/console/target/classes/kubernetes.json to the build
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ console ---
[INFO] Surefire report directory: /Users/jamesrawlings/fabric8/quickstarts/apps/console/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.fabric8.apps.console.ConsoleKubernetesTest
Initializing Session:7d988bb0-b7a8-490e-968f-ebd6ee4ce85a
Creating kubernetes resources inside namespace: itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a
if you use a kubernetes CLI type this to switch namespaces: kube namespace itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a
Applying kubernetes configuration from: file:/Users/jamesrawlings/fabric8/quickstarts/apps/console/target/classes/kubernetes.json
Applying service:fabric8-console-service
[main] WARN org.apache.cxf.transport.https.HttpsURLConnectionFactory - Default key managers cannot be initialized: /Users/jamesrawlings/.keystore (No such file or directory)
[main] INFO io.fabric8.kubernetes.api.Controller - Creating a service from 7d988bb0-b7a8-490e-968f-ebd6ee4ce85a namespace itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a name fabric8-console-service
[main] WARN org.apache.cxf.transport.https.HttpsURLConnectionFactory - Default key managers cannot be initialized: /Users/jamesrawlings/.keystore (No such file or directory)
[main] INFO io.fabric8.kubernetes.api.Controller - Created service: {
  "kind": "Service",
  "id": "fabric8-console-service",
  "uid": "76ef697a-ba6a-11e4-adaa-000c29b1d3fc",
  "creationTimestamp": "2015-02-22T08:11:55Z",
  "selfLink": "/api/v1beta2/services/fabric8-console-service?namespace=itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a",
  "resourceVersion": 198,
  "apiVersion": "v1beta2",
  "namespace": "itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a",
  "port": 80,
  "protocol": "TCP",
  "selector": {
    "component": "console",
    "provider": "fabric8"
  },
  "containerPort": 9090,
  "portalIP": "172.30.17.96",
  "sessionAffinity": "None"
}
Applying replication controller:fabric8-console-controller
[main] INFO io.fabric8.kubernetes.api.Controller - Creating a replicationController from 7d988bb0-b7a8-490e-968f-ebd6ee4ce85a namespace itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a name fabric8-console-controller
[main] INFO io.fabric8.kubernetes.api.Controller - Created replicationController: {
  "kind": "ReplicationController",
  "id": "fabric8-console-controller",
  "uid": "774d7093-ba6a-11e4-adaa-000c29b1d3fc",
  "creationTimestamp": "2015-02-22T08:11:55Z",
  "selfLink": "/api/v1beta2/replicationControllers/fabric8-console-controller?namespace=itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a",
  "resourceVersion": 199,
  "apiVersion": "v1beta2",
  "namespace": "itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a",
  "desiredState": {
    "replicas": 1,
    "replicaSelector": {
      "component": "console",
      "provider": "fabric8"
    },
    "podTemplate": {
      "desiredState": {
        "manifest": {
          "version": "v1beta2",
          "id": "",
          "volumes": [],
          "containers": [
            {
              "name": "fabric8-console-container",
              "image": "fabric8/hawtio-kubernetes",
              "ports": [
                {
                  "containerPort": 9090,
                  "protocol": "TCP"
                },
                {
                  "containerPort": 8778,
                  "protocol": "TCP"
                }
              ],
              "resources": {},
              "terminationMessagePath": "/dev/termination-log",
              "imagePullPolicy": "PullAlways",
              "capabilities": {}
            }
          ],
          "restartPolicy": {
            "always": {}
          },
          "dnsPolicy": "ClusterFirst"
        }
      },
      "labels": {
        "component": "console",
        "provider": "fabric8"
      }
    }
  },
  "currentState": {
    "replicas": 0,
    "podTemplate": {
      "desiredState": {
        "manifest": {
          "version": "",
          "id": "",
          "volumes": null,
          "containers": null,
          "restartPolicy": {}
        }
      }
    }
  },
  "labels": {
    "component": "console",
    "provider": "fabric8"
  }
}
No pods are available yet, waiting...
Waiting for container:POD. Reason:Container cannot run
Waiting for container:fabric8-console-container. Reason:Image: fabric8/hawtio-kubernetes is ready, container is creating
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
No services are available yet, waiting...
Timed out waiting for pods/services!
Deleting pod:fabric8-console-controller-bhowt
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 305.391 sec <<< FAILURE! - in io.fabric8.apps.console.ConsoleKubernetesTest
io.fabric8.apps.console.ConsoleKubernetesTest  Time elapsed: 305.391 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to apply kubernetes configuration.
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:68)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:97)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.IllegalStateException: Failed to apply kubernetes configuration.
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:68)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:97)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error:
  ConsoleKubernetesTest.io.fabric8.apps.console.ConsoleKubernetesTest » Runtime ...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:07.936s
[INFO] Finished at: Sun Feb 22 08:16:57 GMT 2015
[INFO] Final Memory: 25M/439M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project console: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/jamesrawlings/fabric8/quickstarts/apps/console/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by rawlingsj** [comment]
Also the pods still haven't been cleaned up after the failed tests.

```
➜  console git:(master) docker ps | grep itest
19042007d73c        fabric8/hawtio-kubernetes:latest    "/bin/k8s-proxy --in   About a minute ago   Up About a minute                         k8s_fabric8-console-container.d3cf1f4c_fabric8-console-controller-5p5ic.itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a.api_2febfb83-ba6b-11e4-adaa-000c29b1d3fc_44c443f2
186a0e68540c        openshift/origin-pod:latest         "/pod"                 About a minute ago   Up About a minute                         k8s_POD.9a410c32_fabric8-console-controller-5p5ic.itest-7d988bb0-b7a8-490e-968f-ebd6ee4ce85a.api_2febfb83-ba6b-11e4-adaa-000c29b1d3fc_b216fa61
bdc9fa90f08b        openshift/jenkins-1-centos:latest   "/usr/local/bin/jenk   7 minutes ago        Up 7 minutes                              k8s_jenkins-container.74c6fcb0_jenkins-uvv78.itest-a19e262c-2537-4497-967c-9f46e0ec8179.api_6b2cf3a1-ba6a-11e4-adaa-000c29b1d3fc_89be40ef
23137e4eb68c        openshift/origin-pod:latest         "/pod"                 7 minutes ago        Up 7 minutes                              k8s_POD.7d4e9ca_jenkins-uvv78.itest-a19e262c-2537-4497-967c-9f46e0ec8179.api_6b2cf3a1-ba6a-11e4-adaa-000c29b1d3fc_ffc39dd2
6eade48f984f        openshift/jenkins-1-centos:latest   "/usr/local/bin/jenk   12 minutes ago       Up 12 minutes                             k8s_jenkins-container.74c6fcb0_jenkins-cydiz.itest-28f1fec5-6725-426c-b9cc-ff8a7ad360a5.api_be5e1b3f-ba69-11e4-adaa-000c29b1d3fc_5af9d392
e73c1c463221        openshift/origin-pod:latest         "/pod"                 12 minutes ago       Up 12 minutes                             k8s_POD.7d4e9ca_jenkins-cydiz.itest-28f1fec5-6725-426c-b9cc-ff8a7ad360a5.api_be5e1b3f-ba69-11e4-adaa-000c29b1d3fc_340341ad
```

**Comment by rawlingsj** [comment]
The CI job I've been using however has just passed so I must have missed something locally.

Also to confirm another itest failed but for a good reason, this issue was raised because test pods weren't being cleared up but I can confirm they are now.  

Closing.
