### ISSUE TITLE
[v2] fabric8mq arquillian tests using jersey instead of cxf-rs causing incompatible class issues on error

### ISSUE THREAD

**Issue by davidatkins** [fabric8io/fabric8#3499]
Hello,

I've been trying to run the arquillian tests in the fabric8mq project. On first run, they were failing with the following stack trace:

      java.lang.NoSuchMethodError: javax.ws.rs.WebApplicationException.<init>(Ljava/lang/String;Ljavax/ws/rs/core/Response;)V
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:27)
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:11)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy31.getReplicationController(Unknown Source)
	at io.fabric8.kubernetes.api.KubernetesClient.getReplicationController(KubernetesClient.java:154)
	...

It appears that something went wrong when talking to Kubernetes, but the Kubernetes Client had a class incompatibility issue when trying to marshal that error message into an exception.

This is because the level db dependency is pulling in jackson, and this leads to Kubernetes API using Jackson for JAX-RS instead of the expected CXF-RS:

      [INFO] +- io.fabric8:arquillian-fabric8:jar:2.0.25:test
      [INFO] |  +- io.fabric8:kubernetes-api:jar:2.0.25:test
      [INFO] |  |  +- org.apache.cxf:cxf-rt-rs-client:jar:3.0.2:test
      [INFO] |  |  |  \- org.apache.cxf:cxf-rt-frontend-jaxrs:jar:3.0.2:test
      [INFO] |  |  |     +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:test  
      
      [INFO] +- org.apache.activemq:activemq-leveldb-store:jar:5.10.0:compile
      [INFO] |  \- org.apache.hadoop:hadoop-core:jar:1.2.1:compile
      [INFO] |     +- com.sun.jersey:jersey-core:jar:1.8:compile

Jackson includes the javax.ws.rs.WebApplicationException class directly in its own jar, and this is different (older?) than the version expected by the Kubernetes API error handling code. Note that as of version 1.19 jersey no longer includes the JAX RS API packages in its jar.

My quick fix was to stop level db including the jackson libraries

    <dependency>
      <groupId>org.apache.activemq</groupId>
      <artifactId>activemq-leveldb-store</artifactId>
        <exclusions>
            <exclusion>
                <groupId>com.sun.jersey</groupId>
                <artifactId>*</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

I could then see my error message (which i'm yet to investigate)

       javax.ws.rs.WebApplicationException: HTTP 404 replicationController "fabric8MQ" not found

I'm not sure how best to solve this in the code base? Some thoughts:

 * We could add the above exclusion, but then how to do we ensure that libraries are added into the docker image (assuming they're required).
 * We could introduce version 1.19 of jackson to override Level DBs version, which may fix the issue
 * We could modify kubernetes-api use of jax-rs to somehow gurantee that the CXF implementation is used instead of Jackson?

I think the later is the best option. I'll keep investigating, but I wanted to capture the above as it's taken a while to unscramble!

**Comment by davidatkins** [comment]
The final option above isn't going to help, because the (presumably) older jax-rs packages provided by the jackson jar via level-db will still be on the classpath, regardless of what jax-rs implementation is being used.

**Comment by davidatkins** [comment]
I've had a look and I can't come up with a satisfactory solution other than adding the following to the surefire config:

              <classpathDependencyExcludes>
                  <classpathDependencyExcludes>com.sun.jersey:jersey-core:jar</classpathDependencyExcludes>
              </classpathDependencyExcludes>

But this isn't applied in Eclipse/IntelliJ, so classloading issue will occur. If anyone else has this issue, the quick fix is to temporarily exclude the leveldb jersey transitive dependency until you can figure out why the integration tests are throwing exceptions.
