### ISSUE TITLE
fabric8:run - Generates v1beta1 kubernetes json

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#3560]
Wonder if it should not generate v1beta2?

Here is what the camel-cdi quickstart generates today
```
{
  "id": "quickstart-java-camel-cdi-config",
  "kind": "Config",
  "apiVersion": "v1beta1",
  "name": "quickstart-java-camel-cdi-config",
  "description": "Configuration for quickstart-java-camel-cdi",
  "items": [

    {
      "id": "quickstart-java-camel-cdi-controller",
      "kind": "ReplicationController",
      "apiVersion": "v1beta1",
      "desiredState": {
        "replicas": 1,
        "replicaSelector": {
          "container": "java", 
          "group": "quickstarts"
        },
        "podTemplate": {
          "desiredState": {
            "manifest": {
              "version": "v1beta1",
              "id": "quickstart-java-camel-cdiPod",
              "containers": [
                {
                  "name": "quickstart-java-camel-cdi-container",
                  "image": "172.30.17.21:5000/fabric8/quickstart-java-camel-cdi:2.2-SNAPSHOT",
                  "imagePullPolicy": "PullAlways",
                  "env": [
                  ],
                  "ports": [
                    {
                      "containerPort": 8778
    
                    }
                  ]
                }
              ]
            }
          },
          "labels": {
            "container": "java", 
            "group": "quickstarts"
          }
        }
      },
      "labels": {
        "container": "java", 
        "group": "quickstarts"
      }
    }
  ]
}
```

It can also not run on fabric8 anymore, seems like namespace is required, the mvn goal
```
mvn install fabric8:run -Pdocker-build
```

Now fails with
```
[INFO] --- fabric8-maven-plugin:2.0.30:run (default-cli) @ quickstart-java-camel-cdi ---
[INFO] Deploying /Users/davsclaus/workspace/quickstarts/quickstarts/java/camel-cdi/target/classes/kubernetes.json to https://192.168.59.103:8443
[WARNING] Default key managers cannot be initialized: /Users/davsclaus/.keystore (No such file or directory)
[INFO] Creating a replicationController from kubernetes.json namespace  name quickstart-java-camel-cdi-controller
[WARNING] Default key managers cannot be initialized: /Users/davsclaus/.keystore (No such file or directory)
[ERROR] Failed to create replicationController from kubernetes.json. javax.ws.rs.WebApplicationException: HTTP 422 ReplicationController "quickstart-java-camel-cdi-controller" is invalid: metadata.namespace: required value. io.fabric8.kubernetes.api.model.ReplicationController@7c93907b[annotations=<null>,apiVersion=v1beta1,creationTimestamp=<null>,currentState=<null>,desiredState=io.fabric8.kubernetes.api.model.ReplicationControllerState@3bf2bb22[podTemplate=io.fabric8.kubernetes.api.model.PodTemplate@3cdbd3ed[desiredState=io.fabric8.kubernetes.api.model.PodState@4368bd2[host=<null>,hostIP=<null>,info=<null>,manifest=io.fabric8.kubernetes.api.model.ContainerManifest@19158a27[containers=[io.fabric8.kubernetes.api.model.Container@5521134e[command=[],cpu=<null>,env=[],image=172.30.17.21:5000/fabric8/quickstart-java-camel-cdi:2.2-SNAPSHOT,imagePullPolicy=PullAlways,lifecycle=<null>,livenessProbe=<null>,memory=<null>,name=quickstart-java-camel-cdi-container,ports=[io.fabric8.kubernetes.api.model.Port@6e7a918b[containerPort=8778,hostIP=<null>,hostPort=<null>,name=<null>,protocol=<null>,additionalProperties={}]],privileged=<null>,terminationMessagePath=<null>,volumeMounts=[],workingDir=<null>,additionalProperties={}]],dnsPolicy=<null>,id=quickstart-java-camel-cdiPod,restartPolicy=<null>,uuid=<null>,version=v1beta1,volumes=[],additionalProperties={}],message=<null>,podIP=<null>,status=<null>,additionalProperties={}],labels={container=java, group=quickstarts},additionalProperties={}],replicaSelector={container=java, group=quickstarts},replicas=1,additionalProperties={}],id=quickstart-java-camel-cdi-controller,kind=ReplicationController,labels={container=java, group=quickstarts},namespace=<null>,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}]
javax.ws.rs.WebApplicationException: HTTP 422 ReplicationController "quickstart-java-camel-cdi-controller" is invalid: metadata.namespace: required value
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:27)
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:11)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy52.createReplicationController(Unknown Source)
	at io.fabric8.kubernetes.api.KubernetesClient.createReplicationController(KubernetesClient.java:324)
	at io.fabric8.kubernetes.api.KubernetesClient.createReplicationController(KubernetesClient.java:316)
	at io.fabric8.kubernetes.api.Controller.applyReplicationController(Controller.java:282)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:178)
	at io.fabric8.kubernetes.api.Controller.applyConfig(Controller.java:197)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:148)
	at io.fabric8.maven.RunMojo.execute(RunMojo.java:57)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by davsclaus** [comment]
I have a pending fix in this branch
https://github.com/davsclaus/fuse/commit/9b0690db3414ed5de367ae6eb6133d7f0a6fc67c

**Comment by davsclaus** [comment]
The generated json now include namespace
```
{
  "id": "quickstart-java-camel-spring-list",
  "kind": "List",
  "namespace": "default",
  "apiVersion": "v1beta2",
  "name": "quickstart-java-camel-spring-config",
  "description": "Configuration for quickstart-java-camel-spring",
  "items": [

    {
      "id": "quickstart-java-camel-spring-controller",
      "kind": "ReplicationController",
      "namespace": "default",
      "apiVersion": "v1beta2",
      "desiredState": {
        "replicas": 1,
        "replicaSelector": {
          "container": "java", 
          "group": "quickstarts"
        },
        "podTemplate": {
          "desiredState": {
            "manifest": {
              "id": "quickstart-java-camel-springPod",
              "namespace": "default",
              "version": "v1beta2",
              "containers": [
                {
                  "name": "quickstart-java-camel-spring-container",
                  "image": "192.168.59.103:5000/fabric8/quickstart-java-camel-spring:2.2-SNAPSHOT",
                  "imagePullPolicy": "PullAlways",
                  "env": [
                  ],
                  "ports": [
                    {
                      "containerPort": 8778
    
                    }
                  ]
                }
              ]
            }
          },
          "labels": {
            "container": "java", 
            "group": "quickstarts"
          }
        }
      },
      "labels": {
        "container": "java", 
        "group": "quickstarts"
      }
    }
  ]
}
```

**Comment by hekonsek** [comment]
The workaround is to downgrade Fabric8 Maven plugin version to 2.0.25.

**Comment by davsclaus** [comment]
Yeah I posted a discussion about the namespace and beta1 v beta2 issue at the mailing list
https://groups.google.com/forum/#!topic/fabric8/_A7yzUXl-cM

**Comment by davsclaus** [comment]
We are generating v1beta2 now.
