### ISSUE TITLE
Deploying a sample project on jube (fabric8) fails

### ISSUE THREAD

**Issue by ramesh-mohan-reddy** [fabric8io/fabric8#3620]
We are running Linux RHEL v6.4 where we have Jube 2.0.33 installed. Jube is running with below env vars set

export https_proxy=
export http_proxy=
export DOCKER_REGISTRY=
export KUBERNETES_MASTER=
export FABRIC8_CONSOLE=

Now, we are using below mvn command after setting above env vars to build simple project (contained at quickstarts-master\quickstarts\java\simple-mainclass - from Github samples) 
"mvn clean install jube:build fabric8:json fabric8:deploy"

The build becomes successful, however when we go to jube fabric8 hawtio console and try to run application... we don't see pods running... instead we see below stacktrace printed on jube server console.

Stack trace says the built image is trying to be uploaded to external maven repos which we don't want.... we tried setting "upload" xml element in maven to "false" too.... however still no luck, we end up seeing same stack trace.

ERROR: Failed to create pod: quickstart-camel-servlet-8.         java.io.IOException: Failed to resolve mvn:io.fabric8.jube.images.fabric8/quickstart-war-camel-servlet/2.2-SNAPSHOT/zip/image. org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for io.fabric8.jube.images.fabric8:quickstart-war-camel-servlet:zip:image:2.2-SNAPSHOT (runtime)

java.io.IOException: Failed to resolve mvn:io.fabric8.jube.images.fabric8/quickstart-war-camel-servlet/2.2-SNAPSHOT/zip/image. org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for io.fabric8.jube.images.fabric8:quickstart-war-camel-servlet:zip:image:2.2-SNAPSHOT (runtime)

Caused by: org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for io.fabric8.jube.images.fabric8:quickstart-war-camel-servlet:zip:image:2.2-SNAPSHOT (runtime)

Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for io.fabric8.jube.images.fabric8:quickstart-war-camel-servlet:zip:image:2.2-SNAPSHOT

Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.fabric8.jube.images.fabric8:quickstart-war-camel-servlet:pom:2.2-SNAPSHOT from/to central (http://repo1.maven.org/maven2): Error transferring file: null to http://repo1.maven.org/maven2/io/fabric8/jube/images/fabric8/quickstart-war-camel-servlet/2.2-SNAPSHOT/quickstart-war-camel-servlet-2.2-SNAPSHOT.pom

Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact io.fabric8.jube.images.fabric8:quickstart-war-camel-servlet:pom:2.2-SNAPSHOT from/to central (http://repo1.maven.org/maven2): Error transferring file: null to http://repo1.maven.org/maven2/io/fabric8/jube/images/fabric8/quickstart-war-camel-servlet/2.2-SNAPSHOT/quickstart-war-camel-servlet-2.2-SNAPSHOT.pom

Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file: null to http://repo1.maven.org/maven2/io/fabric8/jube/images/fabric8/quickstart-war-camel-servlet/2.2-SNAPSHOT/quickstart-war-camel-servlet-2.2-SNAPSHOT.pom
    at org.sonatype.maven.wagon.AhcWagon.fillInputData(AhcWagon.java:301)

Caused by: java.io.IOException: null to http://repo1.maven.org/maven2/io/fabric8/jube/images/fabric8/quickstart-war-camel-servlet/2.2-SNAPSHOT/quickstart-war-camel-servlet-2.2-SNAPSHOT.pom

Caused by: java.net.ConnectException: null to http://repo1.maven.org/maven2/io/fabric8/jube/images/fabric8/quickstart-war-camel-servlet/2.2-SNAPSHOT/quickstart-war-camel-servlet-2.2-SNAPSHOT.pom
    at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:95)

Caused by: java.nio.channels.UnresolvedAddressException
    at sun.nio.ch.Net.checkAddress(Net.java:127)

Any help to resolve this is greatly appreciated.

Thanks in advance

**Comment by davsclaus** [comment]
Sounds like some network connection issue.

**Comment by ramesh-mohan-reddy** [comment]
We are behind a proxy and not in a position to change or by pass it
Could you please suggest a work around for this?

**Comment by davsclaus** [comment]
Wonder if you need to adjust your m2/settings.xml file to have maven http proxy
https://maven.apache.org/guides/mini/guide-proxies.html
