### ISSUE TITLE
karaf quickstarts don't seem to run the features/bundles/kar any more

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#3645]
tried the camel rest sql and camel EIPs and don't see any camel bundles starting up

**Comment by davsclaus** [comment]
Its likely the issue with Camel 2.15.0 dont install in osgi. Its fixed for the upcoming 2.15.1
http://camel.465427.n5.nabble.com/Apache-Camel-2-15-1-patch-release-td5764661.html

**Comment by jstrachan** [comment]
Ah thanks @davsclaus! Though I tried the CXF rest service and that didn't seem to start up any CXF mbeans either :(

**Comment by davsclaus** [comment]
I build the quickstarts using docker build profile, and tried running it locally just plain docker style
```
davsclaus:~/$ docker run -it 194b5a539044
exec: "/usr/bin/sti-helper": stat /usr/bin/sti-helper: no such file or directoryFATA[0000] Error response from daemon: Cannot start container 6d212e96258ddbbce53d52537bd2eb7d52aaba8f0dd56722f85d2d4d719775ce: exec: "/usr/bin/sti-helper": stat /usr/bin/sti-helper: no such file or directory
```

I wonder if @iocanel would know what is the problem, as it seems related to sti

**Comment by davsclaus** [comment]
It is this quickstart btw I tried: quickstart-karaf-cxf-rest

**Comment by davsclaus** [comment]
The plain java such as camel-spring runs
```
davsclaus:~/$ docker run -it 973cb2260334
I> No access restrictor found, access to all MBean is allowed
I> No suitable address found for listening on multicast discovery requests
Jolokia: Agent started with URL http://172.17.0.5:8778/jolokia/
2015-03-24 14:38:11,706 [main           ] INFO  MainSupport                    - Apache Camel 2.15.0 starting
```

**Comment by davsclaus** [comment]
Starting karaf from jube, I get this in the log
```
2015-04-01 11:25:30,090 | ERROR | FelixStartLevel  | BlueprintContainerImpl           | ?                                   ? | 14 - org.apache.aries.blueprint.core - 1.4.1 | Unable to start blueprint container for bundle org.apache.karaf.management.server
org.osgi.service.blueprint.container.ComponentDefinitionException: Error setting property: PropertyDescriptor <name: port, getter: class org.apache.karaf.management.RmiRegistryFactory.getPort(), setter: [class org.apache.karaf.management.RmiRegistryFactory.setPort(int)]
	at org.apache.aries.blueprint.container.BeanRecipe.setProperty(BeanRecipe.java:941)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:907)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.setProperties(BeanRecipe.java:888)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:820)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[14:org.apache.aries.blueprint.core:1.4.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.RefRecipe.internalCreate(RefRecipe.java:62)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:106)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.instantiateExplicitDependencies(BeanRecipe.java:241)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:804)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[14:org.apache.aries.blueprint.core:1.4.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.RefRecipe.internalCreate(RefRecipe.java:62)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:106)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:280)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:806)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[14:org.apache.aries.blueprint.core:1.4.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:681)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:378)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:269)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:276)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:245)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:235)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[9:org.apache.aries.util:1.1.0]
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1127)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:696)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:484)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4429)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2100)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)[org.apache.felix.framework-4.4.1.jar:]
	at java.lang.Thread.run(Thread.java:744)[:1.7.0_45]
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)[:1.7.0_45]
	at java.lang.Integer.parseInt(Integer.java:504)[:1.7.0_45]
	at java.lang.Integer.valueOf(Integer.java:582)[:1.7.0_45]
	at org.apache.aries.blueprint.container.AggregateConverter.convertFromString(AggregateConverter.java:281)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.AggregateConverter.convert(AggregateConverter.java:174)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintRepository.convert(BlueprintRepository.java:402)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.utils.ReflectionUtils$PropertyDescriptor.convert(ReflectionUtils.java:394)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.utils.ReflectionUtils$MethodPropertyDescriptor.internalSet(ReflectionUtils.java:628)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.utils.ReflectionUtils$PropertyDescriptor.set(ReflectionUtils.java:378)[14:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.setProperty(BeanRecipe.java:939)[14:org.apache.aries.blueprint.core:1.4.1]
	... 44 more
```

davsclaus:~/workspace/quickstarts/quickstarts/karaf/beginner/camel-log/target/jube (master)/$ ./run.sh

**Comment by davsclaus** [comment]
And that causes a number of services in karaf to fail / grace period
