### ISSUE TITLE
Exception while changing profiles "Could not acquire port lock"

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8#376]
While adding/removing an mq-broker profile multiple times (add, remove, add, remove) I eventually ended up in a situation where the child container wouldn't update anymore and when I tried to list the container in the console everything would hang (ie.. it wouldn't show any details for the containers) as well as other random things failing in FMC/hawtio.

This exception appeared  in the logs on the child container. 

Exception when tracking configurations. This exception will be ignored.
Stack Trace:
org.fusesource.fabric.api.FabricException: Could not acquire port lock
  at org.fusesource.fabric.service.ZookeeperPortService.registerPort(ZookeeperPortService.java:87)[org.fusesource.fabric:fabric-core:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.service.PortPlaceholderResolver.resolve(PortPlaceholderResolver.java:88)[org.fusesource.fabric:fabric-core:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.service.AbstractDataStore$2.getValue(AbstractDataStore.java:281)[org.fusesource.fabric:fabric-core:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.zookeeper.utils.InterpolationHelper.substVars(InterpolationHelper.java:178)[org.fusesource.fabric:fabric-zookeeper:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.service.AbstractDataStore.substituteConfigurations(AbstractDataStore.java:276)[org.fusesource.fabric:fabric-core:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.internal.ProfileOverlayImpl.getConfigurations(ProfileOverlayImpl.java:357)[org.fusesource.fabric:fabric-core:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.configadmin.FabricConfigAdminBridge.updateInternal(FabricConfigAdminBridge.java:105)[org.fusesource.fabric:fabric-configadmin:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.configadmin.FabricConfigAdminBridge.access$000(FabricConfigAdminBridge.java:50)[org.fusesource.fabric:fabric-configadmin:7.3.0.redhat-SNAPSHOT]
  at org.fusesource.fabric.configadmin.FabricConfigAdminBridge$1.run(FabricConfigAdminBridge.java:96)[org.fusesource.fabric:fabric-configadmin:7.3.0.redhat-SNAPSHOT]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_17]
  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)[:1.7.0_17]
  at java.util.concurrent.FutureTask.run(FutureTask.java:166)[:1.7.0_17]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_17]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_17]
  at java.lang.Thread.run(Thread.java:722)[:1.7.0_17]

**Comment by ianpage** [comment]
I've seen this too.  For me stopping all the containers, then brining them back up again sorted it.
