### ISSUE TITLE
ZK error when start jube 2.0.44

### ISSUE THREAD

**Issue by jimma** [fabric8io/fabric8#3776]
When start jube 2.0.44 on Fedora 20 with jdk 1.7.0_60, there are bunch of connection refused exception thrown.  I already set env  ZOOKEEPER_URL=localhost:2181 and -Djava.net.preferIPv4Stack=true.  Is this ZK configuration issue in jube ?
```
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:java.io.tmpdir=/tmp
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:java.compiler=<NA>
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:os.name=Linux
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:os.arch=amd64
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:os.version=3.15.8-200.fc20.x86_64
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:user.name=jimma
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:user.home=/home/jimma
2015-04-21 16:47:50,620 [main           ] INFO  ZooKeeper                      - Client environment:user.dir=/home/jimma/code/fabric8v2/jube/jube-2.0.44-image
2015-04-21 16:47:50,621 [main           ] INFO  ZooKeeper                      - Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@6697724f
2015-04-21 16:47:50,637 [127.0.0.1:2181)] INFO  ClientCnxn                     - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-04-21 16:47:50,646 [127.0.0.1:2181)] WARN  ClientCnxn                     - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)[:1.7.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)[:1.7.0_60]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)[zookeeper-3.4.6.jar:3.4.6-1569965]
Starting the replicator with poll time: 2000
Starting the process monitor with poll time: 2000
Writing to path: /jube/hostNodes/60a3ae6d-1993-4f80-9e09-47a9c68a21d7 createMode: EPHEMERAL json: {
  "id" : "60a3ae6d-1993-4f80-9e09-47a9c68a21d7",
  "hostName" : "localhost",
  "webUrl" : "http://localhost:8585/"
}
2015-04-21 16:47:51,747 [127.0.0.1:2181)] INFO  ClientCnxn                     - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-04-21 16:47:51,747 [127.0.0.1:2181)] WARN  ClientCnxn                     - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)[:1.7.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)[:1.7.0_60]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)[zookeeper-3.4.6.jar:3.4.6-1569965]
2015-04-21 16:47:52,848 [127.0.0.1:2181)] INFO  ClientCnxn                     - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-04-21 16:47:52,848 [127.0.0.1:2181)] WARN  ClientCnxn                     - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)[:1.7.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)[:1.7.0_60]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)[zookeeper-3.4.6.jar:3.4.6-1569965]
2015-04-21 16:47:53,949 [127.0.0.1:2181)] INFO  ClientCnxn                     - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
```

**Comment by jimma** [comment]
There is a similar error : http://stackoverflow.com/questions/7755525/why-this-error-is-coming-in-zookeeper

**Comment by davsclaus** [comment]
Do you have an external ZooKeeper server running on localhost and port 2181? 

Jube comes with ZK out of the box, but if you want to use an external then you can set  those ENV variables AFAIR.

**Comment by davsclaus** [comment]
I just downloaded zookeeper 3.4.6 and started it according to
https://zookeeper.apache.org/doc/trunk/zookeeperStarted.html

And then configure jube to use the env you talked about and jube was able to connect to this external ZK server. So this is working as expected.

**Comment by davsclaus** [comment]
See the JUBE faq also
http://fabric8.io/jube/faqConfig.html#how-do-i-run-jube-on-multiple-hosts-
