### ISSUE TITLE
osgi:install fab:mvn:groupid/artifactid/version is throwing errors

### ISSUE THREAD

**Issue by raghunila** [fabric8io/fabric8#3816]
I am using fabric8-karaf-1.2.0.Beta4 and trying to deploy camel route using 
osgi:install fab:mvn:groupid/artifactid/version command. I have received below errors.

How ever it works fine with osgi:install -s file://${path}/jar

How to resolve this dependency issue. thanks in advance.

2015-04-24 15:19:26,843 | ERROR | l Console Thread | FabResolver                      | olverFactoryImpl$FabResolverImpl  165 | 109 - io.fabric8.fab.fab-osgi - 1.0.0.redhat-379 | Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
2015-04-24 15:19:26,843 | ERROR | l Console Thread | FabResolver                      | olverFactoryImpl$FabResolverImpl  168 | 109 - io.fabric8.fab.fab-osgi - 1.0.0.redhat-379 | Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:317)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:172)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:316)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependencies(MavenResolverImpl.java:312)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependenciesFromPom(MavenResolverImpl.java:294)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependencies(MavenResolverImpl.java:263)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.collectDependencyTree(FabResolverFactoryImpl.java:148)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabClassPathResolver.resolve(FabClassPathResolver.java:135)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.configureInstructions(FabResolverFactoryImpl.java:279)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.createInstructions(FabResolverFactoryImpl.java:271)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.getInfo(FabResolverFactoryImpl.java:241)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.installMissingDependencies(FabConnection.java:222)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.getInputStream(FabConnection.java:102)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.installMissingDependencies(FabConnection.java:226)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.getInputStream(FabConnection.java:102)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:524)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:165)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.Felix.installBundle(Felix.java:3117)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.karaf.shell.osgi.InstallBundle.doExecute(InstallBundle.java:43)[31:org.apache.karaf.shell.osgi:2.3.0.redhat-610379]
  at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.karaf.shell.console.jline.Console.run(Console.java:189)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.karaf.shell.console.jline.DelayedStarted.run(DelayedStarted.java:61)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:126)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:819)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:670)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:308)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:308)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 35 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:541)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:220)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:197)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:122)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 40 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:945)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:940)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.flush(WagonRepositoryConnector.java:695)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.flush(WagonRepositoryConnector.java:689)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.get(WagonRepositoryConnector.java:445)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:460)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 43 more
2015-04-24 15:19:26,844 | ERROR | l Console Thread | FabConnection                    | .fab.osgi.internal.FabConnection  238 | 109 - io.fabric8.fab.fab-osgi - 1.0.0.redhat-379 | Failed to deploy file:/Users/rnila/.m2/repository/org/jboss/javaee/jboss-jacc-api_JDK4/1.1.0/jboss-jacc-api_JDK4-1.1.0.jar due to error: java.io.IOException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
java.io.IOException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.getInfo(FabResolverFactoryImpl.java:256)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.installMissingDependencies(FabConnection.java:222)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.getInputStream(FabConnection.java:102)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.installMissingDependencies(FabConnection.java:226)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.getInputStream(FabConnection.java:102)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:524)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:165)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.Felix.installBundle(Felix.java:3117)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.karaf.shell.osgi.InstallBundle.doExecute(InstallBundle.java:43)[31:org.apache.karaf.shell.osgi:2.3.0.redhat-610379]
  at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.karaf.shell.console.jline.Console.run(Console.java:189)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.karaf.shell.console.jline.DelayedStarted.run(DelayedStarted.java:61)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:317)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:172)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:316)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependencies(MavenResolverImpl.java:312)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependenciesFromPom(MavenResolverImpl.java:294)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependencies(MavenResolverImpl.java:263)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.collectDependencyTree(FabResolverFactoryImpl.java:148)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabClassPathResolver.resolve(FabClassPathResolver.java:135)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.configureInstructions(FabResolverFactoryImpl.java:279)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.createInstructions(FabResolverFactoryImpl.java:271)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.getInfo(FabResolverFactoryImpl.java:241)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 25 more
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:126)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:819)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:670)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:308)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:308)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 35 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:541)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:220)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:197)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:122)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 40 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:945)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:940)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.flush(WagonRepositoryConnector.java:695)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.flush(WagonRepositoryConnector.java:689)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.get(WagonRepositoryConnector.java:445)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:460)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 43 more
2015-04-24 15:19:26,846 | ERROR | l Console Thread | FabConnection                    | .fab.osgi.internal.FabConnection  238 | 109 - io.fabric8.fab.fab-osgi - 1.0.0.redhat-379 | Failed to deploy file:/Users/rnila/.m2/repository/org/hibernate/hibernate-core/3.6.9.Final/hibernate-core-3.6.9.Final.jar due to error: java.io.IOException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
java.io.IOException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.getInfo(FabResolverFactoryImpl.java:256)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.installMissingDependencies(FabConnection.java:222)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.getInputStream(FabConnection.java:102)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.installMissingDependencies(FabConnection.java:226)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabConnection.getInputStream(FabConnection.java:102)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:524)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:165)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.Felix.installBundle(Felix.java:3117)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)[org.apache.felix.framework-4.0.3.redhat-610379.jar:]
  at org.apache.karaf.shell.osgi.InstallBundle.doExecute(InstallBundle.java:43)[31:org.apache.karaf.shell.osgi:2.3.0.redhat-610379]
  at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)[15:org.apache.felix.gogo.runtime:0.11.0.redhat-610379]
  at org.apache.karaf.shell.console.jline.Console.run(Console.java:189)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
  at org.apache.karaf.shell.console.jline.DelayedStarted.run(DelayedStarted.java:61)[17:org.apache.karaf.shell.console:2.3.0.redhat-610379]
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.jboss.javaee:jboss-jacc-api_1.1_JDK4:pom:1.0
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:317)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:172)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:316)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependencies(MavenResolverImpl.java:312)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependenciesFromPom(MavenResolverImpl.java:294)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.MavenResolverImpl.collectDependencies(MavenResolverImpl.java:263)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.collectDependencyTree(FabResolverFactoryImpl.java:148)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabClassPathResolver.resolve(FabClassPathResolver.java:135)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.configureInstructions(FabResolverFactoryImpl.java:279)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.createInstructions(FabResolverFactoryImpl.java:271)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at io.fabric8.fab.osgi.internal.FabResolverFactoryImpl$FabResolverImpl.getInfo(FabResolverFactoryImpl.java:241)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 25 more
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:126)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:819)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:670)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:308)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:308)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 35 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:541)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:220)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:197)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:122)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  ... 40 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jboss.javaee:jboss-javaee-parent:pom:6.0.0-SNAPSHOT in repos0 (http://repo1.maven.org/maven2)
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:945)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:940)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.flush(WagonRepositoryConnector.java:695)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.flush(WagonRepositoryConnector.java:689)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.get(WagonRepositoryConnector.java:445)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:460)[109:io.fabric8.fab.fab-osgi:1.0.0.redhat-379]
- See more at: https://developer.jboss.org/message/926913#926913

**Comment by davsclaus** [comment]
FAB is deprecated and removed in Fuse 6.2, so I suggest not to use that.
