### ISSUE TITLE
Sonarqube is not working when deployed on openshiftv3

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#3985]
The sonarqube kube app is not working when deployed on openshiftv3

````
org.jruby.rack.RackInitializationException: no connection available
	from arjdbc/jdbc/RubyJdbcConnection.java:517:in `set_native_database_types'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.1.3/lib/arjdbc/jdbc/connection.rb:61:in `initialize'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.1.3/lib/arjdbc/jdbc/adapter.rb:31:in `initialize'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.1.3/lib/arjdbc/jdbc/connection_methods.rb:6:in `jdbc_connection'
	from org/jruby/RubyKernel.java:2225:in `send'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:223:in `new_connection'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:245:in `checkout_new_connection'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:188:in `checkout'
	from org/jruby/RubyKernel.java:1517:in `loop'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:184:in `checkout'
	from jar:file:/opt/sonar/web/WEB-INF/lib/jruby-complete-1.7.6.jar!/META-INF/jruby.home/lib/ruby/1.8/monitor.rb:191:in `mon_synchronize'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:183:in `checkout'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:98:in `connection'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_pool.rb:326:in `retrieve_connection'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_specification.rb:123:in `retrieve_connection'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/connection_adapters/abstract/connection_specification.rb:115:in `connection'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/migration.rb:440:in `initialize'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/migration.rb:401:in `up'
	from /opt/sonar/web/WEB-INF/gems/gems/activerecord-2.3.15/lib/active_record/migration.rb:383:in `migrate'
	from /opt/sonar/web/WEB-INF/lib/database_version.rb:62:in `upgrade_and_start'
	from /opt/sonar/web/WEB-INF/lib/database_version.rb:74:in `automatic_setup'
	from /opt/sonar/web/WEB-INF/config/environment.rb:236:in `(root)'
	from org/jruby/RubyKernel.java:1096:in `load'
	from file:/opt/sonar/web/WEB-INF/lib/jruby-rack-1.1.13.2.jar!/jruby/rack/rails/environment2.rb:1:in `(root)'
	from file:/opt/sonar/web/WEB-INF/lib/jruby-rack-1.1.13.2.jar!/jruby/rack/rails/environment2.rb:25:in `load_environment'
	from file:/opt/sonar/web/WEB-INF/lib/jruby-rack-1.1.13.2.jar!/jruby/rack/rails_booter.rb:79:in `load_environment'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:98)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)
Caused by: org.jruby.exceptions.RaiseException: (ConnectionNotEstablished) no connection available
	at arjdbc.jdbc.RubyJdbcConnection.set_native_database_types(arjdbc/jdbc/RubyJdbcConnection.java:517)
	at RUBY.initialize(/opt/sonar/web/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.1.3/lib/arjdbc/jdbc/connection.rb:61)
	at RUBY.initialize(/opt/sonar/web/WEB-INF/gems/gems/activerecord-jdbc-adapter-1.1.3/lib/arjdbc/jdbc/adapter.rb:31)
````

Docker logs of the pods don't mention any error 

````
docker ps | grep sonar
ef150b24c419        tpires/sonar-mysql:latest                 "mysqld_safe"          32 minutes ago      Up 32 minutes                                                                          k8s_sonarqube-database-container.fe161536_sonarqube-controller-t9lpl_default_d025d5c1-ffb2-11e4-b3b5-0800275503ae_23ee1647
64921e44db5b        tpires/sonar-server:latest                "/opt/sonar/bin/linu   34 minutes ago      Up 34 minutes                                                                          k8s_sonarqube-server-container.681d34f7_sonarqube-controller-t9lpl_default_d025d5c1-ffb2-11e4-b3b5-0800275503ae_0de7a317
bd7437f59c54        openshift/origin-pod:v0.5.1               "/pod"                 39 minutes ago      Up 39 minutes                                                                          k8s_POD.c07c230f_sonarqube-controller-t9lpl_default_d025d5c1-ffb2-11e4-b3b5-0800275503ae_433b102b

dabou:~/Fuse/projects$ docker logs ef150b24c419
150521 12:20:41 mysqld_safe Logging to syslog.
150521 12:20:41 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql

dabou:~/Fuse/projects$ docker logs 64921e44db5b
Running sonar...
````

**Comment by cmoulliard** [comment]
Problem is perhaps related to the issue with the name of the sonar-mysql container as explained here : 

```
First you need to configure sonar-mysql and name it “smysql”.

Now you need to run the server and link it with the database. That link will be named “db”.

docker run -i -t -d –name sonar -p 9000:9000 –link smysql:db tpires/sonar-server

You can now access to sonar-server by opening your browser to http://localhost:9000 . Default username:password is admin:admin .
```
