### ISSUE TITLE
Kuber service - spec.ports[0].protocol: unsupported value 'HTTP'

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4008]
When `mvn fabric8:apply` (version 2.1.5) is executed with this Model

```
    public void onList(TemplateBuilder builder) {
        builder.addNewServiceObject()
                .withNewMetadata()
                  .withName("gerrit-http-service")
                  .addToLabels("component", "gerrit")
                  .addToLabels("provider", "fabric8")
                .endMetadata()
                .withNewSpec()
                  .addNewPort()
                    .withProtocol("HTTP")
                    .withPort(80)
                      .withNewTargetPort(8080)
                    .endPort()
                    .addToSelector("component", "gerrit")
                    .addToSelector("provider", "fabric8")
                .endSpec()
                .endServiceObject()
                // Second service
                .addNewServiceObject()
                .withNewMetadata()
                  .withName("gerrit-ssh-service")
                  .addToLabels("component", "gerrit")
                  .addToLabels("provider", "fabric8")
                .endMetadata()
                .withNewSpec()
                  .addNewPort()
                    .withProtocol("SSH")
                    .withPort(29418)
                      .withNewTargetPort(29418)
                    .endPort()
                    .addToSelector("component", "gerrit")
                    .addToSelector("provider", "fabric8")
                .endSpec()
                .endServiceObject()
                .build();
    }
```
we get this error : 

```
[ERROR] Failed to create service from kubernetes.json. javax.ws.rs.WebApplicationException: HTTP 422 Service "gerrit-http-service" is invalid: spec.ports[0].protocol: unsupported value 'HTTP'. io.fabric8.kubernetes.api.model.Service@499fa9b0[apiVersion=v1beta3,kind=Service,metadata=io.fabric8.kubernetes.api.model.ObjectMeta@113d8793[annotations={},creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={component=gerrit, provider=fabric8},name=gerrit-http-service,namespace=default,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],spec=io.fabric8.kubernetes.api.model.ServiceSpec@5e8fccbc[createExternalLoadBalancer=<null>,portalIP=<null>,ports=[io.fabric8.kubernetes.api.model.ServicePort@32ca7b24[name=<null>,port=80,protocol=HTTP,targetPort=io.fabric8.kubernetes.api.model.util.IntOrString@1bdab192[IntVal=8080,Kind=<null>,StrVal=<null>,additionalProperties={}],additionalProperties={}]],publicIPs=[],selector={component=gerrit, provider=fabric8},sessionAffinity=<null>,additionalProperties={}],status=<null>,additionalProperties={}]
javax.ws.rs.WebApplicationException: HTTP 422 Service "gerrit-http-service" is invalid: spec.ports[0].protocol: unsupported value 'HTTP'
        at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:25)
        at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:16)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
        at com.sun.proxy.$Proxy54.createService(Unknown Source)
        at io.fabric8.kubernetes.api.KubernetesClient.createService(KubernetesClient.java:528)

```

**Comment by cmoulliard** [comment]
The protocol to be used is "TCP" and not "HTTP" or "SSH"
