### ISSUE TITLE
Forge commands - Use docker.io as prefix for base image to have it work offline

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4160]
@rhuss investigated and found a viable workaround

[14:41:23]  <ro14nd>	 thx, will continue to search. A workaround for that on the plugin side shouldn't be hard. But as a rule of thumb: Always use the full quailified name with 'docker.io/' and you should be on the safe side since no name conversion will happen then.
[14:42:03]  <ro14nd>	 davsclaus: To summarize, dmp should work offline as expected (and it did for me many times ;-) except for this bug.

**Comment by davsclaus** [comment]
Ah maybes its a bug on OS3 @rhuss found
https://bugzilla.redhat.com/show_bug.cgi?id=1215934

**Comment by rhuss** [comment]
Its indeed not OS3 fault, but Fedoras/Centos'

**Comment by davsclaus** [comment]
Argh seems latest code has a forge issue, 

```
Press <ENTER> to confirm, or <CTRL>+C to cancel.
* from (The docker image to use as base line): [0-1] 0
***ERROR*** Error while executing 'io.fabric8.forge.camel.commands.project.FabricStepCommand'
org.jboss.forge.addon.facets.FacetNotFoundException: No Facet of type [interface org.jboss.forge.addon.projects.facets.ResourcesFacet] is installed.
	at org.jboss.forge.addon.facets.AbstractFaceted.getFacet(AbstractFaceted.java:51)
	at io.fabric8.forge.camel.commands.project.FabricStepCommand.execute(FabricStepCommand.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.camel.commands.project.FabricStepCommand_$$_javassist_b74913ec-8e80-413a-8c72-069e99d45175.execute(FabricStepCommand_$$_javassist_b74913ec-8e80-413a-8c72-069e99d45175.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:153)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:152)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:82)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:325)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
***ERROR*** No Facet of type [interface org.jboss.forge.addon.projects.facets.ResourcesFacet] is installed.
```

**Comment by davsclaus** [comment]
Works now in offline mode - I could build the project locally and run on docker without wifi
