### ISSUE TITLE
When generating a Template with the java builders it incorrectly wraps it in a List

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4167]
We then receive the following error when doing a fabric8:apply

```
[INFO] Kubernetes JSON: /Users/jamesrawlings/fabric8/quickstarts/apps/letschat/target/classes/kubernetes.json
[INFO] Creating a template from kubernetes.json namespace cheese name letschat
[INFO] Created template: apps/letschat/target/fabric8/applyJson/cheese/template-letschat-5.json
[INFO] Creating Template null:letschat parameters:
[ERROR] Failed to create controller from kubernetes.json. java.lang.IllegalArgumentException: No namespace supported for parameters: . io.fabric8.openshift.api.model.template.Template@1d7d593b[apiVersion=v1beta3,kind=Template,labels={},metadata=io.fabric8.kubernetes.api.model.ObjectMeta@106d3f9d[annotations={},creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={},name=letschat,namespace=<null>,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],objects=[io.fabric8.kubernetes.api.model.ReplicationController@746b64d7[apiVersion=v1beta3,kind=ReplicationController,metadata=io.fabric8.kubernetes.api.model.ObjectMeta@36a99af7[annotations={},creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={},name=letschat,namespace=<null>,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],spec=io.fabric8.kubernetes.api.model.ReplicationControllerSpec@38fcea2a[replicas=1,selector={},template=io.fabric8.kubernetes.api.model.PodTemplateSpec@647188a0[metadata=io.fabric8.kubernetes.api.model.ObjectMeta@59c0f3e4[annotations={},creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={},name=letschat,namespace=<null>,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],spec=io.fabric8.kubernetes.api.model.PodSpec@acc2bc5[activeDeadlineSeconds=<null>,containers=[io.fabric8.kubernetes.api.model.Container@624d980c[args=[],capabilities=<null>,command=[],env=[],image=fabric8/lets-chat:2.2-SNAPSHOT,imagePullPolicy=<null>,lifecycle=<null>,livenessProbe=<null>,name=letschat,ports=[io.fabric8.kubernetes.api.model.ContainerPort@54396e3f[containerPort=5000,hostIP=<null>,hostPort=<null>,name=<null>,protocol=TCP,additionalProperties={}]],privileged=<null>,readinessProbe=<null>,resources=<null>,securityContext=<null>,terminationMessagePath=<null>,volumeMounts=[],workingDir=<null>,additionalProperties={}], io.fabric8.kubernetes.api.model.Container@675154c[args=[],capabilities=<null>,command=[],env=[io.fabric8.kubernetes.api.model.EnvVar@70c933e3[name=LCB_DATABASE_URI,value=mongodb://127.0.0.1:27017/letschat,valueFrom=<null>,additionalProperties={}]],image=mongo,imagePullPolicy=<null>,lifecycle=<null>,livenessProbe=<null>,name=letschat-mongodb,ports=[io.fabric8.kubernetes.api.model.ContainerPort@296db5ee[containerPort=27017,hostIP=<null>,hostPort=<null>,name=<null>,protocol=TCP,additionalProperties={}]],privileged=<null>,readinessProbe=<null>,resources=<null>,securityContext=<null>,terminationMessagePath=<null>,volumeMounts=[],workingDir=<null>,additionalProperties={}]],dnsPolicy=<null>,host=<null>,hostNetwork=<null>,imagePullSecrets=[],nodeSelector={},restartPolicy=<null>,serviceAccount=<null>,terminationGracePeriodSeconds=<null>,volumes=[],additionalProperties={}],additionalProperties={}],templateRef=<null>,additionalProperties={}],status=<null>,additionalProperties={}], io.fabric8.kubernetes.api.model.Service@61c33181[apiVersion=v1beta3,kind=Service,metadata=io.fabric8.kubernetes.api.model.ObjectMeta@55e73e4b[annotations={},creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={},name=letschat,namespace=<null>,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],spec=io.fabric8.kubernetes.api.model.ServiceSpec@40aad9fc[createExternalLoadBalancer=<null>,portalIP=<null>,ports=[io.fabric8.kubernetes.api.model.ServicePort@10cd508f[name=<null>,nodePort=<null>,port=80,protocol=<null>,targetPort=io.fabric8.kubernetes.api.model.util.IntOrString@9ae8ede[IntVal=5000,Kind=<null>,StrVal=<null>,additionalProperties={}],additionalProperties={}]],publicIPs=[],selector={name=letschat},sessionAffinity=<null>,type=<null>,additionalProperties={}],status=<null>,additionalProperties={}]],parameters=[],additionalProperties={}]
java.lang.IllegalArgumentException: No namespace supported for parameters:
	at io.fabric8.kubernetes.api.KubernetesClient.validateNamespace(KubernetesClient.java:1063)
	at io.fabric8.kubernetes.api.KubernetesClient.processTemplate(KubernetesClient.java:679)
	at io.fabric8.kubernetes.api.Controller.processTemplate(Controller.java:398)
	at io.fabric8.kubernetes.api.Controller.applyTemplate(Controller.java:312)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:223)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:196)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:191)
```

JSON that is generated is..

```JSON
{
  "apiVersion" : "v1beta3",
  "items" : [ {
    "apiVersion" : "v1beta3",
    "kind" : "Template",
    "labels" : { },
    "metadata" : {
      "annotations" : { },
      "labels" : { },
      "name" : "letschat"
    },
    "objects" : [ {
      "apiVersion" : "v1beta3",
      "kind" : "ReplicationController",
      "metadata" : {
        "annotations" : { },
        "labels" : { },
        "name" : "letschat"
      },
      "spec" : {
        "replicas" : 1,
        "selector" : { },
        "template" : {
          "metadata" : {
            "annotations" : { },
            "labels" : { },
            "name" : "letschat"
          },
          "spec" : {
            "containers" : [ {
              "args" : [ ],
              "command" : [ ],
              "env" : [ ],
              "image" : "fabric8/lets-chat:2.2-SNAPSHOT",
              "name" : "letschat",
              "ports" : [ {
                "containerPort" : 5000,
                "protocol" : "TCP"
              } ],
              "volumeMounts" : [ ]
            }, {
              "args" : [ ],
              "command" : [ ],
              "env" : [ {
                "name" : "LCB_DATABASE_URI",
                "value" : "mongodb://127.0.0.1:27017/letschat"
              } ],
              "image" : "mongo",
              "name" : "letschat-mongodb",
              "ports" : [ {
                "containerPort" : 27017,
                "protocol" : "TCP"
              } ],
              "volumeMounts" : [ ]
            } ],
            "imagePullSecrets" : [ ],
            "nodeSelector" : { },
            "volumes" : [ ]
          }
        }
      }
    }, {
      "apiVersion" : "v1beta3",
      "kind" : "Service",
      "metadata" : {
        "annotations" : { },
        "labels" : { },
        "name" : "letschat"
      },
      "spec" : {
        "ports" : [ {
          "port" : 80,
          "targetPort" : 5000
        } ],
        "publicIPs" : [ ],
        "selector" : {
          "name" : "letschat"
        }
      }
    } ],
    "parameters" : [ ]
  } ],
  "kind" : "List"
}
```

If it isn't wrapped in `"kind" : "List"` then it is applied successfully.

**Comment by gashcrumb** [comment]
FYI as a workaround you can drag/drop it into one of the fabric8-console's kubernetes views, it can unwrap the list and apply each item individually...

**Comment by rawlingsj** [comment]
Ah thanks @gashcrumb, yeah that's a pretty neat feature.
