### ISSUE TITLE
Error from KubernetesHelper on OSO v1

### ISSUE THREAD

**Issue by rajdavies** [fabric8io/fabric8#4262]
Getting No namespace supported calling KubernetesHelper from a process running inside openshift - ring a bell with anyone? Stacktrace is this:

2015-06-20 06:42:13 ERROR KubernetesControl:102 - Failed to pollBrokers
java.lang.IllegalArgumentException: No namespace supported
	at io.fabric8.kubernetes.api.KubernetesClient.validateNamespace(KubernetesClient.java:1083)
	at io.fabric8.kubernetes.api.KubernetesClient.getPods(KubernetesClient.java:199)
	at io.fabric8.kubernetes.api.KubernetesHelper.getFilteredPodMap(KubernetesHelper.java:578)
	at io.fabric8.kubernetes.api.KubernetesHelper.getSelectedPodMap(KubernetesHelper.java:570)
	at io.fabric8.kubernetes.api.KubernetesHelper.getSelectedPodMap(KubernetesHelper.java:565)
	at io.fabric8.mq.coordination.KubernetesControl.pollBrokers(KubernetesControl.java:81)

**Comment by jimmidyson** [comment]
You have to specify what namespace you're searching in. There should be an env var called KUBERNETES_NAMESPACE available in your pods if you've used the fabric8 maven plugin to generate your manifest that holds the namespace your pod is in - you should be able to use that.

**Comment by jstrachan** [comment]
The KubernetesClient tries to default the namespace from the config file that's updated whenever you do:

    oc login

Or

    oc project

I wonder if KubernetesClient should always ensure that namespace is not null? Eg use 'default' if no other value is set or discovered?

**Comment by rajdavies** [comment]
my bad - I'd assumed KubernetesHelper defaulted to the current namespace if it wasn't supplied
