### ISSUE TITLE
Unable to connect to the server: net/http: TLS handshake timeout 

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8#4399]
After running up the vagrant image and running the cdelivery everything starts ok.
After a while when running: oc get pods which showed all pods I get the above error.
On my browser I start to get 503 Service Unavailable errors
Other than running it up to take some hawtio screenshots I haven't done anything else.

Previously, I tried creating a project and running it through Jenkins and this happened during a build.

**Comment by chiippy** [comment]
No sure if any update with this issue as I am trying the Cdelivery packaging and I am having the same problem.  Managed to get the test project built a few times, then Vagrant has gone into a halt with either no logging in the journal or sometime do have some repeated logs. When accessing the server, I am getting the same error message as the subject line.

Eventually, the vagrant journal shows as following : 

Sep 10 10:01:31 vagrant.f8 openshift[1035]: /usr/lib/golang/src/net/http/server.go:1703 +0x19a
Sep 10 10:01:31 vagrant.f8 openshift[1035]: net/http.(*conn).serve(0xc214edb180)
Sep 10 10:01:31 vagrant.f8 openshift[1035]: /usr/lib/golang/src/net/http/server.go:1204 +0xb57
Sep 10 10:01:31 vagrant.f8 openshift[1035]: created by net/http.(*Server).Serve
Sep 10 10:01:31 vagrant.f8 openshift[1035]: /usr/lib/golang/src/net/http/server.go:1751 +0x35e
Sep 10 10:01:31 vagrant.f8 openshift[1035]: goroutine 66744 [select, 40 minutes]:
Sep 10 10:01:31 vagrant.f8 openshift[1035]: github.com/coreos/go-etcd/etcd.func·003()
Sep 10 10:01:31 vagrant.f8 openshift[1035]: /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/
go-etcd/etcd/requests.go:147 +0x367
Sep 10 10:01:31 vagrant.f8 openshift[1035]: created by github.com/coreos/go-etcd/etcd.(*Client).SendRequest
Sep 10 10:01:31 vagrant.f8 openshift[1035]: /go/src/github.com/openshift/origin/Godeps/_workspace/src/github.com/coreos/
go-etcd/etcd/requests.go:168 +0x3e3
Sep 10 10:01:31 vagrant.f8 openshift[1035]: goroutine 88494 [runnable]:
Sep 10 10:01:31 vagrant.f8 openshift[1035]: net/http.(*persistConn).writeLoop(0xc20a6a89a0)
Sep 10 10:01:31 vagrant.f8 openshift[1035]: /usr/lib/golang/src/net/http/transport.go:945 +0x41d
Sep 10 10:01:31 vagrant.f8 openshift[1035]: created by net/http.(*Transport).dialConn
Sep 10 10:01:31 vagrant.f8 openshift[1035]: /usr/lib/golang/src/net/http/transport.go:661 +0xcbc
Sep 10 10:01:31 vagrant.f8 systemd[1]: openshift.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 10 10:01:31 vagrant.f8 systemd[1]: Unit openshift.service entered failed state.

Then the system seems totally dead except the docker inside seems to be still running.

**Comment by davsclaus** [comment]
Have anyone tried using the latest release and seen if there is any such problems?
