### ISSUE TITLE
adapt fabric8:apply goal to work with plain Kubernetes config on GKE

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4424]
if using plain kubernetes on GKE we get the following exception when running fabric8:apply

Note: `~/.kube/config` is used by vanilla kubernetes so maven plugin tries to work with that file as if it was the one from openshift, there must be some difference.

```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.5:apply (default-cli) on project hubot-slack: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.2.5:apply failed: port out of range:-1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.5:apply (default-cli) on project hubot-slack: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.2.5:apply failed: port out of range:-1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.2.5:apply failed: port out of range:-1
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
	at io.fabric8.kubernetes.api.KubernetesHelper.isServiceSsl(KubernetesHelper.java:1408)
	at io.fabric8.kubernetes.api.KubernetesFactory.setAddress(KubernetesFactory.java:420)
	at io.fabric8.kubernetes.api.KubernetesFactory.configureFromKubeConfig(KubernetesFactory.java:180)
	at io.fabric8.kubernetes.api.KubernetesFactory.init(KubernetesFactory.java:112)
	at io.fabric8.kubernetes.api.KubernetesFactory.<init>(KubernetesFactory.java:99)
	at io.fabric8.kubernetes.api.KubernetesFactory.<init>(KubernetesFactory.java:94)
	at io.fabric8.kubernetes.api.KubernetesFactory.<init>(KubernetesFactory.java:90)
	at io.fabric8.kubernetes.api.KubernetesClient.<init>(KubernetesClient.java:86)
	at io.fabric8.maven.AbstractNamespacedMojo.getKubernetes(AbstractNamespacedMojo.java:52)
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:152)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
```

**Comment by jstrachan** [comment]
@rawlingsj I wonder if this is fixed now?

**Comment by rawlingsj** [comment]
I'll expect it is, I'll give it a whirl this morning.
