### ISSUE TITLE
fabric8-forge regression on 2.2.17 with the new client

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4561]
it fails to use the fabric8 service account; it uses 'default' instead so can't startup any more
```
org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:|Exception 0 :|io.fabric8.kubernetes.client.KubernetesClientException: User "system:serviceaccount:default:default" cannot get services in project "default"|?at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:470)|?at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:499)|?at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:108)|?at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.getIfExists(BaseOperation.java:117)|?at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1261)|?at io.fabric8.cdi.Services.toServiceUrl(Services.java:38)|?at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:47)|?at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:26)|?at io.fabric8.cdi.bean.ProducerBean.create(ProducerBean.java:42)|?at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:861)|?at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)|?at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)|?at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)|?at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)|?at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:179)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:861)|?at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)|?at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)|?at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)|?at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)|?at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:179)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:861)|?at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)|?at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:375)|?at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:386)|?at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)|?at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)|?at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:159)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:861)|?at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)|?at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:375)|?at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:386)|?at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)|?at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)|?at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:159)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:69)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:784)|?at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:61)|?at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:85)|?at org.apache.cxf.cdi.JAXRSCdiResourceExtension.load(JAXRSCdiResourceExtension.java:83)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:606)|?at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)|?at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)|?at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)|?at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)|?at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)|?at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)|?at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)|?at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)|?at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)|?at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)|?at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:54)|?at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)|?at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)|?at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:447)|?at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)|?at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:195)|?at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:61)|?at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)|?at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:65)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:274)|?at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)|?at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)|?at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)|?at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)|?at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)|?at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)|?at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)|?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)|?at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:455)|?at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)|?at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)|?at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)|?at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)|?at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)|?at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)|?at org.eclipse.jetty.server.Server.start(Server.java:387)|?at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)|?at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)|?at org.eclipse.jetty.server.Server.doStart(Server.java:354)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)|?at java.security.AccessController.doPrivileged(Native Method)|?at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:606)|?at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)|?at org.eclipse.jetty.start.Main.start(Main.java:817)|?at org.eclipse.jetty.start.Main.main(Main.java:112)|
```

**Comment by jstrachan** [comment]
we have removed secrets now - so its looking like the serviceAccountName `fabric8` is not being recognised by OpenShift 1.0.3?

A horrid hack for now....
```
oadm policy add-cluster-role-to-user cluster-admin system:serviceaccount:default:default
```

**Comment by jstrachan** [comment]
turns out that due to this https://github.com/fabric8io/fabric8/issues/4559 I was using the 'oc' binary which was 1.0.0 - which breaks serviceAccountName on 1.0.3 of openshift! DOH
