### ISSUE TITLE
Jenkins workflow scripts are not pre-populated in dropdown of create project

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4617]
Following stackstrace in forge pod..

```
Performing a pull in git repository /tmp/fabric8-forge/jenkinsWorkflows/.git on remote URL: https://github.com/fabric8io/jenkins-workflow-library.git
Failed to pull from the remote git repo with credentials org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider@229ce277 due: null. This exception is ignored.
java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:857)[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.api.RebaseCommand.call(RebaseCommand.java:293)[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:316)[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at io.fabric8.forge.rest.main.ProjectFileSystem.doPull(ProjectFileSystem.java:180)[fabric8-forge-core-2.2.19.jar:2.2.19]
	at io.fabric8.forge.rest.main.ProjectFileSystem.cloneOrPullRepo(ProjectFileSystem.java:146)[fabric8-forge-core-2.2.19.jar:2.2.19]
	at io.fabric8.forge.rest.main.ProjectFileSystem$1.run(ProjectFileSystem.java:105)[fabric8-forge-core-2.2.19.jar:2.2.19]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)[:1.7.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)[:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_65]
```

**Comment by rawlingsj** [comment]
This seems to be an intermittent problem.  A new deployment of the same version resulted in the the list being populated.  Will keep this issue open for now.

**Comment by jstrachan** [comment]
Think this is caused by a failure to pull down the library from github - I just hit that too today. 

Not sure how best to solve this one - bake the list of workflows into the jenkins image?

**Comment by rawlingsj** [comment]
this is fixed now
