### ISSUE TITLE
Profile my-test-profile does not exist even though profile-list lists it

### ISSUE THREAD

**Issue by dowhiletrue** [fabric8io/fabric8#4701]
JBossFuse:karaf@root> profile-list | grep my-test-profile
my-test-profile                                           jboss-fuse-full

JBossFuse:karaf@root> container-add-profile root my-test-profile 
Error executing command: Profile my-test-profile does not exist.

Exception caught while executing command
java.lang.IllegalArgumentException: Profile my-test-profile does not exist.
	at io.fabric8.boot.commands.support.FabricCommand.getExistingProfiles(FabricCommand.java:162)
	at io.fabric8.commands.ContainerAddProfileAction.doExecute(ContainerAddProfileAction.java:51)
	at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)
	at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_80]
	at org.apache.aries.proxy.impl.ProxyHandler$1.invoke(ProxyHandler.java:54)[18:org.apache.aries.proxy.impl:1.0.4]
	at org.apache.aries.proxy.impl.ProxyHandler.invoke(ProxyHandler.java:119)[18:org.apache.aries.proxy.impl:1.0.4]
	at io.fabric8.commands.$ContainerAddProfile590668628.execute(Unknown Source)[mvn:org.apache.aries.proxy/org.apache.aries.proxy.impl/1.0.4:]
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.karaf.shell.console.jline.Console.run(Console.java:195)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]
	at org.apache.karaf.shell.console.jline.DelayedStarted.run(DelayedStarted.java:79)[34:org.apache.karaf.shell.console:2.4.0.redhat-620133]

**Comment by dowhiletrue** [comment]
The problem is that the profile does not exist in right version since I'm in version 1.2 but the profile gets imported into the default version using profile-import without the --version flag
