### ISSUE TITLE
Kubernetes API Fails on forbidden pod

### ISSUE THREAD

**Issue by hamsal** [fabric8io/fabric8#4819]
When I run `mvn clean test-compile exec:java` I many lines of valid output but halfway through it fails with 
```

FAILED: io.fabric8.kubernetes.client.KubernetesClientException: Pod "console2" is forbidden: Namespace mynamespace does not exist
io.fabric8.kubernetes.client.KubernetesClientException: Pod "console2" is forbidden: Namespace mynamespace does not exist
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.assertResponseCode(BaseOperation.java:493)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:506)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:520)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:208)
	at io.fabric8.kubernetes.api.Example.createPod(Example.java:68)
	at io.fabric8.kubernetes.api.Example.main(Example.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by davsclaus** [comment]
Can you explain a bit more what you are doing. The error indicate a namesapce does not exists `mynamespace`. Have you created such namespace ?

**Comment by hamsal** [comment]
the only thing I did before hand was export the `KUBERNETES_MASTER` variable to point to my api. No I don't think I made such a namespace on my cluster.

**Comment by davsclaus** [comment]
Ah okay you ran the `Example` from the kubernetes-api
