### ISSUE TITLE
Warning when building chaos monkey 'Forbidden!Configured service account doesn't have access. Service account may have been revoked.'

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#4847]
Warnings when building chaos monkey for release..  build doesn't fail so not sure if it's a problem..

```
[WARNING] Could not find gogs service URL: io.fabric8.kubernetes.client.KubernetesClientException: Error accessing: https://kubernetes.default.svc/api/v1/namespaces/release/services/gogs,due to:Forbidden!Configured service account doesn't have access. Service account may have been revoked.
io.fabric8.kubernetes.client.KubernetesClientException: Error accessing: https://kubernetes.default.svc/api/v1/namespaces/release/services/gogs,due to:Forbidden!Configured service account doesn't have access. Service account may have been revoked.
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.assertResponseCode(BaseOperation.java:489)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:506)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:531)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:111)
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURLInCurrentNamespace(KubernetesHelper.java:1303)
	at io.fabric8.maven.AbstractFabric8Mojo.tryDefaultAnnotationEnvVar(AbstractFabric8Mojo.java:422)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:358)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:331)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:308)
	at io.fabric8.maven.JsonMojo.execute(JsonMojo.java:511)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Could not find jenkins service URL: io.fabric8.kubernetes.client.KubernetesClientException: Error accessing: https://kubernetes.default.svc/api/v1/namespaces/release/services/jenkins,due to:Forbidden!Configured service account doesn't have access. Service account may have been revoked.
io.fabric8.kubernetes.client.KubernetesClientException: Error accessing: https://kubernetes.default.svc/api/v1/namespaces/release/services/jenkins,due to:Forbidden!Configured service account doesn't have access. Service account may have been revoked.
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.assertResponseCode(BaseOperation.java:489)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:506)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:531)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:111)
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURLInCurrentNamespace(KubernetesHelper.java:1303)
	at io.fabric8.maven.AbstractFabric8Mojo.tryDefaultAnnotationEnvVar(AbstractFabric8Mojo.java:405)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:358)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:331)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:308)
	at io.fabric8.maven.JsonMojo.execute(JsonMojo.java:511)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Added enviroment annotations:
[INFO]     ReplicationController chaos-monkey replicas: 1, image: docker.io/fabric8/chaos-monkey:2.2.38
[INFO] Template is now:
[INFO]     ReplicationController chaos-monkey replicas: 1, image: docker.io/fabric8/chaos-monkey:2.2.38
[INFO] ```

**Comment by rawlingsj** [comment]
not an issue anynmore
