### ISSUE TITLE
fabric-maven-plugin json goal requires online access to kube which it should not

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4852]
The new 2.2.37 release causes it to go online. See
https://gist.github.com/davsclaus/2e0122ec9f108bb62546

**Comment by davsclaus** [comment]
Okay 2.2.40-SNAPSHOT logs this ugly stacktrace by complets the json goal
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: CDI :: Camel 2.2.39-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cdi-camel-archetype ---
[INFO] Deleting /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target
[INFO]
[INFO] --- fabric8-maven-plugin:2.2.40-SNAPSHOT:json (json) @ cdi-camel-archetype ---
[INFO] Configured with file: /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/classes/kubernetes.json
2015-10-02 11:14:12 INFO  Version:17 - HV000001: Hibernate Validator 5.2.2.Final
[INFO] No environment schemas found for file: io/fabric8/environment/schema.json
[INFO] Generated env mappings: {}
[INFO] Generated port mappings: {}
[INFO] Removed 'version' label from service selector for service `qs-java-camel-cdi`
Generated ports: []
[INFO] Icon URL: https://cdn.rawgit.com/fabric8io/fabric8/master/fabric8-maven-plugin/src/main/resources/icons/camel.svg
[WARNING] Cannot auto-default GIT_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Gogs build URL
[WARNING] Cannot auto-default BUILD_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Jenkins build URL
[WARNING] Could not find jenkins service URL: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:118)
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURLInCurrentNamespace(KubernetesHelper.java:1303)
	at io.fabric8.maven.AbstractFabric8Mojo.tryDefaultAnnotationEnvVar(AbstractFabric8Mojo.java:405)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:358)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:331)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:308)
	at io.fabric8.maven.JsonMojo.execute(JsonMojo.java:511)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: No route to host
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:282)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:140)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:115)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:87)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:517)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:229)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:504)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:531)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:111)
	... 27 more
Caused by: java.net.ConnectException: No route to host
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 39 more
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:465)
	at sun.nio.ch.Net.connect(Net.java:457)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:666)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
	at com.ning.http.client.providers.netty.channel.SslInitializer.connectRequested(SslInitializer.java:48)
	at org.jboss.netty.channel.SimpleChannelDownstreamHandler.handleDownstream(SimpleChannelDownstreamHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.connect(Channels.java:634)
	at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:216)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.connect(NettyRequestSender.java:375)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:281)
	... 35 more
[INFO] Added enviroment annotations:
[INFO]     Service qs-java-camel-cdi selector: {project=cdi-camel-archetype, component=cdi-camel-archetype, container=java, provider=fabric8, group=quickstarts} ports: 1
[INFO]     ReplicationController cdi-camel-archetype replicas: 1, image: docker.io/fabric8/cdi-camel-archetype:2.2.39-SNAPSHOT
[INFO] Template is now:
[INFO]     Service qs-java-camel-cdi selector: {project=cdi-camel-archetype, component=cdi-camel-archetype, container=java, provider=fabric8, group=quickstarts} ports: 1
[INFO]     ReplicationController cdi-camel-archetype replicas: 1, image: docker.io/fabric8/cdi-camel-archetype:2.2.39-SNAPSHOT
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cdi-camel-archetype ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.1:compile (default-compile) @ cdi-camel-archetype ---
[INFO] Compiling 2 source files to /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ cdi-camel-archetype ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.1:testCompile (default-testCompile) @ cdi-camel-archetype ---
[INFO] Compiling 1 source file to /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ cdi-camel-archetype ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ cdi-camel-archetype ---
[INFO] Building jar: /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/cdi-camel-archetype.jar
[INFO]
[INFO] --- maven-dependency-plugin:2.10:build-classpath (add-classpath) @ cdi-camel-archetype ---
[INFO] Wrote classpath file '/Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/classpath'.
[INFO]
[INFO] --- fabric8-maven-plugin:2.2.40-SNAPSHOT:attach (attach) @ cdi-camel-archetype ---
[INFO] Generated Kubernetes JSON resources:
[INFO]   Template cdi-camel-archetype parameters:
[INFO]     Service qs-java-camel-cdi selector: {project=cdi-camel-archetype, component=cdi-camel-archetype, container=java, provider=fabric8, group=quickstarts} ports: 1
[INFO]     ReplicationController cdi-camel-archetype replicas: 1, image: docker.io/fabric8/cdi-camel-archetype:2.2.39-SNAPSHOT
[INFO] Attaching kubernetes json file: /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/classes/kubernetes.json to the build
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ cdi-camel-archetype ---
[INFO] Installing /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/cdi-camel-archetype.jar to /Users/davsclaus/.m2/repository/io/fabric8/archetypes/cdi-camel-archetype/2.2.39-SNAPSHOT/cdi-camel-archetype-2.2.39-SNAPSHOT.jar
[INFO] Installing /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/pom.xml to /Users/davsclaus/.m2/repository/io/fabric8/archetypes/cdi-camel-archetype/2.2.39-SNAPSHOT/cdi-camel-archetype-2.2.39-SNAPSHOT.pom
[INFO] Installing /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/classes/kubernetes.json to /Users/davsclaus/.m2/repository/io/fabric8/archetypes/cdi-camel-archetype/2.2.39-SNAPSHOT/cdi-camel-archetype-2.2.39-SNAPSHOT-kubernetes.json
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.717 s
[INFO] Finished at: 2015-10-02T11:14:18+02:00
[INFO] Final Memory: 62M/627M
[INFO] ------------------------------------------------------------------------
davsclaus:~/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output (master)/$
```

**Comment by davsclaus** [comment]
Looks like this commit did this
https://github.com/fabric8io/fabric8/commit/e94e2d25dac04477fb1e3a6cc77f3744efb08756

**Comment by davsclaus** [comment]
#4800 causes this problem

**Comment by jstrachan** [comment]
the build works - I guess we just have to be a bit quieter in the exception if we can't find jenkins?

**Comment by davsclaus** [comment]
Yes I added some check to detect if its some connection error and silently ignore it, now it shows
```
davsclaus:~/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output (master)/$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: CDI :: Camel 2.2.39-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ cdi-camel-archetype ---
[INFO] Deleting /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target
[INFO]
[INFO] --- fabric8-maven-plugin:2.2.40-SNAPSHOT:json (json) @ cdi-camel-archetype ---
[INFO] Configured with file: /Users/davsclaus/workspace/quickstarts/archetype-itests/target/cdi-camel-archetype-output/target/classes/kubernetes.json
2015-10-02 13:26:07 INFO  Version:17 - HV000001: Hibernate Validator 5.2.2.Final
[INFO] No environment schemas found for file: io/fabric8/environment/schema.json
[INFO] Generated env mappings: {}
[INFO] Generated port mappings: {}
[INFO] Removed 'version' label from service selector for service `qs-java-camel-cdi`
Generated ports: []
[INFO] Icon URL: https://cdn.rawgit.com/fabric8io/fabric8/master/fabric8-maven-plugin/src/main/resources/icons/camel.svg
[WARNING] Cannot auto-default GIT_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Gogs build URL
[WARNING] Cannot auto-default BUILD_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Jenkins build URL
[INFO] Added enviroment annotations:
[INFO]     Service qs-java-camel-cdi selector: {project=cdi-camel-archetype, component=cdi-camel-archetype, container=java, provider=fabric8, group=quickstarts} ports: 1
[INFO]     ReplicationController cdi-camel-archetype replicas: 1, image: docker.io/fabric8/cdi-camel-archetype:2.2.39-SNAPSHOT
[INFO] Template is now:
[INFO]     Service qs-java-camel-cdi selector: {project=cdi-camel-archetype, component=cdi-camel-archetype, container=java, provider=fabric8, group=quickstarts} ports: 1
[INFO]     ReplicationController cdi-camel-archetype replicas: 1, image: docker.io/fabric8/cdi-camel-archetype:2.2.39-SNAPSHOT
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cdi-camel-archetype ---
```

**Comment by davsclaus** [comment]
This is better now
