### ISSUE TITLE
mvn fabric:json - A bit nicer error messages

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4860]
Have vagrant running and deploy the camel-servlet quickstart using: mvn clean install docker:build fabric8:json fabric8:apply

There is no CI/CD setup in the f8 platform. Just a plain vagrant up.

```
[WARNING] Cannot auto-default GIT_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Gogs build URL
[WARNING] Cannot auto-default BUILD_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Jenkins build URL
[WARNING] Could not find jenkins service URL: java.lang.IllegalArgumentException: No kubernetes service could be found for name: jenkins
java.lang.IllegalArgumentException: No kubernetes service could be found for name: jenkins
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURLInCurrentNamespace(KubernetesHelper.java:1306)
	at io.fabric8.maven.AbstractFabric8Mojo.tryDefaultAnnotationEnvVar(AbstractFabric8Mojo.java:405)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:358)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:331)
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:221)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Not adding annotation `fabric8.io/git-commit` to ReplicationController quickstart-war-camel-servlet with value `92dfb5605324b0885ce7d6a1e064df577e55fd88` as there is already an annotation value of `92dfb5605324b0885ce7d6a1e064df577e55fd88`
[WARNING] Not adding annotation `fabric8.io/git-branch` to ReplicationController quickstart-war-camel-servlet with value `master` as there is already an annotation value of `master`
```

**Comment by davsclaus** [comment]
Fixed hy #4874
