### ISSUE TITLE
mvn fabric8:apply failure

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#4872]
this used to work. Now on 2.2.40 I get this
```
[ERROR] Failed to create namespace. io.fabric8.kubernetes.client.KubernetesClientException: namespaces "gogsadmin-james2-staging" already exists. Namespace(apiVersion=v1, kind=Namespace, metadata=ObjectMeta(annotations=null, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels=null, name=gogsadmin-james2-staging, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=null, status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: namespaces "gogsadmin-james2-staging" already exists
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.assertResponseCode(BaseOperation.java:493)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:506)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:520)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:208)
	at io.fabric8.kubernetes.api.Controller.applyNamespace(Controller.java:802)
	at io.fabric8.kubernetes.api.Controller.applyNamespace(Controller.java:788)
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:193)

```

when trying the CanaryStageApproveAndPromote.groovy

**Comment by jstrachan** [comment]
think this was caused by 2 builds running in parallel!

**Comment by davsclaus** [comment]
@jstrachan oh a new dimension to haunt us ;) 

Did you really hit some code that do a 

if not exists namespace
   then create namespace

**Comment by jstrachan** [comment]
yeah - I guess we could check if the create fails double check its not just that some other process created it in the meantime. Though I guess avoiding the parallel builds by default would work around this issue for now
