### ISSUE TITLE
The fabric maven plugin should be less noisy when guess jenkins url

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#4874]
When you just start f8 without jenkins you get

```
[WARNING] Cannot find jenkins service URL: java.lang.IllegalArgumentException: No kubernetes service could be found for name: jenkins
java.lang.IllegalArgumentException: No kubernetes service could be found for name: jenkins
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURLInCurrentNamespace(KubernetesHelper.java:1306)
	at io.fabric8.maven.AbstractFabric8Mojo.tryDefaultAnnotationEnvVar(AbstractFabric8Mojo.java:407)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:359)
	at io.fabric8.maven.AbstractFabric8Mojo.addEnvironmentAnnotations(AbstractFabric8Mojo.java:332)
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:221)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Not adding annotation `fabric8.io/git-commit` to ReplicationController quickstart-war-camel-servlet with value `57bfab9a68f2d5e52b9843b4d801fee802705dfb` as there is already an annotation value of `57bfab9a68f2d5e52b9843b4d801fee802705dfb`
```

**Comment by davsclaus** [comment]
We should detect the IllegalArgumentException and not show the stacktrace

**Comment by davsclaus** [comment]
Its less noisy now

```
[INFO] No environment schemas found for file: io/fabric8/environment/schema.json
[INFO] Generated env mappings: {}
[INFO] Generated port mappings: {http=ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=null, additionalProperties={}), jolokia=ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=null, additionalProperties={})}
[INFO] Removed 'version' label from service selector for service `quickstart-camelservlet`
Generated ports: [ServicePort(name=null, nodePort=null, port=9101, protocol=TCP, targetPort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={})]
[INFO] Icon URL: https://cdn.rawgit.com/fabric8io/fabric8/master/fabric8-maven-plugin/src/main/resources/icons/camel.svg
[WARNING] Cannot auto-default GIT_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Gogs build URL
[WARNING] Cannot auto-default BUILD_URL as there is no environment variable `JENKINS_GOGS_USER` defined so we can't guess the Jenkins build URL
[WARNING] No kubernetes service could be found for name: jenkins
[INFO] Added environment annotations:
[INFO]     Service quickstart-camelservlet selector: {project=quickstart-war-camel-servlet, component=quickstart-war-camel-servlet, container=tomcat, provider=fabric8, group=quickstarts} ports: 9101
[INFO]     ReplicationController quickstart-war-camel-servlet replicas: 1, image: docker.io/fabric8/quickstart-war-camel-servlet:2.2.41-SNAPSHOT
[INFO] Template is now:
[INFO]     Service quickstart-camelservlet selector: {project=quickstart-war-camel-servlet, component=quickstart-war-camel-servlet, container=tomcat, provider=fabric8, group=quickstarts} ports: 9101
[INFO]     ReplicationController quickstart-war-camel-servlet replicas: 1, image: docker.io/fabric8/quickstart-war-camel-servlet:2.2.41-SNAPSHOT
```
