### ISSUE TITLE
Create tests that ensure shrink-wrap works fine.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/fabric8#4889]
The last couple of months I notice that shrink-wrap which is used by fabric8-arquillian breaks quite a lot due to version conflicts. 

We should have a test that takes shrink-wrap for a ride, so that we can catch pull requests that can possibly break shrinkwrap.

**Comment by oscerd** [comment]
Maybe the problem it's related to the last version upgrade?

https://github.com/fabric8io/fabric8/commit/1ff73ff76ade8c5aabff76c0f6d0b284cc608cba

**Comment by iocanel** [comment]
@oscerd not sure. but it doesn't really matter. We should have a test so that we can catch those as early as possible :-)

**Comment by iocanel** [comment]
@oscerd: fwiw, that particular change is NOT responsible for the error I am seeing:

org.jboss.shrinkwrap.resolver.api.Invokable$InvocationException: Unable to load class org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader with class loader sun.misc.Launcher$AppClassLoader@591ce4fe
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.jboss.shrinkwrap.resolver.api.Invokable.loadClass(Invokable.java:64)
        at org.jboss.shrinkwrap.resolver.api.Invokable.<init>(Invokable.java:41)
        at org.jboss.shrinkwrap.resolver.api.ResolverSystemFactory.createFromUserView(ResolverSystemFactory.java:74)
        at org.jboss.shrinkwrap.resolver.api.ResolverSystemFactory.createFromUserView(ResolverSystemFactory.java:53)
        at org.jboss.shrinkwrap.resolver.api.Resolvers.use(Resolvers.java:68)

**Comment by oscerd** [comment]
@iocanel thanks :-)
