### ISSUE TITLE
Forge generates a NPE within Fabric8SetupStep class

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#4903]
````
[Temp]$ devops-edit --chatRoom
***ERROR*** Error while executing 'io.fabric8.forge.devops.setup.Fabric8SetupStep'
java.lang.NullPointerException
	at io.fabric8.forge.devops.setup.Fabric8SetupStep.execute(Fabric8SetupStep.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
```

**Comment by jstrachan** [comment]
workaround is - run devop-edit in a folder that contains a pom.xml. I'll fix and return a better exception
