### ISSUE TITLE
Upgrade deltaspike as its old

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#5035]
we use 1.0.3 and latest is 1.5.0

**Comment by davsclaus** [comment]
Building fabric-cdi fails with, when using deltaspike 1.5.0
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.674 sec <<< FAILURE! - in io.fabric8.cdi.weld.internal.ExtensionInternalTest
io.fabric8.cdi.weld.internal.ExtensionInternalTest  Time elapsed: 2.674 sec  <<< ERROR!
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type WindowContextQuotaHandler with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.apache.deltaspike.core.impl.scope.window.WindowBeanHolder.windowContextQuotaHandler
  at org.apache.deltaspike.core.impl.scope.window.WindowBeanHolder.windowContextQuotaHandler(WindowBeanHolder.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:359)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:281)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:134)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:155)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:518)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:68)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:66)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)


Results :

Tests in error:
  ExtensionInternalTest.io.fabric8.cdi.weld.internal.ExtensionInternalTest » Deployment

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

@iocanel wonder if you fancy one day look at upgrading deltaspike, as its cdi stuff.

**Comment by davsclaus** [comment]
@iocanel or @oscerd wonder if that unit test failure can be fixed so we can get fabric8 updated.

deltaspike 1.5.1 is the latest release.

**Comment by oscerd** [comment]
I'll take a look.

**Comment by iocanel** [comment]
@davsclaus , @oscerd: I've hit this in the past and I had to bake the shrink-wrap generated wars, in ways I won't dare to speak about in public :-)

Maybe 1.5.1 of deltaspike doesn't need all that voodoo and we can even simplify our code.

**Comment by iocanel** [comment]
@iocanel: note to self. Don't be so naive ....

**Comment by iocanel** [comment]
@oscerd: If you don't mind I'll pick it up, since I've quite familiar with the issue.

**Comment by davsclaus** [comment]
yay thanks @iocanel and @oscerd for helping

**Comment by oscerd** [comment]
Perfect :-)

**Comment by rjmveloso** [comment]
I'm still facing this issue, with deltaspike 1.5.1 and even with 1.8.1, running on JBoss EAP 7.0
It seems that the @Specializes beans are being ignored.
Also facing the same for a different dependency:
```
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type LocaleResolver with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.apache.deltaspike.core.impl.message.DefaultMessageContext.localeResolver
```
