### ISSUE TITLE
Build of jenkins job created using CD Pipeline fails - out of memory error with jenkins swarm

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#5071]
```
Started by user anonymous
Fetching changes from the remote Git repository
Checking out Revision b97e430892eb508e3fe640d11fa061c28613fa7d (refs/remotes/origin/master)
Running: Allocate node : Start
Running on jenkins-swarm-client-lupyh-9e5b52d6 in /var/jenkins_home/workspace/gogsadmin-demo
Running: Allocate node : Body : Start
Running: Git
Running: Allocate node : Body : End
Running: Allocate node : End
Running: End of Workflow
java.io.IOException: remote file operation failed: /var/jenkins_home/workspace/gogsadmin-demo at hudson.remoting.Channel@2493dc2f:jenkins-swarm-client-lupyh-9e5b52d6: java.io.IOException: Remote call on jenkins-swarm-client-lupyh-9e5b52d6 failed
	at hudson.FilePath.act(FilePath.java:985)
	at hudson.FilePath.act(FilePath.java:967)
	at hudson.FilePath.mkdirs(FilePath.java:1150)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:695)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1037)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:213)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Remote call on jenkins-swarm-client-lupyh-9e5b52d6 failed
	at hudson.remoting.Channel.call(Channel.java:761)
	at hudson.FilePath.act(FilePath.java:978)
	... 15 more
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at hudson.remoting.AtmostOneThreadExecutor.execute(AtmostOneThreadExecutor.java:88)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at hudson.remoting.JarCacheSupport.resolve(JarCacheSupport.java:59)
	at hudson.remoting.ResourceImageInJar._resolveJarURL(ResourceImageInJar.java:78)
	at hudson.remoting.ResourceImageInJar.resolve(ResourceImageInJar.java:42)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:234)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at hudson.FilePath.getTarEntryLinkFlagField(FilePath.java:2729)
	at hudson.FilePath.<clinit>(FilePath.java:2725)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.getLong(Field.java:611)
	at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1663)
	at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:480)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:468)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:468)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:365)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:602)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:185)
	at hudson.remoting.UserRequest.perform(UserRequest.java:99)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:63)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to jenkins-swarm-client-lupyh-9e5b52d6(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1360)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:753)
	... 16 more
Finished: FAILURE
```

**Comment by cmoulliard** [comment]
Error disappeared after restarting vagrant vm box.

**Comment by jstrachan** [comment]
Wonder if you hit the file descriptor limit for your vagrant process?

On Wednesday, 21 October 2015, Charles Moulliard <notifications@github.com>
wrote:

> Error disappeared after restarting vagrant vm box.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/5071#issuecomment-149967889>.
>


-- 
James
-------
Red Hat

Twitter: @jstrachan
Email: james.strachan@gmail.com
Medium: https://medium.com/@jstrachan/
Blog: http://macstrac.blogspot.com/

fabric8: http:/ <http://fusesource.com/>/fabric8.io/
hawtio: http:/ <http://fusesource.com/>/hawt.io/

Open Source DevOps and Integration

**Comment by rawlingsj** [comment]
We've taken sonarqube out from the cd-pipeline package as this was taking up a lot of resources.  Hopefully that will help avoid this issue.  Shall we close and re-open if it happens again?

**Comment by cmoulliard** [comment]
I prefer that you wait till I make a new test to see if that issue happens again. Last week, everything has blocked during the demo's conference even if the VM Memory was defined to 8Mb of RAM.
