### ISSUE TITLE
Maven: Can't set repository or tag in fabric8.container.name

### ISSUE THREAD

**Issue by maklemenz** [fabric8io/fabric8#5108]
Using this properties:

    <dockerregistry>docker-registry.kube-system:5000</dockerregistry>
    <containername>${dockerregistry}/${project.artifactId}:${project.version}</containername>
    <fabric8.version>2.2.43</fabric8.version>
    <fabric8.container.name>${containername}</fabric8.container.name>

I get the following error:

	[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.43:json (default-cli) on project batch-boot-demo: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.2.43:json failed: Constraint Violations:
	[ERROR] EditableContainer name:"docker-registry.kube-system:5000/batch-boot-demo:0.0.9-SNAPSHOT" must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
	[ERROR] -> [Help 1]
	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.43:json (default-cli) on project batch-boot-demo: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.2.43:json failed: Constraint Violations:
		EditableContainer name:"docker-registry.kube-system:5000/batch-boot-demo:0.0.9-SNAPSHOT" must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
		at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:2.2.43:json failed: Constraint Violations:
		EditableContainer name:"docker-registry.kube-system:5000/batch-boot-demo:0.0.9-SNAPSHOT" must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
		... 19 more
	Caused by: java.lang.IllegalStateException: Constraint Violations:
		EditableContainer name:"docker-registry.kube-system:5000/batch-boot-demo:0.0.9-SNAPSHOT" must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

		at io.fabric8.kubernetes.api.model.ContainerBuilder.validate(ContainerBuilder.java:62)
		at io.fabric8.kubernetes.api.model.ContainerBuilder.build(ContainerBuilder.java:35)
		at io.fabric8.kubernetes.api.model.PodSpecFluent$ContainersNested.and(PodSpecFluent.java:199)
		at io.fabric8.kubernetes.api.model.PodSpecFluent$ContainersNested.endContainer(PodSpecFluent.java:196)
		at io.fabric8.maven.JsonMojo.generateKubernetesJson(JsonMojo.java:822)
		at io.fabric8.maven.JsonMojo.execute(JsonMojo.java:501)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
		... 20 more

**Comment by jimmidyson** [comment]
That is a constraint enforced by Kubernetes. Not much we can do about that I'm afraid. You'll need to set a container name that conforms to that regexp.

**Comment by jimmidyson** [comment]
Just FYI - the container name != image name. Container name is the name of the container in the pod. Image name is the name of the image that will be used to run that container.

**Comment by maklemenz** [comment]
@jimmidyson Thank you, as you guessed I just mixed that up

**Comment by jimmidyson** [comment]
No worries - there's loads of new terminology to learn to begin with but it'll become second nature in no time I'm sure.
