### ISSUE TITLE
[fabric8 forge] pod fails to start: java.net.ConnectException: General SSLEngine problem

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5150]
From the logs I see this error which was also reported on irc by @tdcox yesterday, full stack trace can be found at the bottom.

KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/services/gogs. Cause: java.net.ConnectException: General SSLEngine problem

Workaround suggested by @iocanel 

```
oc get rc fabric8-forge -o=yaml > update-forge.yml
[START ADD TO ENV VARS]
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
[END ADD TO ENV VARS]
oc update -f update-forge.yml

[kill forge pod and let the RC recreate it]
```

Full stack trace..
```
org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:|Exception 0 :|io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/services/gogs. Cause: java.net.ConnectException: General SSLEngine problem|?at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestException(OperationSupport.java:241)|?at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:178)|?at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:168)|?at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:464)|?at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:98)|?at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1256)|?at io.fabric8.cdi.Services.toServiceUrl(Services.java:34)|?at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:49)|?at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:26)|?at io.fabric8.cdi.bean.ProducerBean.create(ProducerBean.java:42)|?at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:842)|?at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)|?at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)|?at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)|?at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)|?at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:180)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:842)|?at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)|?at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)|?at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)|?at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)|?at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:180)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:842)|?at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)|?at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:378)|?at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:389)|?at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)|?at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)|?at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:159)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)|?at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:842)|?at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)|?at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:378)|?at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:389)|?at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)|?at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)|?at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)|?at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)|?at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:159)|?at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)|?at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)|?at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)|?at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:765)|?at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:61)|?at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:85)|?at org.apache.cxf.cdi.JAXRSCdiResourceExtension.load(JAXRSCdiResourceExtension.java:87)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:497)|?at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)|?at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)|?at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:309)|?at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)|?at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:287)|?at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:265)|?at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)|?at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)|?at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)|?at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)|?at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)|?at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)|?at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)|?at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:450)|?at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)|?at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:234)|?at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:61)|?at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)|?at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:327)|?at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1368)|?at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1335)|?at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:735)|?at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)|?at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)|?at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)|?at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)|?at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)|?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)|?at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:453)|?at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)|?at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)|?at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)|?at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)|?at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)|?at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)|?at org.eclipse.jetty.server.Server.start(Server.java:405)|?at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)|?at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)|?at org.eclipse.jetty.server.Server.doStart(Server.java:372)|?at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)|?at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)|?at java.security.AccessController.doPrivileged(Native Method)|?at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)|?at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)|?at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)|?at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)|?at java.lang.reflect.Method.invoke(Method.java:497)|?at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)|?at org.eclipse.jetty.start.Main.start(Main.java:457)|?at org.eclipse.jetty.start.Main.main(Main.java:75)|Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: General SSLEngine problem|?at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)|?at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)|?at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37)|?at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:104)|?at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)|?at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395)|?at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)|?at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1460)|?at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1314)|?at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)|?at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)|?at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)|?at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)|?at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)|?at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)|?at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)|?at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)|?at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)|?at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)|?at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)|?at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)|?at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)|?at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)|?at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)|?at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)|?at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)|?at java.lang.Thread.run(Thread.java:745)|Caused by: java.net.ConnectException: General SSLEngine problem|?at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)|?... 25 more|Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem|?at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)|?at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)|?at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)|?at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)|?at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)|?at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)|?... 18 more|Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem|?at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)|?at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)|?at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)|?at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)|?at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)|?at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)|?at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)|?at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)|?at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)|?at java.security.AccessController.doPrivileged(Native Method)|?at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)|?at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)|?at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)|?... 18 more|Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching kubernetes.default.svc found.|?at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:204)|?at sun.security.util.HostnameChecker.match(HostnameChecker.java:95)|?at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)|?at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)|?at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)|?at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)|?at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1484)|?... 26 more|
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:450)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:234)
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:61)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:327)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1368)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1335)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:735)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:453)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
	at org.eclipse.jetty.start.Main.start(Main.java:457)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
2015-10-30 08:14:42.759:INFO:oejs.ServerConnector:main: Started ServerConnector@367795c7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2015-10-30 08:14:42.759:INFO:oejs.Server:main: Started @11507ms
```

**Comment by jstrachan** [comment]
BTW I just did a `vagrant delete -f; vagrant up` using OpenShift Origin 1.0.7 and didn't see this with the latest release using the image `fabric8/fabric8-forge:2.2.63`.

Mind you the forge doesn't seem to work too well either (editing the Pipeline of a project seems broken); gonna try a new release shortly to see if that fixes it..

**Comment by jstrachan** [comment]
Maybe this is only an issue on non-vagrant? I'll add KUBERNETES_TRUST_CERTIFICATES to forge for the next release to see if that helps

**Comment by jstrachan** [comment]
think this is fixed in the next release now
