### ISSUE TITLE
hubot notifier pod can't be started due to this empty string error - 2.2.67

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#5186]
The hubot-notifier pod can't be started as this error is reported within its log file 

```
2015-11-05 17:54:11 WARN  Bootstrap:386 - WELD-001208: Error when validating jar:file:/maven/hubot-notifier.jar!/META-INF/beans.xml@7 against xsd. cvc-complex-type.2.4.a: Invalid content was found starting with element 'scan'. One of '{"http://java.sun.com/xml/ns/javaee":interceptors, "http://java.sun.com/xml/ns/javaee":decorators, "http://java.sun.com/xml/ns/javaee":alternatives, WC[##other:"http://java.sun.com/xml/ns/javaee"]}' is expected.
12
2015-11-05 17:54:11 INFO  Bootstrap:211 - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
13
2015-11-05 17:54:11 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.message.MessageBundleExtension.detectInterfaces(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
14
2015-11-05 17:54:11 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.interceptor.GlobalInterceptorExtension.promoteInterceptors(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
15
2015-11-05 17:54:11 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension.vetoBeans(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
16
2015-11-05 17:54:11 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] public io.fabric8.cdi.Fabric8Extension.processAnnotatedType(@Observes ProcessAnnotatedType<R>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
17
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
18
INFO: class: org.apache.deltaspike.core.impl.scope.DeltaSpikeContextExtension activated=true
19
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
20
INFO: class: org.apache.deltaspike.core.impl.config.ConfigurationExtension activated=true
21
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
22
INFO: class: org.apache.deltaspike.core.impl.interceptor.GlobalInterceptorExtension activated=true
23
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
24
INFO: class: org.apache.deltaspike.core.impl.exception.control.extension.ExceptionControlExtension activated=true
25
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
26
INFO: class: org.apache.deltaspike.core.impl.message.MessageBundleExtension activated=true
27
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
28
INFO: class: org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension activated=true
29
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
30
INFO: class: org.apache.deltaspike.core.impl.exclude.CustomProjectStageBeanFilter activated=true
31
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
32
INFO: class: org.apache.deltaspike.core.impl.exclude.GlobalAlternative activated=true
33
Nov 05, 2015 5:54:11 PM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
34
INFO: class: org.apache.deltaspike.core.impl.jmx.MBeanExtension activated=true
35
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
36
Exception 0 :
37
java.lang.RuntimeException: Empty String or null supplied as string-default value for property HUBOT_USERNAME
38
	at org.apache.deltaspike.core.api.config.ConfigResolver$PropertyBuilder.withStringDefault(ConfigResolver.java:735)
39
	at org.apache.deltaspike.core.spi.config.BaseConfigPropertyProducer.getPropertyValue(BaseConfigPropertyProducer.java:127)
40
	at org.apache.deltaspike.core.spi.config.BaseConfigPropertyProducer.getStringPropertyValue(BaseConfigPropertyProducer.java:108)
41
	at org.apache.deltaspike.core.impl.config.DefaultConfigPropertyProducer.produceStringConfiguration(DefaultConfigPropertyProducer.java:43)
42
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
43
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
44
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
45
	at java.lang.reflect.Method.invoke(Method.java:606)
46
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
47
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
48
	at org.jboss.weld.injection.producer.ProducerMethodProducer.produce(ProducerMethodProducer.java:99)
49
	at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:161)
50
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:181)
51
	at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
52
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
53
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
54
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)
55
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:842)
56
	at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)
57
	at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)
58
	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)
59
	at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
60
	at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)
61
	at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:180)
62
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)
63
	at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
64
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
65
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
66
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:742)
67
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:842)
68
	at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)
69
	at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)
70
	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)
71
	at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
72
	at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)
73
	at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:180)
74
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)
75
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
76
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
77
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
78
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
79
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
80
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
81
	at io.fabric8.hubot.notifier.KubernetesHubotNotifier$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
82
	at io.fabric8.cdi.eager.EagerCDIExtension.afterDeploymentValidation(EagerCDIExtension.java:42)
83
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
84
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
85
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
86
	at java.lang.reflect.Method.invoke(Method.java:606)
87
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
88
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
89
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:309)
90
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
91
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:287)
92
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:265)
93
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
94
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
95
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
96
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
97
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
98
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
99
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
100
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:450)
101
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
102
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:558)
103
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:44)
104
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:53)
105

106
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
107
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
108
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:450)
109
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
110
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:558)
111
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:44)
112
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:53)
```

**Comment by cmoulliard** [comment]
If I look to the template I see a variable but for the key LETSCHAT_HUBOT_USERNAME

```
[root@vagrant vagrant]# oc describe template chat-letschat
Name:		chat-letschat
Created:	About an hour ago
Labels:		<none>
Description:	Provides [Chat](http://fabric8.io/guide/chat.html) using [Hubot](https://hubot.github.com/) as the bot framework and [Let's Chat](https://github.com/sdelements/lets-chat) as the chat server
Annotations:	fabric8.chat-letschat/iconUrl=https://cdn.rawgit.com/fabric8io/fabric8-devops/master/packages/chat-letschat/src/main/fabric8/icon.png
		fabric8.chat-letschat/summary=Sonatype helps open source projects to set up Maven repositories on https://oss.sonatype.org/
		fabric8.hubot-letschat/iconUrl=https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-letschat/src/main/fabric8/icon.png
		fabric8.hubot-letschat/summary=[Hubot](http://hubot.github.com) chat bot for Lets Chat
		fabric8.hubot-notifier/iconUrl=https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png
		fabric8.hubot-notifier/summary=Watches the OpenShift environment and notifies Hubot of events such as builds completing or failing

Parameters:
    Name:		HUBOT_GRAFANA_API_KEY
    Description:	API key for a particular user
    Required:		false
    Value:		<none>
    Name:		LETSCHAT_HUBOT_PASSWORD
    Description:	The password for the Fabric8 Hubot bot
    Required:		false
    Value:		RedHat$1
    Name:		LETSCHAT_DEFAULT_ROOMS
    Description:	Comma delimited list of rooms for hubot to join on startup
    Required:		false
    Value:		fabric8_default
    Name:		LETSCHAT_HUBOT_USERNAME
    Description:	The username for the Fabric8 Hubot bot
    Required:		false
    Value:		fabric8
    Name:		LETSCHAT_HUBOT_SCRIPTS
    Description:	Coffeescripts for hubot
    Required:		false
    Value:		https://github.com/fabric8io/fabric8-hubot-scripts.git
    Name:		HUBOT_JENKINS_URL
    Description:	The URL for the Jenkins CI server
    Required:		false
    Value:		http://jenkins.default.svc.cluster.local
    Name:		HUBOT_GRAFANA_HOST
    Description:	Host for your Grafana 2.0 install, e.g. 'http://play.grafana.org'
    Required:		false
    Value:		<none>
    Name:		KUBERNETES_DNS_DOMAIN
    Description:	The DNS domain added to the serviceName.namespace.svc. to make the DNS name
    Required:		false
    Value:		cluster.local

Object Labels:	<none>

Objects:
    Service			hubot
    Service			hubot-jenkins-notifier
    Service			letschat
    ReplicationController	hubot-letschat
    ReplicationController	hubot-notifier
    ReplicationController	letschat
```
