### ISSUE TITLE
Can't create a new pipeline project - forge error - vagrant snapshot

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8#5243]
When, after creating a pipeline project successfully and taking a vagrant snapshot, we restart vagrant and would like to create a new pipeline project, we can't as Forge complains about gogs invalid user/password

Within the log of Forge, when the pod is started, I see this error 

````
INFO: WELD-ENV-002003: Weld SE container org.jboss.forge.addon:javaee initialized
129
Preloading commands
130
Loaded 17 commands
131
Preloading archetypes
132
Preloaded archetypes!
133
Now trying to create a new project in: /tmp/startupNewProject4650023551122411016tmp
134
Cloning git repo https://github.com/fabric8io/jenkins-workflow-library.git into directory /tmp/fabric8-forge/jenkinsWorkflows cloneAllBranches: true
135
Status: 200
136
Got entity: ExecutionResult{status=SUCCESS, message='null', output='', err='', detail='null'} io.fabric8.forge.rest.dto.ExecutionResult
137
Created project!
138
Now lets try validate the devops-edit command
139
Nov 16, 2015 2:14:55 PM io.fabric8.forge.devops.setup.Fabric8SetupStep initializeUI
140
INFO: Getting the current project
141
Nov 16, 2015 2:14:55 PM org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator canMoveToNextStep
142
SEVERE: Error while navigating to next step
143
java.lang.IllegalStateException: A project is required in the current context
144
	at org.jboss.forge.addon.projects.ui.AbstractProjectCommand.getSelectedProject(AbstractProjectCommand.java:78)
145
	at io.fabric8.forge.devops.setup.Fabric8SetupStep.initializeUI(Fabric8SetupStep.java:152)
146
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
147
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
148
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
149
	at java.lang.reflect.Method.invoke(Method.java:497)
150
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
151
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
152
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
153
	at io.fabric8.forge.devops.setup.Fabric8SetupStep_$$_javassist_e55d6ad2-54d5-432e-86ee-0f43dbd5f9d3.initializeUI(Fabric8SetupStep_$$_javassist_e55d6ad2-54d5-432e-86ee-0f43dbd5f9d3.java)
154
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
155
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.initialize(WizardCommandControllerImpl.java:115)
156
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.canMoveToNextStep(NoUIWizardControllerDecorator.java:60)
157
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.initialize(NoUIWizardControllerDecorator.java:43)
158
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
159
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
160
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
161
	at java.lang.reflect.Method.invoke(Method.java:497)
162
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:123)
163
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
164
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:96)
165
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_9105755e-5e09-4fb9-a00c-29563a03acf2.initialize(CommandController_$$_javassist_9105755e-5e09-4fb9-a00c-29563a03acf2.java)
166
	at io.fabric8.forge.rest.CommandsResource.createController(CommandsResource.java:484)
167
	at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:265)
168
	at io.fabric8.forge.rest.main.ForgeInitialiser.preloadCommands(ForgeInitialiser.java:135)
169
	at io.fabric8.forge.rest.main.ForgeRestApplication.getSingletons(ForgeRestApplication.java:51)
170
	at org.apache.cxf.cdi.JAXRSCdiResourceExtension.load(JAXRSCdiResourceExtension.java:95)
171
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
172
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
173
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
174
	at java.lang.reflect.Method.invoke(Method.java:497)
175
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
176
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
177
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:309)
178
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
179
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:287)
180
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:265)
181
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
182
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
183
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
184
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
185
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
186
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
187
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
188
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:450)
189
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
190
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:234)
191
	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:61)
192
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
193
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
194
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
195
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:327)
196
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1368)
197
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1335)
198
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:735)
199
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
200
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:511)
201
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
202
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
203
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
204
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
205
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
206
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
207
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:453)
208
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
209
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
210
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
211
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
212
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
213
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
214
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
215
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
216
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
217
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
218
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
219
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
220
	at org.eclipse.jetty.server.Server.start(Server.java:405)
221
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
222
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
223
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
224
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
225
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
226
	at java.security.AccessController.doPrivileged(Native Method)
227
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
228
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
229
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
230
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
231
	at java.lang.reflect.Method.invoke(Method.java:497)
232
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
233
	at org.eclipse.jetty.start.Main.start(Main.java:457)
234
	at org.eclipse.jetty.start.Main.main(Main.java:75)
```

**Comment by jstrachan** [comment]
are you sure thats just not a startup exception? Does the fabric8-forge pod startup correctly & is it ready? if so can you create a project?

**Comment by cmoulliard** [comment]
Pod is started. I have also recreate new Forge pod and this error is always there.

**Comment by jstrachan** [comment]
is it just a startup exception or does it happen if you try to create a project?

**Comment by cmoulliard** [comment]
This error is probably not relevant but this one yes which is reported from the browser console when I try to authenticate the user

````
GET https://vagrant.f8:8443/api/v1/proxy/namespaces/create/services/fabric8-for…ogsAuth=Basic%20Z29nc2FkbWluOlJlZEhhdCQx&_gogsEmail=gogsadmin%40fabric8.io 404 (Not Found)
three.js:26805 [Forge] failed to load https://vagrant.f8:8443/api/v1/proxy/namespaces/create/services/fabric8-for…ogsAuth=Basic%20Z29nc2FkbWluOlJlZEhhdCQx&_gogsEmail=gogsadmin%40fabric8.io. status: 404 data: [object Object]
```

**Comment by jstrachan** [comment]
any chance of the full URL (from the Network tab)

**Comment by cmoulliard** [comment]
Here is the full url `https://vagrant.f8:8443/api/v1/proxy/namespaces/create/services/fabric8-forge/api/forge/repos?_gogsAuth=Basic%20Z29nc2FkbWluOlJlZEhhdCQx&_gogsEmail=gogsadmin%40fabric8.io``
and the response returned

```
{
kind: "Status",
apiVersion: "v1",
metadata: { },
status: "Failure",
message: "User "system:anonymous" cannot "proxy" "services/api" with name "fabric8-forge" in project "create"",
reason: "Forbidden",
details: {
name: "fabric8-forge",
kind: "services/api"
},
code: 403
}
```

**Comment by jstrachan** [comment]
thanks, can you still create projects?

**Comment by jimmidyson** [comment]
That URL is totally wrong - the namespace is being called `create` for some reason.

**Comment by cmoulliard** [comment]
I can't create new projects as I can't be authenticated

**Comment by jstrachan** [comment]
which namespace / workspace are you inside when you try to authenticate?

**Comment by cmoulliard** [comment]
Default -> https://www.dropbox.com/s/4wgk4fbajatcb89/Screenshot%202015-11-16%2015.58.00.png?dl=0

**Comment by jstrachan** [comment]
which version are you running? Looks like as @jimmidyson said, its using the wrong URL

**Comment by cmoulliard** [comment]
Version used is : 2.2.67

**Comment by gashcrumb** [comment]
Wonder, even if you're taking a snapshot of the vagrant VM, if the gogs pod gets restarted your account is gonna be gone I think.  Did you verify that you could log into gogs with the same username and password before trying the create project wizard?

**Comment by cmoulliard** [comment]
I can log to gogs server

**Comment by cmoulliard** [comment]
Been able to find a workaround. (= reopen the fabric8 console by clicking on the link from openshift console).

Do we keep this ticket open for the forge error reported ?

**Comment by jstrachan** [comment]
so effectively a browser reload fixed it? would be nice to find out why the console got borked

**Comment by cmoulliard** [comment]
Not a bowser reload. Close the window and click on the fabric8 console link (fabric8.vagrant.io) from openshift console

**Comment by jstrachan** [comment]
I think we can close this one now
