### ISSUE TITLE
arquillian integration tests failing (fabric8 CD pipeline fails)

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5367]
Not sure yet if this is the same issue we had last week @iocanel 

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.example.KubernetesIntegrationKT
[32mInitializing Session:35e1a6d6-383c-4ebc-bab8-26a1f84a8516[m
[32mUsing Kubernetes at: https://kubernetes.default.svc/[m
[32mCreating kubernetes resources inside namespace: my-thing-testing[m
if you use OpenShift then type this switch namespaces:     oc project my-thing-testing
if you use kubernetes then type this to switch namespaces: kubectl namespace my-thing-testing
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.327 sec <<< FAILURE! - in org.example.KubernetesIntegrationKT
org.example.KubernetesIntegrationKT  Time elapsed: 2.326 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/codehaus/plexus/util/xml/pull/EntityReplacementMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:523)
	at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:557)
	at org.apache.maven.settings.io.DefaultSettingsReader.read(DefaultSettingsReader.java:92)
	at org.apache.maven.settings.building.DefaultSettingsBuilder.readSettings(DefaultSettingsBuilder.java:169)
	at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:95)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenSettingsBuilder.buildSettings(MavenSettingsBuilder.java:166)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenSettingsBuilder.buildDefaultSettings(MavenSettingsBuilder.java:117)
	at org.jboss.shrinkwrap.resolver.impl.maven.SettingsManager.getSettings(SettingsManager.java:75)
	at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenWorkingSessionImpl.getSettings(ConfigurableMavenWorkingSessionImpl.java:129)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.getSettingsDefinedProfiles(MavenWorkingSessionImpl.java:471)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.loadPomFromFile(MavenWorkingSessionImpl.java:155)
	at org.jboss.shrinkwrap.resolver.impl.maven.task.LoadPomTask.execute(LoadPomTask.java:84)
	at org.jboss.shrinkwrap.resolver.impl.maven.PomlessResolveStageBaseImpl.loadPomFromFile(PomlessResolveStageBaseImpl.java:93)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenResolverSystemBaseImpl.loadPomFromFile(MavenResolverSystemBaseImpl.java:154)
	at io.fabric8.arquillian.kubernetes.DependencyResolver.resolve(DependencyResolver.java:54)
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)

[33mShutdown hook cleaning up the integration test![m

Results :

Tests in error: 
  JUnit4Provider.invoke:128->executeTestSet:153->executeWithRerun:173->execute:283 » NoClassDefFound

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default-cli) @ my-thing ---
[INFO] Failsafe report directory: /home/jenkins/workspace/my-thing/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.155 s
[INFO] Finished at: 2015-11-30T21:55:04+00:00
[INFO] Final Memory: 19M/321M
[INFO] ------------------------------------------------------------------------
```

**Comment by rawlingsj** [comment]
We still have conflicts with the fabric8 and camel BOMs on the ipaas-quickstarts project.  

Here's the dependency tree after the fabric8 wizard generates a project using the camel CDI ipaas-quickstart..

__NOTE__ the different versions of __plexus-utils__

__[INFO] \- org.codehaus.plexus:plexus-utils:jar:1.5.8:test__
```
➜  my-thing git:(master) ✗ mvn dependency:tree | grep -C 10 plexus-utils
[INFO] |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:test
[INFO] |  +- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:test
[INFO] |  |  \- org.sonatype.plexus:plexus-cipher:jar:1.4:test
[INFO] |  +- org.apache.maven.wagon:wagon-provider-api:jar:2.6:test
[INFO] |  +- org.apache.maven.wagon:wagon-file:jar:2.6:test
[INFO] |  |  \- commons-lang:commons-lang:jar:2.6:test
[INFO] |  \- org.apache.maven.wagon:wagon-http-lightweight:jar:2.6:test
[INFO] |     \- org.apache.maven.wagon:wagon-http-shared:jar:2.6:test
[INFO] |        +- org.jsoup:jsoup:jar:1.7.2:test
[INFO] |        \- commons-io:commons-io:jar:2.4:test
[INFO] \- org.codehaus.plexus:plexus-utils:jar:1.5.8:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.074 s
[INFO] Finished at: 2015-11-30T23:10:44+00:00
[INFO] Final Memory: 24M/437M
[INFO] ------------------------------------------------------------------------
```
I'm sure its not the answer but for info if I remove the camel bom from the generated project and push it back to gogs the integration test passes, the new dependency tree looks like...

__[INFO] \- org.codehaus.plexus:plexus-utils:jar:3.0.22:test__
```
➜  my-thing git:(master) ✗ mvn dependency:tree | grep -C 10 plexus-utils
[INFO] |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:test
[INFO] |  +- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:test
[INFO] |  |  \- org.sonatype.plexus:plexus-cipher:jar:1.4:test
[INFO] |  +- org.apache.maven.wagon:wagon-provider-api:jar:2.6:test
[INFO] |  +- org.apache.maven.wagon:wagon-file:jar:2.6:test
[INFO] |  |  \- commons-lang:commons-lang:jar:2.6:test
[INFO] |  \- org.apache.maven.wagon:wagon-http-lightweight:jar:2.6:test
[INFO] |     \- org.apache.maven.wagon:wagon-http-shared:jar:2.6:test
[INFO] |        +- org.jsoup:jsoup:jar:1.7.2:test
[INFO] |        \- commons-io:commons-io:jar:2.4:test
[INFO] \- org.codehaus.plexus:plexus-utils:jar:3.0.22:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

It seems having two BOMs that bring in conflicting dependency versions causes the fabric8 CD feature to fail.

**Comment by rawlingsj** [comment]
@davsclaus @iocanel I doubt there's an easy answer to this but would you mind if we spend a bit of time in the morning trying to figure it out as at the moment the CD feature doesnt work end to end without manual hacks.

**Comment by davsclaus** [comment]
Can you post the full tree? Wonder what dependency those that plexus-utils comes from

**Comment by davsclaus** [comment]
And maven as a JAR library is a terrible mess. Sadly there is no simple maven like library that don't bring in a ton of weird dependencies in all sorts of versions that breaks. 

I wonder what ant ivy uses to resolve dependencies? Maybe its fucked too and have to use the maven?

**Comment by davsclaus** [comment]
Yeah the camel bom is using an old plexus-utils version, sadly its in our bom but its only used for some camel maven tooling. We should likely move it out of the bom, so it does not affect others.

**Comment by davsclaus** [comment]
I logged a ticket on Camel side
https://issues.apache.org/jira/browse/CAMEL-9379

**Comment by davsclaus** [comment]
As a workaround on the quickstart we can add/override those versions so they use same version of plexus-utils as fabric8 does.

From Camel 2.17 onwards we should be good as those are removed from the camel BOM

**Comment by iocanel** [comment]
We can do what we've already done for the redhat branch:

"use the fabric8 platform bom before any other bom"


On Tue, Dec 1, 2015 at 9:38 AM, Claus Ibsen <notifications@github.com>
wrote:

> As a workaround on the quickstart we can add/override those versions so
> they use same version of plexus-utils as fabric8 does.
>
> From Camel 2.17 onwards we should be good as those are removed from the
> camel BOM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8/issues/5367#issuecomment-160884849>.
>



-- 
*Ioannis Canellos*

*Blog: http://iocanel.blogspot.com <http://iocanel.blogspot.com/>*
*Twitter: iocanel*

**Comment by iocanel** [comment]
the platform bom contains just fabric8 artifacts and very few other dependencies like weld arquillian etc.

this bom also includes a couple of other dependencies, which are not obvious and have huge impact in case of version mismatch like plexus-utils.

**Comment by davsclaus** [comment]
yeah if the fabric8 bom keeps being short and only about the fabric8 dependencies. Also maybe we should shade the test JAR for integration testing so it include all the maven stuff out of the box, so there is no dependency hell. Also we avoid causing side effects for end users by defining those dependencies. Then the fabric8 bom is only about fabric8 JARs (and maybe jolokia).

**Comment by davsclaus** [comment]
@iocanel can you try those latest changes you did on redhat on the master branch? then we have fabric8 bom first and its similar.

And btw the comment on the redhat branch is wrong, something about fabric8 bom before fabric8 bom. You may want to fix that too.

**Comment by iocanel** [comment]
@davsclaus : I am on it ;-)

**Comment by rawlingsj** [comment]
ah fantastic, thanks @iocanel and @davsclaus.  I'll kick off a release now.
