### ISSUE TITLE
Arquillian fails when building the cdi-camel quickstart in the latest release

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#5369]
```
[camel1] Running shell script

+ mvn org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test -Dfabric8.environment=Testing -Dit.test=*KT -DfailIfNoTests=false org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify -Ddocker.registry=172.30.1.249:80

[INFO] Scanning for projects...

[INFO] Downloading: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/plugins/maven-failsafe-plugin/2.18.1/maven-failsafe-plugin-2.18.1.pom

[INFO] Downloaded: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/plugins/maven-failsafe-plugin/2.18.1/maven-failsafe-plugin-2.18.1.pom (9 KB at 26.0 KB/sec)

[INFO] Downloading: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/plugins/maven-failsafe-plugin/2.18.1/maven-failsafe-plugin-2.18.1.jar

[INFO] Downloaded: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/plugins/maven-failsafe-plugin/2.18.1/maven-failsafe-plugin-2.18.1.jar (81 KB at 471.9 KB/sec)

[INFO]

[INFO] ------------------------------------------------------------------------

[INFO] Building Fabric8 :: Quickstarts :: CDI :: Camel 1.0.1

[INFO] ------------------------------------------------------------------------

[INFO]

[INFO] --- maven-failsafe-plugin:2.18.1:integration-test (default-cli) @ camel1 ---

[INFO] Failsafe report directory: /home/jenkins/workspace/camel1/target/failsafe-reports

[INFO] Downloading: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/surefire/surefire-junit4/2.18.1/surefire-junit4-2.18.1.pom

[INFO] Downloaded: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/surefire/surefire-junit4/2.18.1/surefire-junit4-2.18.1.pom (3 KB at 27.7 KB/sec)

[INFO] Downloading: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/surefire/surefire-providers/2.18.1/surefire-providers-2.18.1.pom

[INFO] Downloaded: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/surefire/surefire-providers/2.18.1/surefire-providers-2.18.1.pom (3 KB at 27.9 KB/sec)

[INFO] Downloading: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/surefire/surefire-junit4/2.18.1/surefire-junit4-2.18.1.jar

[INFO] Downloaded: http://nexus.vagrant.f8:80/content/groups/public/org/apache/maven/surefire/surefire-junit4/2.18.1/surefire-junit4-2.18.1.jar (67 KB at 481.1 KB/sec)

-------------------------------------------------------

T E S T S

-------------------------------------------------------

Running org.example.KubernetesIntegrationKT

[32mInitializing Session:ac229e26-912e-4b29-8e08-e15482d857b3[m

[32mUsing Kubernetes at: https://kubernetes.default.svc/[m

[32mCreating kubernetes resources inside namespace: camel1-testing[m

if you use OpenShift then type this switch namespaces: oc project camel1-testing

if you use kubernetes then type this to switch namespaces: kubectl namespace camel1-testing

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.437 sec <<< FAILURE! - in org.example.KubernetesIntegrationKT

org.example.KubernetesIntegrationKT Time elapsed: 1.436 sec <<< ERROR!

java.lang.NoClassDefFoundError: org/codehaus/plexus/util/xml/pull/EntityReplacementMap

at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:523)

at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:557)

at org.apache.maven.settings.io.DefaultSettingsReader.read(DefaultSettingsReader.java:92)

at org.apache.maven.settings.building.DefaultSettingsBuilder.readSettings(DefaultSettingsBuilder.java:169)

at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:95)

at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenSettingsBuilder.buildSettings(MavenSettingsBuilder.java:166)

at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenSettingsBuilder.buildDefaultSettings(MavenSettingsBuilder.java:117)

at org.jboss.shrinkwrap.resolver.impl.maven.SettingsManager.getSettings(SettingsManager.java:75)

at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenWorkingSessionImpl.getSettings(ConfigurableMavenWorkingSessionImpl.java:129)

at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.getSettingsDefinedProfiles(MavenWorkingSessionImpl.java:471)

at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.loadPomFromFile(MavenWorkingSessionImpl.java:155)

at org.jboss.shrinkwrap.resolver.impl.maven.task.LoadPomTask.execute(LoadPomTask.java:84)

at org.jboss.shrinkwrap.resolver.impl.maven.PomlessResolveStageBaseImpl.loadPomFromFile(PomlessResolveStageBaseImpl.java:93)

at org.jboss.shrinkwrap.resolver.impl.maven.MavenResolverSystemBaseImpl.loadPomFromFile(MavenResolverSystemBaseImpl.java:154)

at io.fabric8.arquillian.kubernetes.DependencyResolver.resolve(DependencyResolver.java:54)

at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:111)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)

at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)

at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)

at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)

at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)

at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)

at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:56)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)

at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)

at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)

at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)

at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)

at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)

at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)

at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)

at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)

at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)

at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)

at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)

at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)

[33mShutdown hook cleaning up the integration test![m

Results :

Tests in error:

JUnit4Provider.invoke:128->executeTestSet:153->executeWithRerun:173->execute:283 » NoClassDefFound
```

**Comment by iocanel** [comment]
Let's just monitor #5367, which is also assigned to me :-)
