### ISSUE TITLE
Gerrit pod failing 'Cannot access /home/gerrit/site'

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5443]
Running Gerrit 2.2.86 on Origin - non vagrant setup.

This seems different to the SSH key issue that was recently fixed..

```
[root@demo-master rawlingsj]# docker logs 2e39449947a0
/root/.ssh/id_rsa
id files identical
/root/.ssh/id_rsa
/root/.ssh/id_rsa.pub
id files identical
/root/.ssh/id_rsa.pub
>> .gerrit-configured doesn't exist. We will start gerrit to generate it
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.io.FileNotFoundException: Cannot access /home/gerrit/site
  at com.google.gerrit.server.config.SitePaths.<init>(SitePaths.java:67)
  at com.google.gerrit.server.config.GerritServerConfigModule$1.configure(GerritServerConfigModule.java:51)
  while locating com.google.gerrit.server.config.SitePaths

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at com.google.gerrit.server.config.GerritServerConfigModule.getSecureStoreFromGerritConfig(GerritServerConfigModule.java:55)
	at com.google.gerrit.server.config.GerritServerConfigModule.getSecureStoreClassName(GerritServerConfigModule.java:39)
	at com.google.gerrit.pgm.util.SiteProgram.getConfiguredSecureStoreClass(SiteProgram.java:186)
	at com.google.gerrit.pgm.init.BaseInit.createSiteInit(BaseInit.java:214)
	at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:106)
	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:166)
	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:93)
	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:50)
	at Main.main(Main.java:25)
Caused by: java.io.FileNotFoundException: Cannot access /home/gerrit/site
	at com.google.gerrit.server.config.SitePaths.<init>(SitePaths.java:106)
	at com.google.gerrit.server.config.SitePaths$$FastClassByGuice$$199e0369.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:108)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	... 15 more
```

**Comment by rawlingsj** [comment]
I'm not sure if we should be using mounted host volumes should we?

i.e. persistence needs to be sorted out but writing to a host mount wont work anyway when running in a cluster or do we need to have extra steps to configure storage when using gerrit outside of the vagrant image?
I'm wondering if we cant just remove the host mount for gerrit so it behave like our other apps until we sort out persistence?

I'll probably just remove the host mounted volume config from gerrit for the next release so at least the pod starts again and we can work out the best / right way to handle storage. 

@jimmidyson @cmoulliard @jstrachan does that sound ok to you?

**Comment by rawlingsj** [comment]
Fixed in a previous release.
