### ISSUE TITLE
jube report nullpointerexception

### ISSUE THREAD

**Issue by liuhaif** [fabric8io/fabric8#5484]
jube version: 2.2.0
jdk version: 1.8.0.64_60
**Use command: 
mvn fabric8:apply -Dfabric8.namespace=fabric8 -Dfabric8.domain=tong.com

**the server report error:
2015-12-18 16:12:53,175 [qtp546718765-25] WARN  HttpParser                     - Illegal character 0x16 in state=START for buffer HeapByteBuffer@10c2e7ba[p=1,l=200,c=16384,r=199]={\x16<<<\x03\x03\x00\xC3\x01\x00\x00\xBf\x03\x03Vs\xC0\x05\x1a\xC3\xAa...\x03\x04\x01\x03\x03\x03\x01\x02\x03\x02\x01\x02\x02\x01\x01>>>xt/javascript, */...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2015-12-18 16:12:53,177 [qtp546718765-25] WARN  HttpParser                     - badMessage: 400 Illegal character 0x16 for HttpChannelOverHttp@2739a4ce{r=0,c=false,a=IDLE,uri=-}
2015-12-18 16:12:59,499 [Timer-0        ] INFO  NodeHelper                     - Added new container: quickstart-java-simple-mainclass-1-quickstart-java-simple-mainclass
2015-12-18 16:12:59,501 [Timer-0        ] INFO  ApiMasterKubernetesModel       - Attempting to create pod on host: http://localhost:8585/
Updating pod io.fabric8.kubernetes.api.model.Pod@4144bdce[apiVersion=v1,kind=Pod,metadata=io.fabric8.kubernetes.api.model.ObjectMeta@60925a28[annotations=<null>,creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={container=java, provider=fabric8, group=quickstarts},name=quickstart-java-simple-mainclass-1,namespace=<null>,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],spec=io.fabric8.kubernetes.api.model.PodSpec@676a8eb7[activeDeadlineSeconds=<null>,containers=[io.fabric8.kubernetes.api.model.Container@d9f5940[args=[],command=[],env=[io.fabric8.kubernetes.api.model.EnvVar@69513ff0[name=KUBERNETES_NAMESPACE,value=<null>,valueFrom=io.fabric8.kubernetes.api.model.EnvVarSource@1b606be8[fieldRef=io.fabric8.kubernetes.api.model.ObjectFieldSelector@28cc4105[apiVersion=<null>,fieldPath=metadata.namespace,additionalProperties={}],additionalProperties={}],additionalProperties={}]],image=fabric8/quickstart-java-simple-mainclass:2.2.0,imagePullPolicy=<null>,lifecycle=<null>,livenessProbe=<null>,name=quickstart-java-simple-mainclass-1-quickstart-java-simple-mainclass,ports=[io.fabric8.kubernetes.api.model.ContainerPort@5f6e5805[containerPort=8778,hostIP=<null>,hostPort=<null>,name=jolokia,protocol=<null>,additionalProperties={}]],readinessProbe=<null>,resources=<null>,securityContext=<null>,terminationMessagePath=<null>,volumeMounts=[],workingDir=<null>,additionalProperties={}]],dnsPolicy=<null>,host=<null>,hostNetwork=<null>,imagePullSecrets=[],nodeSelector=<null>,restartPolicy=<null>,serviceAccount=<null>,terminationGracePeriodSeconds=<null>,volumes=[],additionalProperties={}],status=io.fabric8.kubernetes.api.model.PodStatus@3f2042a7[conditions=[],containerStatuses=[io.fabric8.kubernetes.api.model.ContainerStatus@27074180[containerID=quickstart-java-simple-mainclass-1-quickstart-java-simple-mainclass,image=<null>,imageID=<null>,lastState=<null>,name=<null>,ready=<null>,restartCount=<null>,state=<null>,additionalProperties={}]],hostIP=localhost,message=<null>,phase=<null>,podIP=<null>,startTime=<null>,additionalProperties={}],additionalProperties={}]
2015-12-18 16:12:59,628 [pool-7-thread-3] ERROR ApiMasterService               - Failed to create container quickstart-java-simple-mainclass-1. java.lang.NullPointerException
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:464)[:1.8.0_60]
        at io.fabric8.kubernetes.api.KubernetesHelper.getCurrentContainers(KubernetesHelper.java:966)[kubernetes-api-2.2.0.jar:2.2.0]
        at io.fabric8.jube.local.NodeHelper.createMissingContainers(NodeHelper.java:189)[node-2.2.0.jar:2.2.0]
        at io.fabric8.jube.apimaster.ApiMasterService$2$1.run(ApiMasterService.java:551)[node-2.2.0.jar:2.2.0]
        at io.fabric8.jube.local.NodeHelper.excludeFromProcessMonitor(NodeHelper.java:626)[node-2.2.0.jar:2.2.0]
        at io.fabric8.jube.apimaster.ApiMasterService$2.run(ApiMasterService.java:558)[node-2.2.0.jar:2.2.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_60]

**client error:
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: Java :: Simple main class 2.2.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- fabric8-maven-plugin:2.2.0:apply (default-cli) @ quickstart-java-simple-mainclass ---
[INFO] Using kubernetes at: http://localhost:8585 in namespace fabric8
[INFO] Kubernetes JSON: D:\~.bin\ipaas-quickstarts-project-2.2.0\quickstarts\java\simple-mainclass\target\classes\kubernetes.json
十二月 18, 2015 4:15:45 下午 org.apache.cxf.jaxrs.utils.JAXRSUtils logMessageHandlerProblem
严重: No message body reader has been found for class io.fabric8.openshift.api.model.RouteList, ContentType: */*
[WARNING] Could not load routes; we maybe are not connected to an OpenShift environment? javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
        at io.fabric8.kubernetes.api.KubernetesClient.handle404ByReturningNull(KubernetesClient.java:1644)
        at io.fabric8.kubernetes.api.KubernetesClient.getRoutes(KubernetesClient.java:754)
        at io.fabric8.maven.ApplyMojo.createRoutes(ApplyMojo.java:284)
        at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:220)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: javax.ws.rs.client.ResponseProcessingException: No message body reader has been found for class io.fabric8.openshift.api.model.RouteList, ContentType: */*
        at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:433)
        at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:384)
        at org.apache.cxf.jaxrs.client.AbstractClient.readBody(AbstractClient.java:500)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:744)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
        at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
        at com.sun.proxy.$Proxy53.getRoutes(Unknown Source)
        at io.fabric8.kubernetes.api.KubernetesClient$9.call(KubernetesClient.java:757)
        at io.fabric8.kubernetes.api.KubernetesClient$9.call(KubernetesClient.java:754)
        at io.fabric8.kubernetes.api.KubernetesClient.handle404ByReturningNull(KubernetesClient.java:1636)
        ... 25 more
[INFO] Deleting ReplicationController: quickstart-java-simple-mainclass namespace: fabric8
[INFO] Creating a replicationController from kubernetes.json namespace fabric8 name quickstart-java-simple-mainclass
[ERROR] Failed to create replicationController from kubernetes.json. java.lang.NullPointerException. io.fabric8.kubernetes.api.model.ReplicationController@3724b43e[apiVersion=v1,kind=ReplicationController,metadata=io.fabric8.kubernetes.api.model.ObjectMeta@77eb5790[annotations={},creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={container=java, provider=fabric8, group=quickstarts},name=quickstart-java-simple-mainclass,namespace=fabric8,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],spec=io.fabric8.kubernetes.api.model.ReplicationControllerSpec@68e7c8c3[replicas=1,selector={container=java, provider=fabric8, group=quickstarts},template=io.fabric8.kubernetes.api.model.PodTemplateSpec@319c3a25[metadata=io.fabric8.kubernetes.api.model.ObjectMeta@238bfd6c[annotations={},creationTimestamp=<null>,deletionTimestamp=<null>,generateName=<null>,labels={container=java, provider=fabric8, group=quickstarts},name=<null>,namespace=<null>,resourceVersion=<null>,selfLink=<null>,uid=<null>,additionalProperties={}],spec=io.fabric8.kubernetes.api.model.PodSpec@ef1695a[activeDeadlineSeconds=<null>,containers=[io.fabric8.kubernetes.api.model.Container@58860997[args=[],command=[],env=[io.fabric8.kubernetes.api.model.EnvVar@81b5db0[name=KUBERNETES_NAMESPACE,value=<null>,valueFrom=io.fabric8.kubernetes.api.model.EnvVarSource@7487b142[fieldRef=io.fabric8.kubernetes.api.model.ObjectFieldSelector@7139bd31[apiVersion=<null>,fieldPath=metadata.namespace,additionalProperties={}],additionalProperties={}],additionalProperties={}]],image=fabric8/quickstart-java-simple-mainclass:2.2.0,imagePullPolicy=<null>,lifecycle=<null>,livenessProbe=<null>,name=quickstart-java-simple-mainclass,ports=[io.fabric8.kubernetes.api.model.ContainerPort@199bc830[containerPort=8778,hostIP=<null>,hostPort=<null>,name=jolokia,protocol=<null>,additionalProperties={}]],readinessProbe=<null>,resources=<null>,securityContext=io.fabric8.kubernetes.api.model.SecurityContext@4b3fe06e[capabilities=<null>,privileged=<null>,runAsUser=<null>,seLinuxOptions=<null>,additionalProperties={}],terminationMessagePath=<null>,volumeMounts=[],workingDir=<null>,additionalProperties={}]],dnsPolicy=<null>,host=<null>,hostNetwork=<null>,imagePullSecrets=[],nodeSelector={},restartPolicy=<null>,serviceAccount=<null>,terminationGracePeriodSeconds=<null>,volumes=[],additionalProperties={}],additionalProperties={}],templateRef=<null>,additionalProperties={}],status=<null>,additionalProperties={}]
java.lang.NullPointerException
        at io.fabric8.kubernetes.api.KubernetesHelper.toJson(KubernetesHelper.java:361)
        at io.fabric8.kubernetes.api.Controller.logGeneratedEntity(Controller.java:355)
        at io.fabric8.kubernetes.api.Controller.doCreateReplicationController(Controller.java:660)
        at io.fabric8.kubernetes.api.Controller.applyReplicationController(Controller.java:622)
        at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:234)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Thanks!

**Comment by liuhaif** [comment]
move to jube
