### ISSUE TITLE
fabric8 release failing on fabric8-forge

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5611]
Not sure if this is really a timeout issue as I think vertx is a new quickstart so sounds suspect.  I'll try a single release of forge now to be sure but raising issue anyhow..

 Error transferring file: Connection timed out from http://172.30.56.155:80/content/groups/public/io/fabric8/archetypes/vertx-simplest-archetype/2.2.93/vertx-simplest-archetype-2.2.93.jar

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 412.436 sec <<< FAILURE! - in io.fabric8.forge.systest.PopulateMavenRepositoryTest
testPopulateMavenRepo(io.fabric8.forge.systest.PopulateMavenRepositoryTest)  Time elapsed: 412.292 sec  <<< ERROR!
org.jboss.forge.furnace.manager.maven.MavenOperationException_$$_javassist_06c7823d-d23c-4ce7-8a0c-9981f9894ad9: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.fabric8.archetypes:vertx-simplest-archetype:jar:2.2.93 from/to nexus (http://172.30.56.155:80/content/groups/public): Error transferring file: Connection timed out from http://172.30.56.155:80/content/groups/public/io/fabric8/archetypes/vertx-simplest-archetype/2.2.93/vertx-simplest-archetype-2.2.93.jar
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1147)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:131)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveArtifact(MavenDependencyResolver.java:192)
	at sun.reflect.GeneratedMethodAccessor423.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver_$$_javassist_9076fd57-3c47-4727-bfad-2ac79fae938f.resolveArtifact(MavenDependencyResolver_$$_javassist_9076fd57-3c47-4727-bfad-2ac79fae938f.java)
	at org.jboss.forge.addon.maven.projects.archetype.ui.ArchetypeCatalogSelectionWizardStep.execute(ArchetypeCatalogSelectionWizardStep.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.maven.projects.archetype.ui.ArchetypeCatalogSelectionWizardStep_$$_javassist_6f768bba-f881-46c6-9f0d-af6433e15855.execute(ArchetypeCatalogSelectionWizardStep_$$_javassist_6f768bba-f881-46c6-9f0d-af6433e15855.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:162)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:152)
	at sun.reflect.GeneratedMethodAccessor749.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:123)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:96)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_339c149d-d283-414b-b58a-1cdfc9b7c482.execute(CommandController_$$_javassist_339c149d-d283-414b-b58a-1cdfc9b7c482.java)
	at io.fabric8.forge.systest.ProjectGenerator.createProject(ProjectGenerator.java:154)
	at io.fabric8.forge.systest.PopulateMavenRepositoryTest.createProjects(PopulateMavenRepositoryTest.java:81)

Weld SE container org.jboss.forge.addon:configuration shut down by shutdown hook
Weld SE container org.jboss.forge.addon:bean-validation shut down by shutdown hook
Weld SE container org.jboss.forge.addon:convert shut down by shutdown hook
Weld SE container org.jboss.forge.addon:shell shut down by shutdown hook
Weld SE container org.jboss.forge.addon:parser-java shut down by shutdown hook
Weld SE container io.fabric8.forge:devops shut down by shutdown hook
Weld SE container io.fabric8.forge:camel shut down by shutdown hook

Results :

Tests in error: 
  PopulateMavenRepositoryTest.testPopulateMavenRepo:60->createProjects:81 ? MavenOperationException_$$_javassist_06c7823d-d23c-4ce7-8a0c-9981f9894ad9

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by rawlingsj** [comment]
Worked when running again. Closing.
