### ISSUE TITLE
Using the nodejs sample, I get some issue at the jenkins level : No signature of method: io.fabric8.kubernetes.workflow.Kubernetes.image() 

### ISSUE THREAD

**Issue by jmlambert78** [fabric8io/fabric8#5668]
the workflow file is containing : k**ubernetes.image**().withName(clusterImageName).build().fromPath(".")
I used as well James project node-example ant this occurs too;
JMarc

Entering stage canary release
Proceeding
[Workflow] fileExists
[Workflow] } //node
[Workflow] Allocate node : End
[Workflow] End of Workflow
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: io.fabric8.kubernetes.workflow.Kubernetes.image() is applicable for argument types: () values: []
Possible solutions: isCase(java.lang.Object), wait(), any(), wait(long), use([Ljava.lang.Object;), is(java.lang.Object)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at groovy.lang.GroovyObject$invokeMethod$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:75)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:68)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at com.cloudbees.groovy.cps.sandbox.

**Comment by jmlambert78** [comment]
With the last version of the forge, it seems to work better for this point. But I open a ticket on the push that does not work.
