### ISSUE TITLE
amq not starting: ClassNotFoundException: org.easymock.IAnswer

### ISSUE THREAD

**Issue by rparree** [fabric8io/fabric8#5787]
I am trying to run `fabric8mq` with with the `amqbroker` using the `amq` app (also tried them separately) . Inside the `amqbroker` pod i find the following exception:

```
WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.interceptor.GlobalInterceptorExtension.promoteInterceptors(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.WeldJUnitRunner because of underlying class loading error: Type org.junit.runners.BlockJUnit4ClassRunner not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.deltaspike.DeltaspikeTestBase because of underlying class loading error: Type org.jboss.shrinkwrap.api.asset.Asset not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.internal.endpoints.EnpointsInternalTest because of underlying class loading error: Type org.junit.rules.ExpectedException not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.ClientProducer$1 because of underlying class loading error: Type org.easymock.IAnswer not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.nonamespace.NoNamespaceTest because of underlying class loading error: Type org.junit.rules.ExpectedException not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.internal.ExtensionInternalTest because of underlying class loading error: Type org.jboss.shrinkwrap.api.spec.WebArchive not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.external.ExtensionExternalTest because of underlying class loading error: Type org.jboss.shrinkwrap.api.spec.WebArchive not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.internal.brokenfactory.BrokenFactoryInternalTest because of underlying class loading error: Type org.junit.rules.ExpectedException not found.  If this is unexpected, enable DEBUG logging to see the full error.
WELD-000119: Not generating any bean definitions from io.fabric8.cdi.weld.ClientProducer because of underlying class loading error: Type org.easymock.IAnswer not found.  If this is unexpected, enable DEBUG logging to see the full error.
org.jboss.weld.exceptions.DeploymentException: WELD-000123: Error loading io.fabric8.cdi.weld.ClientProducer defined in <class>io.fabric8.cdi.weld.ClientProducer</class> in jar:file:/deployments/lib/fabric8-cdi-2.2.95-tests.jar!/META-INF/beans.xml@21
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:269)
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:256)
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:572)
        at java.util.AbstractList$Itr.next(AbstractList.java:358)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:378)
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder.createModuleEnablement(GlobalEnablementBuilder.java:233)
        at org.jboss.weld.bootstrap.BeanDeployment.createEnablement(BeanDeployment.java:219)
        at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:377)
        at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:76)
        at org.jboss.weld.environment.se.Weld.initialize(Weld.java:146)
        at io.fabric8.amq.Main.main(Main.java:31)
Caused by: java.lang.NoClassDefFoundError: org/easymock/IAnswer
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getDeclaredConstructors(Class.java:2020)
        at org.jboss.weld.environment.deployment.WeldResourceLoader.classForName(WeldResourceLoader.java:52)
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:267)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: org.easymock.IAnswer
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 16 more
Failed to Start AMQ_Broker
org.jboss.weld.exceptions.DeploymentException: WELD-000123: Error loading io.fabric8.cdi.weld.ClientProducer defined in <class>io.fabric8.cdi.weld.ClientProducer</class> in jar:file:/deployments/lib/fabric8-cdi-2.2.95-tests.jar!/META-INF/beans.xml@21
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:269)[weld-core-2.2.5.Final.jar:2014-09-15 07:54]
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:256)[weld-core-2.2.5.Final.jar:2014-09-15 07:54]
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:572)[guava-15.0.jar:]
        at java.util.AbstractList$Itr.next(AbstractList.java:358)[:1.8.0_51]
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)[:1.8.0_51]
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:378)[guava-15.0.jar:]
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder.createModuleEnablement(GlobalEnablementBuilder.java:233)[weld-core-2.2.5.Final.jar:2014-09-15 07:54]
        at org.jboss.weld.bootstrap.BeanDeployment.createEnablement(BeanDeployment.java:219)[weld-core-2.2.5.Final.jar:2014-09-15 07:54]
        at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:377)[weld-core-2.2.5.Final.jar:2014-09-15 07:54]
        at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:76)[weld-core-2.2.5.Final.jar:2014-09-15 07:54]
        at org.jboss.weld.environment.se.Weld.initialize(Weld.java:146)[weld-se-2.2.5.Final.jar:2014-09-15 07:54]
        at io.fabric8.amq.Main.main(Main.java:31)[amqbroker-2.2.93.jar:]

```

**Comment by rparree** [comment]
The (my?) problem seem to be the inclusion of the following dependency of `amqbroker` [pom.xml](https://github.com/fabric8io/fabric8-ipaas/blob/3b35ed8178c38b174e6d6dafab9c1299d1659724/amqbroker/pom.xml#L91)

```
<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-cdi</artifactId>
  <scope>test</scope>
  <type>test-jar</type>
</dependency>
```

This dependency is then included by the `hawt-app` plugin (`target/hawt-app/lib/fabric8-cdi-2.2.95-tests.jar`) even though its scope is `test`. At runtime weld finds the `fabric8-cdi-2.2.95-tests.jar!/META-INF/beans.xml` which fails on classloading of test scoped dependencies ()

Am i the only one having this problem? It can be tested on a standalone machine:

```
docker run -it --rm  fabric8/amqbroker:2.2.93
```

**Comment by jimmidyson** [comment]
You're not the only one - it was reported in https://github.com/fabric8io/ipaas-quickstarts/issues/1157#issuecomment-190808031 & the same conclusion was reached. It looks like a bug in hawt-app maven plugin - fix discussed in that thread too.

We'll try to get a fix out ASAP.

**Comment by rparree** [comment]
tx...i removing the dependency and pushed  the docker  image. That worked for me. i will check out that comment.
