### ISSUE TITLE
[springboot-camel quickstart] IllegalArgumentException: Invalid source 'io.fabric8.quickstarts.camel'

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5817]
springboot-camel quickstart fails to start after archetype is used from the fabric8 console new app wizard
```
2016-03-09 13:25:53.961 ERROR 1 --- [ main] o.s.boot.SpringApplication : Application startup failed
java.lang.IllegalArgumentException: Invalid source 'io.fabric8.quickstarts.camel'
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:221) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:142) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:125) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
at org.springframework.boot.SpringApplication.load(SpringApplication.java:694) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:343) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
at org.apache.camel.spring.boot.FatJarRouter.main(FatJarRouter.java:26) [camel-spring-boot-2.16.2.jar!/:2.16.2]
at org.example.MyCamelRoute.main(MyCamelRoute.java:29) [my-new-springbapp-1.0.1.jar!/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [my-new-springbapp-1.0.1.jar!/:na]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid source 'io.fabric8.quickstarts.camel'
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:221)
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:142)
at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:125)
at org.springframework.boot.SpringApplication.load(SpringApplication.java:694)
at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:343)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
at org.apache.camel.spring.boot.FatJarRouter.main(FatJarRouter.java:26)
at org.example.MyCamelRoute.main(MyCamelRoute.java:29)
... 6 more
```

**Comment by davsclaus** [comment]
Are you using a snapshot of the spring-boot/camel-spring example or from a release?

I can run it locally from snapshot, and trying on f8 now.

**Comment by davsclaus** [comment]
It works for me on f8 also
```
davsclaus:~/workspace/fabric8-installer/vagrant/openshift (master)/$ oc logs -f springboot-camel-gf2u2
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://172.17.0.4:8778/jolokia/

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.0.RELEASE)

2016-03-10 07:44:46.983  INFO 1 --- [           main] o.apache.camel.spring.boot.FatJarRouter  : Starting FatJarRouter v2.16.2 on springboot-camel-gf2u2 with PID 1 (started by jboss in /app)
2016-03-10 07:44:46.994  INFO 1 --- [           main] o.apache.camel.spring.boot.FatJarRouter  : No profiles are active
2016-03-10 07:44:47.143  INFO 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@448ea93c: startup date [Thu Mar 10 07:44:47 UTC 2016]; root of context hierarchy
2016-03-10 07:44:48.613  INFO 1 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-03-10 07:44:48.745  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.apache.camel.spring.boot.CamelAutoConfiguration' of type [class org.apache.camel.spring.boot.CamelAutoConfiguration$$EnhancerBySpringCGLIB$$26abcfe9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-03-10 07:44:49.293  INFO 1 --- [           main] o.a.c.i.converter.DefaultTypeConverter   : Loaded 183 type converters
2016-03-10 07:44:49.745  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-03-10 07:44:49.801  INFO 1 --- [           main] o.a.camel.spring.SpringCamelContext      : Apache Camel 2.16.2 (CamelContext: MyCamel) is starting
2016-03-10 07:44:49.801  INFO 1 --- [           main] o.a.c.m.ManagedManagementStrategy        : JMX is enabled
2016-03-10 07:44:50.010  INFO 1 --- [           main] o.a.c.i.DefaultRuntimeEndpointRegistry   : Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
2016-03-10 07:44:50.370  INFO 1 --- [           main] o.a.camel.spring.SpringCamelContext      : AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
2016-03-10 07:44:50.370  INFO 1 --- [           main] o.a.camel.spring.SpringCamelContext      : StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2016-03-10 07:44:50.424  INFO 1 --- [           main] o.a.camel.spring.SpringCamelContext      : Route: route1 started and consuming from: Endpoint[timer://foo?period=5000]
2016-03-10 07:44:50.426  INFO 1 --- [           main] o.a.camel.spring.SpringCamelContext      : Total 1 routes, of which 1 is started.
2016-03-10 07:44:50.432  INFO 1 --- [           main] o.a.camel.spring.SpringCamelContext      : Apache Camel 2.16.2 (CamelContext: MyCamel) started in 0.626 seconds
2016-03-10 07:44:50.439  INFO 1 --- [           main] o.apache.camel.spring.boot.FatJarRouter  : Started FatJarRouter in 4.115 seconds (JVM running for 5.068)
2016-03-10 07:44:51.441  INFO 1 --- [0 - timer://foo] route1                                   : >>> Hello World
```
