### ISSUE TITLE
release failing on fabric8-forge Failed to start addon [org.jboss.forge.addon:maven,3.0.1.Final] with classloader [ModuleClassLoader for Module "org.jboss.forge.addon.maven:3.0.1.Final_d62b1aea-6949-4966-8367-c1d754a7a573"

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5891]
Not sure yet if this is the correct error that's causing the release to fail but here's the stacktrace and link to the Jenkins log 

http://jenkins.cd.origin.fabric8.io/job/multi-project-fabric8/branch/pipeline-devops+forge/3/console

Its worth noting this is on the new fabric8 CD environment and the first multi project release I've tried with the new scripts but the error doesn't suggest its connected to the pipeline - I could be totally wrong mind.
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.fabric8.forge.systest.PopulateMavenRepositoryTest
Mar 31, 2016 10:56:35 PM org.jboss.forge.furnace.impl.FurnaceImpl start
INFO: Furnace [2.23.4.Final] starting.
Mar 31, 2016 10:56:37 PM org.jboss.forge.furnace.impl.addons.AddonRunnable run
SEVERE: Failed to start addon [org.jboss.forge.addon:maven,3.0.1.Final] with classloader [ModuleClassLoader for Module "org.jboss.forge.addon.maven:3.0.1.Final_d62b1aea-6949-4966-8367-c1d754a7a573" from AddonModuleLoader]
org.jboss.forge.furnace.exception.ContainerException: No services of type [org.jboss.forge.addon.configuration.Configuration] could be found in any started addons.
	at org.jboss.forge.furnace.impl.addons.ImportedImpl.get(ImportedImpl.java:79)
	at org.jboss.forge.addon.maven.archetype.ArchetypeCatalogFactoryRegistryImpl.getArchetypeConfiguration(ArchetypeCatalogFactoryRegistryImpl.java:40)
	at org.jboss.forge.addon.maven.archetype.ArchetypeCatalogFactoryRegistryImpl.handleThisPostStartup(ArchetypeCatalogFactoryRegistryImpl.java:51)
	at org.jboss.forge.furnace.container.simple.AbstractEventListener.handleEvent(AbstractEventListener.java:34)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.maven.archetype.ArchetypeCatalogFactoryRegistryImpl_$$_javassist_ffda8e2f-d44f-4e41-b3b4-c4c2ba809a5e.handleEvent(ArchetypeCatalogFactoryRegistryImpl_$$_javassist_ffda8e2f-d44f-4e41-b3b4-c4c2ba809a5e.java)
	at org.jboss.forge.furnace.container.simple.events.SimpleEventManagerImpl.fireEvent(SimpleEventManagerImpl.java:41)
	at org.jboss.forge.furnace.container.simple.lifecycle.SimpleAddonLifecycleProvider.postStartup(SimpleAddonLifecycleProvider.java:76)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable.firePostStartup(AddonRunnable.java:142)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable.access$400(AddonRunnable.java:38)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:96)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:86)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.impl.addons.AddonRunnable.run(AddonRunnable.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.064 sec <<< FAILURE! - in io.fabric8.forge.systest.PopulateMavenRepositoryTest
testPopulateMavenRepo(io.fabric8.forge.systest.PopulateMavenRepositoryTest)  Time elapsed: 1.946 sec  <<< ERROR!
org.jboss.forge.furnace.exception.ContainerException_$$_javassist_610eb38f-af97-442b-9520-ab7ec6a03860: No services of type [org.jboss.forge.addon.ui.controller.CommandControllerFactory] could be found in any started addons.
	at org.jboss.forge.furnace.impl.addons.ImportedImpl.get(ImportedImpl.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.furnace.services.Imported_$$_javassist_aae16ff0-c933-4590-a33f-c1e79f89d1a8.get(Imported_$$_javassist_aae16ff0-c933-4590-a33f-c1e79f89d1a8.java)
	at io.fabric8.forge.systest.ProjectGenerator.<init>(ProjectGenerator.java:78)
	at io.fabric8.forge.systest.PopulateMavenRepositoryTest.createProjects(PopulateMavenRepositoryTest.java:75)


Results :

Tests in error: 
  PopulateMavenRepositoryTest.testPopulateMavenRepo:61->createProjects:75 ? ContainerException_$$_javassist_610eb38f-af97-442b-9520-ab7ec6a03860

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Fabric8 :: Forge Parent ............................ SUCCESS [  7.670 s]
[INFO] Fabric8 :: Forge Addons ............................ SUCCESS [  1.085 s]
[INFO] Fabric8 :: Forge Addons :: Utils ................... SUCCESS [ 12.782 s]
[INFO] Fabric8 :: Forge Addons :: Camel Util .............. SUCCESS [ 20.486 s]
[INFO] Fabric8 :: Forge Addons :: Camel ................... SUCCESS [ 13.309 s]
[INFO] Fabric8 :: Forge Addons :: Camel Commands .......... SUCCESS [  3.570 s]
[INFO] Fabric8 :: Forge Addons :: Kubernetes .............. SUCCESS [  5.702 s]
[INFO] Fabric8 :: Forge Addons :: DevOps .................. SUCCESS [  8.762 s]
[INFO] Fabric8 :: Camel Maven Plugin ...................... SUCCESS [ 11.299 s]
[INFO] Fabric8 :: Forge :: Core ........................... SUCCESS [  5.281 s]
[INFO] Fabric8 :: Forge :: Web ............................ SUCCESS [  2.765 s]
[INFO] Fabric8 :: Forge ................................... FAILURE [ 11.522 s]
[INFO] Fabric8 :: Forge :: Packages ....................... SKIPPED
[INFO] Fabric8 :: Forge :: Packages :: Continuous Delivery Pipeline SKIPPED
[INFO] Fabric8 :: Forge :: Packages :: Distro ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:45 min
[INFO] Finished at: 2016-03-31T22:56:37+00:00
[INFO] Final Memory: 114M/703M
[INFO] ------------------------------------------------------------------------
```

**Comment by rawlingsj** [comment]
This must be down to the new CD process as fabric8-devops and fabric8-forge (which is finishing now) seem to release individually just fine.
