### ISSUE TITLE
Creating tar from path: ..java.io.IOException: This archives contains unclosed entries.

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#5986]
This error is when building a nodejs app using kubernetes-workflow build image..
```
[Pipeline] buildImage

Creating tar from path: ..java.io.IOException: This archives contains unclosed entries.
at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:225)
at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:241)
at io.fabric8.kubernetes.workflow.BuildImageStepExecution$DockerImageArchiver.close(BuildImageStepExecution.java:331)
at hudson.FilePath$1.invoke(FilePath.java:455)
at hudson.FilePath$1.invoke(FilePath.java:449)
at hudson.FilePath.act(FilePath.java:990)
at hudson.FilePath.act(FilePath.java:968)
at hudson.FilePath.archive(FilePath.java:449)
at hudson.FilePath.archive(FilePath.java:465)
at io.fabric8.kubernetes.workflow.BuildImageStepExecution$CreateTarTask.call(BuildImageStepExecution.java:187)
at io.fabric8.kubernetes.workflow.BuildImageStepExecution$CreateTarTask.call(BuildImageStepExecution.java:174)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

@iocanel does this mean anything to you?  
@rhuss I noticed there's a [similar error](https://github.com/fabric8io/docker-maven-plugin/issues/171) reported recently wth d-m-p, so I wondered if there's any light you can shed on this problem?

**Comment by rhuss** [comment]
Could it be that the tar achive tries to include itself as part of the archive ?

**Comment by rawlingsj** [comment]
Not sure.. @iocanel?

**Comment by rawlingsj** [comment]
I just tried on the fabric8 origin VM and it worked.  

I'll try on our openstack kubernetes cluster.

**Comment by byouloh** [comment]
I have tried it several times on my kubernetes cluster, but I can see the same error till now. Is the sample nodejs app working correctly on fabric8?
