### ISSUE TITLE
Creating tar from path: ..java.io.IOException: This archives contains unclosed entries.

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6010]
After upgrading to the Jenkins 2.0 base image and updating a bunch of plugins [with this commit](https://github.com/fabric8io/jenkins-docker/commit/dc4dfd3e729ad63a0d603cdc5f2c37f007cc7dd8) I've started getting errors during the pipeline, I'm testing a nodejs project and not sure yet why I didn't notice when testing last week.

```
Creating tar from path: ..java.io.IOException: This archives contains unclosed entries.
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:225)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:241)
	at io.fabric8.kubernetes.workflow.BuildImageStepExecution$DockerImageArchiver.close(BuildImageStepExecution.java:331)
	at hudson.FilePath$1.invoke(FilePath.java:455)
	at hudson.FilePath$1.invoke(FilePath.java:449)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at hudson.FilePath.archive(FilePath.java:449)
	at hudson.FilePath.archive(FilePath.java:465)
	at io.fabric8.kubernetes.workflow.BuildImageStepExecution$CreateTarTask.call(BuildImageStepExecution.java:187)
	at io.fabric8.kubernetes.workflow.BuildImageStepExecution$CreateTarTask.call(BuildImageStepExecution.java:174)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by novakg** [comment]
Have you found any  solution to this?
