### ISSUE TITLE
gitcollector fails to start on kubernetes

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6078]
Getting the following in the gitcollector logs...

```
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://10.112.0.4:8778/jolokia/
2016-06-14 17:50:13.303:INFO:ifasjoejs.Server:jetty-8.y.z-SNAPSHOT
2016-06-14 17:50:13.362:INFO:ifasjoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9779
2016-06-14 17:50:13 INFO  Version:153 - WELD-000900: 2.3.4 (Final)
Jun 14, 2016 5:50:13 PM org.apache.deltaspike.core.util.ProjectStageProducer initProjectStage
INFO: Computed the following DeltaSpike ProjectStage: Production
2016-06-14 17:50:13 WARN  Bootstrap:386 - WELD-001208: Error when validating jar:file:/maven/collector-utils-2.2.202.jar!/META-INF/beans.xml@5 against xsd. cvc-complex-type.3.2.2: Attribute 'version' is not allowed to appear in element 'beans'.
2016-06-14 17:50:13 WARN  Bootstrap:386 - WELD-001208: Error when validating jar:file:/maven/collector-utils-2.2.202.jar!/META-INF/beans.xml@7 against xsd. cvc-complex-type.2.4.a: Invalid content was found starting with element 'scan'. One of '{"http://java.sun.com/xml/ns/javaee":interceptors, "http://java.sun.com/xml/ns/javaee":decorators, "http://java.sun.com/xml/ns/javaee":alternatives, WC[##other:"http://java.sun.com/xml/ns/javaee"]}' is expected.
2016-06-14 17:50:13 WARN  Bootstrap:386 - WELD-001208: Error when validating jar:file:/maven/git-collector.jar!/META-INF/beans.xml@5 against xsd. cvc-complex-type.3.2.2: Attribute 'version' is not allowed to appear in element 'beans'.
2016-06-14 17:50:13 WARN  Bootstrap:386 - WELD-001208: Error when validating jar:file:/maven/git-collector.jar!/META-INF/beans.xml@7 against xsd. cvc-complex-type.2.4.a: Invalid content was found starting with element 'scan'. One of '{"http://java.sun.com/xml/ns/javaee":interceptors, "http://java.sun.com/xml/ns/javaee":decorators, "http://java.sun.com/xml/ns/javaee":alternatives, WC[##other:"http://java.sun.com/xml/ns/javaee"]}' is expected.
2016-06-14 17:50:13 INFO  Bootstrap:209 - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2016-06-14 17:50:14 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.message.MessageBundleExtension.detectInterfaces(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-06-14 17:50:14 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.interceptor.GlobalInterceptorExtension.promoteInterceptors(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-06-14 17:50:14 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] public io.fabric8.cdi.Fabric8Extension.processAnnotatedType(@Observes ProcessAnnotatedType<R>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-06-14 17:50:14 INFO  Event:87 - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension.vetoBeans(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2016-06-14 17:50:16 ERROR WatchConnectionManager$1:140 - Exec Failure: HTTP:200. Message:OK
java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
io.fabric8.kubernetes.client.KubernetesClientException: OK
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:142)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:100)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:449)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:585)
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:44)
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:53)
2016-06-14 17:50:17 ERROR WatchConnectionManager$1:140 - Exec Failure: HTTP:200. Message:OK
java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-06-14 17:50:18 ERROR WatchConnectionManager$1:140 - Exec Failure: HTTP:200. Message:OK
java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rawlingsj** [comment]
This is a smaller snip of the exception.. 
```
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
io.fabric8.kubernetes.client.KubernetesClientException: OK
```
