### ISSUE TITLE
Can't create quickstart app

### ISSUE THREAD

**Issue by AaoGITKarein** [fabric8io/fabric8#6131]
Hi, 

I am trying to create quick start app (First app) as demonstrated in several Videos for CI and CD, I am receiving following error:

Found Elasticsearch server, sending:{"timestamp":"2016-07-05T06:47:34.304+0000","build_number":6,"app":"my-cool-first-project","build_result":"FAILURE","start_time":"2016-07-05T06:47:34.309+0000","duration":0,"env_vars":{"BUILD_DISPLAY_NAME":"#6","BUILD_ID":"6","BUILD_NUMBER":"6","BUILD_TAG":"jenkins-my-cool-first-project-6","CLASSPATH":"","HUDSON_HOME":"/var/jenkins_home","HUDSON_SERVER_COOKIE":"317a5bee30207125","JENKINS_HOME":"/var/jenkins_home","JENKINS_SERVER_COOKIE":"317a5bee30207125","JOB_NAME":"my-cool-first-project"},"build_url":"job/my-cool-first-project/6/","causes":[{"short_description":"Started by user anonymous","user_name":"anonymous"}]}
Event created
io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/images/example/my-cool-first-project:1.0.6/tag?tag=1.0.6&force=false&repo=172.30.99.107:80/example/my-cool-first-project. Status:404. Message: Not Found. Body: could not find image: no such id: example/my-cool-first-project:1.0.6

	at io.fabric8.docker.client.impl.OperationSupport.requestFailure(OperationSupport.java:255)
	at io.fabric8.docker.client.impl.OperationSupport.assertResponseCodes(OperationSupport.java:239)
	at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:191)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:88)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:33)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:50)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:41)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to 530bd67e23d0(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:41)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:28)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:137)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:298)
	at io.fabric8.kubernetes.pipeline.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:297)
	at mavenCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/mavenCanaryRelease.groovy:22)
	at WorkflowScript.run(WorkflowScript:46)
	at io.fabric8.kubernetes.pipeline.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:123)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor298.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor301.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)
	at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

**Could you please help me out on this ?**

**Comment by rawlingsj** [comment]
Someone mentioned this last Friday, I think it's a bug introduced in the latest release. I'll take a look straight away.

**Comment by AaoGITKarein** [comment]
Thanks @rawlingsj for your quick response.

Looking forward for a fix.

**Comment by rawlingsj** [comment]
@AaoGITKarein I just need to run some more tests but this will be fixed in the next release, hopefully at some point today.  I'll also add a workaround here once it's tested as you should be able to pick up the fix before waiting for the release.

**Comment by AaoGITKarein** [comment]
Thanks @rawlingsj

**Comment by AaoGITKarein** [comment]
Hi @rawlingsj 

Didn't get it what you are suggesting, It would be great if you can please share a screenshot or example.

**Comment by rawlingsj** [comment]
@AaoGITKarein I'm just doing some testing so should have a workaround for you shortly

**Comment by AaoGITKarein** [comment]
@rawlingsj ok. Thanks, Waiting for it, as stuck on it from last two days :)

**Comment by rawlingsj** [comment]
you can pick up my fix by editing the jenkins replication controller env vars and point to my pipeline library until the release tomorrow.

kubernetes
```
kubectl edit rc jenkins
```
openshift
```
oc edit rc jenkins
```

edit the line and change
```
        - name: JENKINS_WORKFLOW_GIT_REPOSITORY
          value: https://github.com/fabric8io/jenkins-pipeline-library.git
```
to 
```
        - name: JENKINS_WORKFLOW_GIT_REPOSITORY
          value: https://github.com/rawlings/jenkins-pipeline-library.git
```
then delete the jenkins pod and it will be recreated with the fix

__Note__: if you're using a cluster, i.e. more than one node then you will run into another error which has also now been fixed but you'll need to wait for the release scheduled tomorrow.

https://github.com/fabric8io/fabric8/issues/5923

To skip the integration test stage then you can comment out the stage in the Jenkinsfile if you navigate to the Source tab on the left menu bar.

**Comment by rawlingsj** [comment]
I tested the above fix using the camel integration new project wizard

**Comment by abouchama** [comment]
It works like a breeze ;-) Thanks @rawlingsj

**Comment by rawlingsj** [comment]
Yay! Thanks for confirming @abouchama

**Comment by AaoGITKarein** [comment]
@rawlingsj , Testing it now, Will update you shortly.

**Comment by abouchama** [comment]
@AaoGITKarein, I have gotten the same error as you with another archetyoeArtifactId.

I have deleted the Integration Stage from Jenkinsfile, and after the commit, a new build will triggered and it works after as expected.

**Comment by AaoGITKarein** [comment]
Hi @abouchama 

Sorry but I am not getting which Jenkinsfile you are suggesting, I am not able to find it anywhere.

What I have done is, 

1. Cloned repo as https://github.com/AaoGITKarein/jenkins-pipeline-library.git
2. Removed "Integration test" from https://github.com/AaoGITKarein/jenkins-pipeline-library/blob/master/workflows/maven/CanaryReleaseStageAndApprovePromote/Jenkinsfile 
3. Committed
4. oc edit rc Jenkins 
5. Modified JENKINS_WORKFLOW_GIT_REPOSITORY to https://github.com/AaoGITKarein/jenkins-pipeline-library.git
6. Deleted jenkins pod
7. Created project/app using "camel integration"
It is still going for T E S T S and failing...

Kindly suggest if I am doing something wrong.

**Comment by rawlingsj** [comment]
@AaoGITKarein ah yeah you had the right source tab but my guess is the Jenkinsfile wasn't copied into the project git repo.  There's a check box when you create the project and select the pipeline, this ought to be checked by default really.

If you create a new project and select that check box to copy the Jenkinsfile you can comment out the Integration test stage in you project source.

FWIW we did a new release last night so that integration test issue should be fixed so you might want to update to the latest version rather than messing around commenting out stages.

**Comment by AaoGITKarein** [comment]
Hi @rawlingsj 

"copy pipeline" checkbox is not default, I had to do it and then modify Jenkinsfile and had to commit it - This resolved my issue, deployed quickstart project with camel integration. Thank you so much for helping out.

To start with the latest version what would be the steps ? Is there any way to patch it up with existing or I have to start it from scratch ?

**Comment by rawlingsj** [comment]
Having an upgrade command in gofabric8 is on our todo list but it's not there yet unfortunately. 

I usually delete the fabric8 replication controllers (+ templates in on openshift) and run `gofabric8 deploy` again, this pulls in the latest release.

Just note we are still waiting for the release to finish, it's taking a little longer than usual.  I'll comment in this issue once it's finished and ready to be used.

__kubernetes__
```
kubectl delete all -l provider=fabric8
```
__openshift__
```
oc delete all -l provider=fabric8
oc delete templates --all
```

**Comment by AaoGITKarein** [comment]
Thanks for the update @rawlingsj .

Will wait for you comment on final release till then I will continue by commenting integrations tests.

**Comment by rawlingsj** [comment]
Ok great, sounds like a plan.

**Comment by AaoGITKarein** [comment]
@rawlingsj :)

**Comment by AaoGITKarein** [comment]
@rawlingsj (y)

**Comment by rawlingsj** [comment]
this is fixed now and available with the latest release

**Comment by rawlingsj** [comment]
this is fixed now and available with the latest release
