### ISSUE TITLE
Can't launch ManageIQ in Fabric8

### ISSUE THREAD

**Issue by jameslabocki** [fabric8io/fabric8#6140]
I am unable to access ManageIQ after launching it via Fabric8 running on the CDK on OSX. When I launch the application the pod says it is running, but when I browse to _https://manageiq.sample-project.openshift.10.1.2.2.xip.io/_ it says:

```
Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting.
```

It is running the following image:

`Image: manageiq/manageiq:latest
`

When I try to attach the container it just hangs and never returns.

```
[vagrant@rhel-cdk ~]$ docker ps |grep -i manage
9abd29bf2efc        manageiq/manageiq:latest                                                                                          "/usr/sbin/init"         3 minutes ago       Up 2 minutes                            k8smanageiq.9d3271be_manageiq-gwljt_sample-project_02eba234-438f-11e6-8102-525400825485_ad2a073d

[vagrant@rhel-cdk ~]$ sudo docker attach 9abd29bf2efcea1fef4c6ed12c08cb049bfeb98a1dd965203d5882f8b7f97172 
```

This is followed what appears to be a new manageiq container being started each time I do this.

```
[vagrant@rhel-cdk ~]$ docker ps -a |grep -i manage
f2d9674a0f9a        manageiq/manageiq:latest                                                                                          "/usr/sbin/init"         16 seconds ago      Up 13 seconds                                      k8s_manageiq.9d3271be_manageiq-gwljt_sample-project_02eba234-438f-11e6-8102-525400825485_19dccc14
9abd29bf2efc        manageiq/manageiq:latest                                                                                          "/usr/sbin/init"         8 minutes ago       Exited (129) 28 seconds ago                        k8s_manageiq.9d3271be_manageiq-gwljt_sample-project_02eba234-438f-11e6-8102-525400825485_ad2a073d
20fedb49c54e        manageiq/manageiq:latest                                                                                          "/usr/sbin/init"         About an hour ago   Exited (129) 9 minutes ago                         k8s_manageiq.9d3271be_manageiq-gwljt_sample-project_02eba234-438f-11e6-8102-525400825485_80f442c4
b74eb901fc77        openshift3/ose-pod:v3.2.0.44                                                                                      "/pod"                   About an hour ago   Up About an hour                                   k8s_POD.6305dc28_manageiq-gwljt_sample-project_02eba234-438f-11e6-8102-525400825485_821ea38d
```

No logs are available for the pod either:

```
[vagrant@rhel-cdk ~]$ oc get pods
NAME                            READY     STATUS    RESTARTS   AGE
content-repository-68rwi        1/1       Running   0          1h
fabric8-2s5r1                   1/1       Running   0          1h
fabric8-docker-registry-23ae5   1/1       Running   0          1h
fabric8-forge-mheyd             1/1       Running   0          1h
gogs-ldnpr                      1/1       Running   0          1h
jenkins-8yu1r                   1/1       Running   0          1h
manageiq-gwljt                  1/1       Running   2          1h
nexus-5hd0u                     1/1       Running   1          1h
test-1-3tbgg                    1/1       Running   0          1h

[vagrant@rhel-cdk ~]$ oc logs manageiq-gwljt
```

Has anyone successfully launched the ManageIQ container before via fabric8?

What other information should I provide for troubleshooting and root cause analysis?

**Comment by rawlingsj** [comment]
Yeah it needs a kubernetes readiness check to say when it's available, I found it took quite sometime to start 2-3 mins.  Maybe you could check again now?  If still no luck could you see if there's anything in the logs?  `oc logs manageiq-gwljt` although from memory there wasn't much in the way of output there.

**Comment by jameslabocki** [comment]
It's been 2 hours and it's still unreachable. Logs still don't show anything:

```
[vagrant@rhel-cdk ~]$ oc logs manageiq-gwljt
[vagrant@rhel-cdk ~]$ 
```

Maybe this has something to do with it - there is no ports associated with the replication controller?

![screen shot 2016-07-06 at 1 24 14 pm](https://cloud.githubusercontent.com/assets/238043/16627837/00b6f6cc-437d-11e6-9838-e16eae549445.png)

**Comment by jameslabocki** [comment]
nevermind about the replication controller. For whatever reason, even locally within the running ManageIQ container I'm not able to access the admin console:

```
[root@manageiq-gwljt log]# curl -k https://localhost
curl: (7) Failed connect to localhost:443; Connection refused

```

**Comment by rawlingsj** [comment]
ah thats odd.. I'm arfaid I'm not able to look this evening but I will in the morning if you don't get anywhere

**Comment by jameslabocki** [comment]
I understand @rawlingsj - thanks for your help so far. Looking at the evm.log I see this:

```
[----] I, [2016-07-06T17:39:03.204286 #6586:3fb3520d1980]  INFO -- : MIQ(Vmdb::Loggers.apply_config) Log level for vim.log has been changed to [WARN]
[----] I, [2016-07-06T17:39:03.755081 #6586:3fb3520d1980]  INFO -- : MIQ(SessionStore) Using session_store: ActionDispatch::Session::MemCacheStore
[----] I, [2016-07-06T17:39:03.905198 #6586:3fb3520d1980]  INFO -- : MIQ(Vmdb::Initializer.init) - Program Name: /opt/rubies/ruby-2.2.5/bin/rake, PID: 6586, ENV['MIQ_GUID']: , ENV['EVMSERVER']: 
[----] I, [2016-07-06T17:39:05.679315 #6586:3fb3520d1980]  INFO -- : MIQ(EvmApplication.start) EVM Startup initiated
[----] I, [2016-07-06T17:39:12.174756 #6605:3f9a3331b980]  INFO -- : MIQ(EvmDatabaseOps.start) Starting internal database
[----] I, [2016-07-06T17:39:12.174918 #6605:3f9a3331b980]  INFO -- : MIQ(PostgresAdmin.runcmd_with_logging) Running command... service rh-postgresql94-postgresql start
[----] E, [2016-07-06T17:39:12.211886 #6605:3f9a3331b980] ERROR -- : AwesomeSpawn: service rh-postgresql94-postgresql start exit code: 1
[----] E, [2016-07-06T17:39:12.212008 #6605:3f9a3331b980] ERROR -- : AwesomeSpawn: Redirecting to /bin/systemctl start  rh-postgresql94-postgresql.service
Job for rh-postgresql94-postgresql.service failed because the control process exited with error code. See "systemctl status rh-postgresql94-postgresql.service" and "journalctl -xe" for details.
```

I'm guessing this is either because the database isn't initialized or because there is some privileged operations preventing something from working.

**Comment by jameslabocki** [comment]
When I see why the appliance is failing to start I only see the following error:

```
[root@manageiq-gwljt log]#  systemctl status evmserverd.service
● evmserverd.service - EVM server daemon
   Loaded: loaded (/usr/lib/systemd/system/evmserverd.service; enabled; vendor preset: disabled)
   Active: activating (start) since Wed 2016-07-06 17:54:44 UTC; 714ms ago
  Control: 8588 (evmserver.sh)
   CGroup: /system.slice/docker-f2d9674a0f9a9951d20869a547599a0c6a35a29d9383e67304d44babd0153f5e.scope/system.slice/evmserverd.service
           ├─8588 /bin/bash /bin/evmserver.sh start
           └─8590 ruby /opt/rubies/ruby-2.2.5/bin/rake evm:start
           ‣ 8588 /bin/bash /bin/evmserver.sh start

Jul 06 17:54:44 manageiq-gwljt systemd[1]: Starting EVM server daemon...
Jul 06 17:54:45 manageiq-gwljt sh[8588]: fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by jameslabocki** [comment]
@rawlingsj I stumbled upon these scripts `https://github.com/ManageIQ/manageiq/tree/master/docker-assets` and ran the appliance initialization. It seems to have initialized the database and I'm watching /var/www/miq/vmdb/log/evm.log as the appliance is now starting. 

My question is ... should fabric8 already have done this when I created the app? It seems like connecting you with Bazulay and Franco Bladilo who authored those scripts and working on containerizing ManageIQ downstream as CloudForms for running on Kubernetes would be a good idea.

**Comment by rawlingsj** [comment]
@jameslabocki yeah that sounds like a good idea.. I just tried this morning and it worked once then failed subsequent times so it sounds like there's something not quite right when the container starts.  Happy to connect to Bazulay and Franco to help figure it out.

**Comment by jameslabocki** [comment]
So, the way I worked around this was this:

I stopped the evm service on the manageiq container because it appears the service sits at "starting" waiting for the postgres database to be available. It's important to stop it before you do the next steps otherwise it will grab the database before it's completely initialized causing errors.

```
[root@manageiq-9a84j vmdb]# systemctl stop evmserverd.service

[root@manageiq-9a84j vmdb]# systemctl status evmserverd.service
● evmserverd.service - EVM server daemon
   Loaded: loaded (/usr/lib/systemd/system/evmserverd.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2016-07-07 13:11:45 UTC; 54s ago
  Process: 2660 ExecStart=/bin/sh -c /bin/evmserver.sh start (code=killed, signal=TERM)

Jul 07 13:11:53 manageiq-9a84j sh[2660]: /var/www/miq/vmdb/app/models/miq_server.rb:533:in `block in <class:MiqServer>'
Jul 07 13:11:53 manageiq-9a84j sh[2660]: /var/www/miq/vmdb/gems/pending/util/extensions/miq-module.rb:37:in `call'
Jul 07 13:11:53 manageiq-9a84j sh[2660]: /var/www/miq/vmdb/gems/pending/util/extensions/miq-module.rb:37:in `block (2 levels) in cache_with_timeout'
Jul 07 13:11:53 manageiq-9a84j sh[2660]: /var/www/miq/vmdb/gems/pending/util/extensions/miq-module.rb:25:in `block in cache_with_timeout'
Jul 07 13:11:53 manageiq-9a84j sh[2660]: /var/www/miq/vmdb/app/models/miq_server/worker_management.rb:14:in `kill_all_workers'
Jul 07 13:11:53 manageiq-9a84j sh[2660]: /var/www/miq/vmdb/lib/tasks/evm_application.rb:21:in `start'
Jul 07 13:11:53 manageiq-9a84j sh[2660]: /var/www/miq/vmdb/lib/tasks/evm.rake:7:in `block (2 levels) in <top (required)>'
Jul 07 13:11:53 manageiq-9a84j sh[2660]: Tasks: TOP => evm:start
Jul 07 13:11:53 manageiq-9a84j sh[2660]: (See full trace by running task with --trace)
Jul 07 13:11:54 manageiq-9a84j systemd[1]: Stopped EVM server daemon.
```

You'll notice if you try to start the postgres database service it fails:

```
root@manageiq-9a84j vmdb]# systemctl start rh-postgresql94-postgresql.service
Job for rh-postgresql94-postgresql.service failed because the control process exited with error code. See "systemctl status rh-postgresql94-postgresql.service" and "journalctl -xe" for details.

[root@manageiq-9a84j vmdb]# journalctl -xe
Jul 07 13:13:09 manageiq-9a84j postgresql-check-db-dir[2780]: Directory "/var/opt/rh/rh-postgresql94/lib/pgsql/data" is missing or empty.
Jul 07 13:13:09 manageiq-9a84j postgresql-check-db-dir[2780]: Use "/opt/rh/rh-postgresql94/root/usr/bin/postgresql-setup --initdb"
Jul 07 13:13:09 manageiq-9a84j postgresql-check-db-dir[2780]: to initialize the database cluster.
Jul 07 13:13:09 manageiq-9a84j postgresql-check-db-dir[2780]: See /opt/rh/rh-postgresql94/root/usr/share/doc/rh-postgresql94-postgresql-9.4.5/README.rpm-dist for more information.
Jul 07 13:13:09 manageiq-9a84j systemd[1]: rh-postgresql94-postgresql.service: control process exited, code=exited status=1
Jul 07 13:13:09 manageiq-9a84j systemd[1]: Failed to start PostgreSQL database server.
-- Subject: Unit rh-postgresql94-postgresql.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rh-postgresql94-postgresql.service has failed.
-- 
-- The result is failed.
Jul 07 13:13:09 manageiq-9a84j systemd[1]: Unit rh-postgresql94-postgresql.service entered failed state.
Jul 07 13:13:09 manageiq-9a84j systemd[1]: rh-postgresql94-postgresql.service failed.
Jul 07 13:13:21 manageiq-9a84j systemd[1]: Stopped PostgreSQL database server.
```

Now initialize the database manually:

```
[root@manageiq-9a84j vmdb]# /usr/bin/appliance-initialize.sh 
fatal: Not a git repository (or any of the parent directories): .git
configuring internal database
Initialize postgresql starting
Initialize postgresql complete
Checking for connections to the database...

Create region starting
Create region complete
```

Now start the evmserverd.service:

```
[root@manageiq-9a84j vmdb]# systemctl start evmserverd.service
[root@manageiq-9a84j vmdb]# systemctl status evmserverd.service
● evmserverd.service - EVM server daemon
   Loaded: loaded (/usr/lib/systemd/system/evmserverd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-07-07 13:16:50 UTC; 3min 6s ago
  Process: 3101 ExecStart=/bin/sh -c /bin/evmserver.sh start (code=exited, status=0/SUCCESS)
 Main PID: 3125 (ruby)
   CGroup: /system.slice/docker-8f5abeee8e205e6b9e30f64c6e8c0e40a8d20c8e9db2c074d9d87af1d0416804.scope/system.slice/evmserverd.service
           ├─3125 MIQ Server
           ├─3307 MIQ: MiqEventHandler id: 1, queue: ems
           ├─3312 MIQ: MiqGenericWorker id: 2, queue: generic
           ├─3317 MIQ: MiqGenericWorker id: 3, queue: generic
           ├─3322 MIQ: MiqPriorityWorker id: 4, queue: generic
           ├─3328 MIQ: MiqPriorityWorker id: 5, queue: generic
           ├─3334 MIQ: MiqReportingWorker id: 6, queue: reporting
           ├─3340 MIQ: MiqReportingWorker id: 7, queue: reporting
           ├─3347 MIQ: MiqScheduleWorker id: 8
           ├─3359 puma 3.3.0 (tcp://127.0.0.1:5000) [MIQ: Web Server Worker]
           ├─3383 puma 3.3.0 (tcp://127.0.0.1:3000) [MIQ: Web Server Worker]
           └─3393 puma 3.3.0 (tcp://127.0.0.1:4000) [MIQ: Web Server Worker]
           ‣ 3125 MIQ Server

Jul 07 13:16:41 manageiq-9a84j systemd[1]: Starting EVM server daemon...
Jul 07 13:16:41 manageiq-9a84j sh[3101]: fatal: Not a git repository (or any of the parent directories): .git
Jul 07 13:16:50 manageiq-9a84j sh[3101]: Starting EVM...
Jul 07 13:16:50 manageiq-9a84j sh[3101]: Running EVM in background...
Jul 07 13:16:50 manageiq-9a84j systemd[1]: Started EVM server daemon.
Jul 07 13:19:51 manageiq-9a84j systemd[1]: Started EVM server daemon.
```

My guess is this is some sort of timing problem with the database initialization script running when something isn't ready. After that the evmserverd.service steps on the database not being ready and this creates a cascade of problems. It seems like it could be remedied with a little more verification in the appliance-initialization service.

**Comment by rawlingsj** [comment]
yeah I wonder how hard it is to split out the database into its own container so we can use a kubernetes readiness check to say when the DB has finished initialising?

**Comment by jameslabocki** [comment]
Sadly, even after all that the admin console was not reachable. I was able to reach the admin console from the container itself via ```curl -k https://localhost``` but not from outside the container. Also, after about 30 minutes the container is killed and a new one is started and this process repeats.

**Comment by rawlingsj** [comment]
I just tried again on our kubernetes cluster on GKE, I was able access the console and log in successully

<img width="1439" alt="screenshot 2016-07-07 17 25 46" src="https://cloud.githubusercontent.com/assets/1457180/16660833/08040e9c-4468-11e6-9b7c-70dad83ce988.png">

I'll try killing the pod a few times to see if it comes back up and how long it takes.

**Comment by rawlingsj** [comment]
Ah I wonder... I dont have an openshift environment at the moment but I wonder if its because it's https and not http?  i.e. the service pod and service are using port 443, I'll add another service for 80 now to see if that works but in the meantime you could try https.

**Comment by jameslabocki** [comment]
I did try https but that didn't work either. I wonder if it has something to do with running on the CDK. I'll try to reproduce in the lab once the large OpenShift/OpenStack environment is available.

**Comment by rawlingsj** [comment]
@jameslabocki I've just taken a proper look at this and found out what the issue is.  ManageIQ was running fine on our GKE environment but on OpenShift I had to edit the route to enable TLS passthrough termination.

i.e. after `oc edit route manageiq` add in this TLS section

```
  tls:
    termination: passthrough
```
so it resembles the yaml below...
```
spec:
  host: manageiq.what.ever.your.domain.is
  tls:
    termination: passthrough
  to:
    kind: Service
    name: manageiq

```
We'll find out a way to enable this by default but in the meantime if you add that config I'm confident you'll be able to access ManageIQ on OpenShift.

I've also fixed up the readiness and liveness probes so it's clear when manageiq is available.  This will be in the next release which I'll kick off shortly.

**Comment by jameslabocki** [comment]
Thanks @rawlingsj - I'll give it a shot this afternoon and see if it works!

**Comment by rawlingsj** [comment]
@jameslabocki ok great - let me know if there's any issues - the release has finished so if you pull in the latest then fingers crossed everything will work OOTB.

**Comment by jameslabocki** [comment]
Now the ManageIQ pod keeps crashing (see below). I'm going to see if I can make this work on some bigger iron as running all this on the CDK seems very slow.

```
[vagrant@rhel-cdk ~]$ kubectl get pods
NAME                            READY     STATUS             RESTARTS   AGE
fabric8-docker-registry-0db7t   1/1       Running            0          57m
fabric8-forge-9km9h             1/1       Running            0          57m
fabric8-s2f41                   1/1       Running            0          57m
gogs-984iy                      1/1       Running            0          57m
jenkins-9crkh                   1/1       Running            0          57m
manageiq-avbto                  0/1       CrashLoopBackOff   6          13m
nexus-ost83                     1/1       Running            0          57m
```

**Comment by jameslabocki** [comment]
Also, the latest deployment did not have the tls line in the manageiq route, but I manually added it. What I did to get the latest was vagrant destroy, vagrant up, re-run gofabric8 deploy, then create a new app from within fabric8 selecting ManageIQ.

**Comment by rawlingsj** [comment]
Sounds like the liveness check is kicking in and restarting the pod, for now I've removed that and just left the readiness check.  

BTW if you don't want to destroy the VM and recreate it then you can remove the fabric8 parts and install the latest versions by...

```
oc delete all -l provider=fabric8
oc delete templates --all
gofabric8 deploy
```

**Comment by jameslabocki** [comment]
After deploying manageiq pod - 19 minutes later the readiness check hasn't finished and we have 9 restarts.

```
[vagrant@rhel-cdk ~]$ oc get pods
NAME                            READY     STATUS    RESTARTS   AGE
fabric8-55fmv                   1/1       Running   0          40m
fabric8-docker-registry-gudwz   1/1       Running   0          39m
fabric8-forge-jarbs             1/1       Running   0          39m
gogs-w7r1p                      1/1       Running   0          39m
jenkins-rp25o                   1/1       Running   0          39m
manageiq-kqpey                  0/1       Running   9          19m
nexus-y4w8x                     1/1       Running   0          39m
```

if I grab the docker container and try to enter it, it's disappeared and CrashLoopBackOff appears as the status for the manageiq pod.


```
[vagrant@rhel-cdk ~]$ docker ps |grep -i manageiq
4e7f598a41c6        manageiq/manageiq:latest                              "/usr/sbin/init"         30 seconds ago      Up 28 seconds                           k8s_manageiq.b9d96e3d_manageiq-kqpey_sample-project_cbced20e-4866-11e6-8755-525400825485_99d566b0
6f99120c866b        openshift3/ose-pod:v3.2.0.44                          "/pod"                   19 minutes ago      Up 19 minutes                           k8s_POD.6305dc28_manageiq-kqpey_sample-project_cbced20e-4866-11e6-8755-525400825485_ecb004fe


[vagrant@rhel-cdk ~]$ docker exec -i -t 4e7f598a41c6 /bin/bash
Error response from daemon: Container 4e7f598a41c6 is not running


[vagrant@rhel-cdk ~]$ docker ps |grep -i manageiq
6f99120c866b        openshift3/ose-pod:v3.2.0.44                          "/pod"                   19 minutes ago      Up 19 minutes                           k8s_POD.6305dc28_manageiq-kqpey_sample-project_cbced20e-4866-11e6-8755-525400825485_ecb004fe
[vagrant@rhel-cdk ~]$ oc get pods
NAME                            READY     STATUS             RESTARTS   AGE
fabric8-55fmv                   1/1       Running            0          40m
fabric8-docker-registry-gudwz   1/1       Running            0          40m
fabric8-forge-jarbs             1/1       Running            0          40m
gogs-w7r1p                      1/1       Running            0          40m
jenkins-rp25o                   1/1       Running            0          40m
manageiq-kqpey                  0/1       CrashLoopBackOff   9          19m
nexus-y4w8x                     1/1       Running            0          40m
```

Is that the liveness check kicking in or something else? I redeployed today about an hour ago. 

Thanks for the short cut on recreating the environment. The reason I destroy is because I want my memory back from the vagrant image. :)

**Comment by rawlingsj** [comment]
That's really frustrating. I'm not 100% sure but I'm inclined to think this is related somehow to the CDK. It's been working fine on GKE and the fabric8 origin VM. I'll grab the CDK in the morning and figure out what's going on. Sorry about the back and forth over this issue. It's up to you but if you just want to get manageiq app running locally then use the fabric8 vagrant image until I can test this out myself on the CDK.

**Comment by jameslabocki** [comment]
@rawlingsj  I was able to get this working on OpenShift Enterprise on OpenStack. I did have to disable the liveness and readiness checks and change the TLS to pass through.

**Comment by jameslabocki** [comment]
@rawlingsj I opened this issue with ManageIQ requesting they maintain an OpenShift application template or at least kubernetes deployment files and also to split ManageIQ into multiple containers.

https://github.com/ManageIQ/manageiq/issues/9921
