### ISSUE TITLE
Vanilla Kubernetes + fabric8 fails to build any workflow

### ISSUE THREAD

**Issue by rpots** [fabric8io/fabric8#6207]
Hello,

I have installed kubernetes on AWS and Fabric8 successfully.

Creating an app using any workflow fails with the following error on Jenkins:

Unable to connect to Elasticsearch service. Check Elasticsearch is running in the correct namespace
java.lang.RuntimeException: java.lang.RuntimeException: Failed to push image. Error:Get https://100.64.98.45:80/v1/_ping: tls: oversized record received with length 20527
	at io.fabric8.kubernetes.pipeline.PushImageStepExecution$1.call(PushImageStepExecution.java:103)
	at io.fabric8.kubernetes.pipeline.PushImageStepExecution$1.call(PushImageStepExecution.java:50)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to a5f7ffcaee(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at io.fabric8.kubernetes.pipeline.PushImageStepExecution.run(PushImageStepExecution.java:50)
	at io.fabric8.kubernetes.pipeline.PushImageStepExecution.run(PushImageStepExecution.java:39)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:137)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at io.fabric8.kubernetes.pipeline.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:350)
	at io.fabric8.kubernetes.pipeline.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.pipeline.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:349)
	at io.fabric8.kubernetes.pipeline.Kubernetes$PushImage.toRegistry(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:355)
	at mavenCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/mavenCanaryRelease.groovy:33)
	at WorkflowScript.run(WorkflowScript:28)
	at io.fabric8.kubernetes.pipeline.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:123)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to push image. Error:Get https://100.64.98.45:80/v1/_ping: tls: oversized record received with length 20527
	at io.fabric8.kubernetes.pipeline.PushImageStepExecution$1$1.onError(PushImageStepExecution.java:87)
	at io.fabric8.docker.client.impl.EventHandle.onEvent(EventHandle.java:148)
	at io.fabric8.docker.client.impl.EventHandle.access$000(EventHandle.java:46)
	at io.fabric8.docker.client.impl.EventHandle$1.call(EventHandle.java:114)
	at io.fabric8.docker.client.impl.EventHandle$1.call(EventHandle.java:111)
	at io.fabric8.docker.client.utils.InputStreamPumper.run(InputStreamPumper.java:63)
	... 5 more
Finished: FAILURE

Apparently it is trying to connection over https using port 80 (strange). And there is an error. This is strange as this is a vanilla installation of Kubernetes and Fabric8.

**Comment by rawlingsj** [comment]
Yeah this popped up on the IRC channel about a month ago and we we really ought to have a getting stared guide that covers AWS sorry. Will try to get to it soon. 

I'm pretty confident this issue can be resolved by adding the insecure registry flag to each nodes docker options, then restart the docker service, this will recreate all the pods but the next new project will hopefully work. 

I.e using the link below add this flag for your registry 
--insecure-registry=100.64.0.0/16

https://docs.docker.com/registry/insecure/

If this works we ought to keep this issue open until we add in some checks to gofabric8 that helps identify the problem and add docs to getting started with AWS.

**Comment by rpots** [comment]
@rawlingsj  Thank you. That solved the issue straight away.

**Comment by rawlingsj** [comment]
That's great to hear! 

We'll get some AWS docs done within the next couple of weeks so that we hopefully avoid this in the future.

**Comment by iscra** [comment]
The above Docker flag has also solved the issue for our Fabric8 on custom cluster built on CoreOS.

**Comment by Mahaswami** [comment]
@rpots To change the flag, I am trying to locate a method to SSH into the node since I did not ask the cluster setup process to use my existing key. 

Would you mind sharing how you went about this?
