### ISSUE TITLE
SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6229]
After creating a new cluster on AWS using [stackpoint](https://stackpoint.io) we're seeing an error during pipelines, this log is from a new nodejs app when the pipeline uses Kubernetes client to figure out if we're running in a single node.  I'm not sure if this is fabric8 using an non supported hostname of `kubernetes.default.svc` or the cert that stackpoint created is missing it?

@iocanel @jimmidyson any ideas?

Full exception...

`javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Pzd8x1G60bqJE9ivlggxLwdHl5k=
    DN: CN=kube-apiserver
    subjectAltNames: [172.23.1.192, 52.17.103.152, 10.200.0.1, kubernetes, kubernetes.default, kubernetes.default.svc.cluster.local]`

```
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:418)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:58)
	at io.fabric8.kubernetes.client.dsl.Listable$list.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:393)
	at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at performCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/performCanaryRelease.groovy:17)
	at WorkflowScript.run(WorkflowScript:16)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:74)
	at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha1/Pzd8x1G60bqJE9ivlggxLwdHl5k=
    DN: CN=kube-apiserver
    subjectAltNames: [172.23.1.192, 52.17.103.152, 10.200.0.1, kubernetes, kubernetes.default, kubernetes.default.svc.cluster.local]
	at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:201)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:93)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:416)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:58)
	at io.fabric8.kubernetes.client.dsl.Listable$list.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at io.fabric8.Fabric8Commands.isSingleNode(Fabric8Commands.groovy:393)
	at io.fabric8.Fabric8Commands$isSingleNode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	... 24 more
Finished: FAILURE
```

**Comment by rawlingsj** [comment]
I've just changed the pipeline script to use the f.q.d.n as listed in the exception above subjectAltNames, and this works..

```
KubernetesClient kubernetes = new DefaultKubernetesClient('https://kubernetes.default.svc.cluster.local');
```

So either the certs generated by stackpoint need to accept `kubernetes.default.svc` or we need to change our default master URL in KubernetesClient to`kubernetes.default.svc.cluster.local`

**Comment by rawlingsj** [comment]
Another workaround is to add an env var to the jenkins master
```
kubectl edit deployment jenkins
```
add to the env vars section..

```
name: KUBERNETES_MASTER
value: kubernetes.default
```
and let kubernetes restart the jenkins pod with the updated env var

**Comment by rawlingsj** [comment]
It might be worth adding in the `KUBERNETES_MASTER` env var to the jenkins deployment yaml as a temporary workaround until we get the cert updated? https://github.com/fabric8io/fabric8-devops/blob/master/jenkins/src/main/fabric8/jenkins-deployment.yml#L36

**Comment by jimmidyson** [comment]
`kubernetes.default.svc` was the address suggested to us by a RHT Kubernetes maintainer... we could change this to kubernetes.default but i'd suggest to stackpoint that they should support the `kubernetes.default.svc` too as it's a totally valid DNS name to access the API server from a pod.

**Comment by rawlingsj** [comment]
yeah - we've done that too, its just the cert hasn't been updated yet and people are going to hit this.  I'll followup again and see if it is something stackpoint is looking at doing.  Until then does it sound fair to add this work around to save the initial user experience?

**Comment by jimmidyson** [comment]
Yeah, yet another workaround...

**Comment by DonMartin76** [comment]
Also ran into this today. Hooray. Sorry for the enthusiasm, but it's just one issue after the other (not only with this).
