### ISSUE TITLE
fabric8:deploy broken after 3.1.1

### ISSUE THREAD

**Issue by ntrvic** [fabric8io/fabric8#6261]
Hello,

I am trying to deploy a kubernetes spec to our cluster using fabric8:deploy. Seems to work in 3.1.1, but anything more recent results in the following error:
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.2:deploy (default-cli) on project app.collection.serp.parser: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.2:deploy failed: An error has occurred. CLEARTEXT communication not supported: [ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)] -> [Help 1]
```
Would anyone know what could be causing this problem?
Thanks a lot,
Victor
@jgangemi

full stack trace:
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.15:deploy (default-cli) on project app.collection.serp.parser: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.15:deploy failed: An error has occurred. CLEARTEXT communication not supported: [ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.15:deploy (default-cli) on project app.collection.serp.parser: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.15:deploy failed: An error has occurred.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.15:deploy failed: An error has occurred.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:156)
	at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:150)
	at io.fabric8.kubernetes.api.KubernetesHelper.isOpenShift(KubernetesHelper.java:2153)
	at io.fabric8.maven.plugin.DeployMojo.executeInternal(DeployMojo.java:185)
	at io.fabric8.maven.plugin.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:49)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.net.UnknownServiceException: CLEARTEXT communication not supported: [ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)]
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:103)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:149)
	... 26 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by ntrvic** [comment]
In case this helps here is the spec I was testing with:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: parser
spec:
  replicas: 1
  template:
    metadata:
      name: parser
      labels:
        name: parser
        tier: backend
        namespace: parser
    spec:
      containers:
       - name: "parser"
         image: "registry/parser:latest"
         resources:
            requests:
              cpu: 6
              memory: 4Gi
         args:
                - --append-javaopt
                - -Dcond.deploy.dcontext=/prod/collection/asyncSerpParser
         ports:
           -
             containerPort: 8181
```

**Comment by christian-posta** [comment]
@ntrvic what flavor of Kubernetes are you running? GKE? OpenShift?

**Comment by ntrvic** [comment]
@christian-posta i'm running 1.3.4 on aws. Basic setup, non secure cluster. I thought the non secure part might be related. We provisioned all the services from scratch so just passed something like `--cloud-provider=aws` and setup the proper iam rules.

**Comment by jimmidyson** [comment]
Looks like I messed up communication to non secure kubernetes in recent version of kubernetes-client. Thought we had tests for that... sorry! I'm on PTO so won't be able to look at this until next week - help appreciated! @iocanel maybe?

**Comment by jstrachan** [comment]
BTW I wonder if a newer version of the fabric8-maven-plugin might have this fixed? I see you are using 3.1.2 and there's now 3.1.17.

@jimmidyson I hit this issue with jenkinshift + kubernetes + BuildConfig recently. Seems this is the offending code you added: https://github.com/fabric8io/kubernetes-client/commit/1e2f27c7f09ab6571178ebb9175636c6f7292289#diff-b049f296ce77937d1b28c472e0707370R82-L85

I wonder if there's a way to only enable this SSL stuff https://github.com/fabric8io/kubernetes-client/blob/1e2f27c7f09ab6571178ebb9175636c6f7292289/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L83-L86 if we know the URL is a https URL?

**Comment by jgangemi** [comment]
where is the source code for v3 of the maven plugin? according to @ntrvic, v3 doesn't require a `fabric8` server any more, but i don't see that reflected in `master`, at least i don't think.

**Comment by jstrachan** [comment]
version 2.x and 3.x of the maven plugin just requires kubernetes/docker/openshift; there's no 'fabric8 server' any more.

Version 3.x is here: https://maven.fabric8.io/ or the code is here: https://github.com/fabric8io/fabric8-maven-plugin

**Comment by jgangemi** [comment]
awesome, i was finding the one here: https://github.com/fabric8io/fabric8/tree/master/fabric8-maven-plugin

**Comment by jstrachan** [comment]
yeah, thats the 2.x version of the fabric8 maven plugin

**Comment by jstrachan** [comment]
FWIW I made it a bit more clear on the readme here: https://github.com/fabric8io/fabric8/blob/master/fabric8-maven-plugin/ReadMe.md
