### ISSUE TITLE
Created applications are not shown in dashboard and Environment panels stay empty. 

### ISSUE THREAD

**Issue by iscra** [fabric8io/fabric8#6279]
Fabric8 on 3 node Kubernetes cluster.
Created Microservice app. Build successful, pipeline and logs window update correctly.
Environment panel does not update, stays empty.
Dashboard does not show the app.

```
[hawtio-oauth] All oauth plugins have executedlibs-f994e0f7.js:39:20456
[kubernetes-watcher] Backend is a vanilla Kubernetes instance, namespace kind:  namespaceslibs-f994e0f7.js:39:20456
[k8s-objects] Using polling for kind:  buildconfigslibs-f994e0f7.js:39:20456
[k8s-objects] Failed to fetch data while connecting to backend for type:  ingresses  error:  Object { kind: "Status", apiVersion: "v1", metadata: Object, status: "Failure", message: "the server could not find the reque…", reason: "NotFound", details: Object, code: 404 }libs-f994e0f7.js:39:20456
[fabric8-console] started, version:  1.0.73libs-f994e0f7.js:39:20456
[fabric8-console] commit ID:  69b54b79954eb2233e56fcf45ed8f496d067d157libs-f994e0f7.js:39:20456
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/default/ingresses?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/default/configmaps?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/default/events?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/default/pods?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/default/replicationcontrollers?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/default/secrets?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/default/services?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/apis/extensions/v1beta1/namespaces/default/replicasets?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/apis/extensions/v1beta1/namespaces/default/deployments?watch=true&access_token.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/api/v1/namespaces/default/ingresses?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/api/v1/namespaces/default/configmaps?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/api/v1/namespaces/default/events?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/api/v1/namespaces/default/pods?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/api/v1/namespaces/default/replicationcontrollers?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/api/v1/namespaces/default/secrets?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/api/v1/namespaces/default/services?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/apis/extensions/v1beta1/namespaces/default/replicasets?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
The connection to ws://30060/k8s/apis/extensions/v1beta1/namespaces/default/deployments?watch=true&access_token was interrupted while the page was loading.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://k8s/apis/extensions/v1beta1/ingresses?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://k8s/apis/extensions/v1beta1/ingresses?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/fabric8/events?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/fabric8/pods?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/fabric8/replicationcontrollers?watch=true&access_token.libs-f994e0f7.js:80:15719
Firefox can’t establish a connection to the server at ws://30060/k8s/api/v1/namespaces/fabric8/secrets?watch=true&access_token.libs-f994e0f7.js:80:15719
```

**Comment by jimmidyson** [comment]
Looks like the hostname is being dropped from the WS URLs... @gashcrumb @jstrachan?

**Comment by iscra** [comment]
I think this is related to using Kubernetes namespace, which we do in our cluster.

I have tried some older dev console versions and see the same issues there (2.2.169, 2.2.167).

Using fresh install of Fabric8 in a default namespace - the console works now properly updating the environments for the new project being built. The dashboard also show the new created app deployments in testing and staging environments.

The JS console also shows less errors, related to websocket connections.

**Comment by rawlingsj** [comment]
I wondered if this is related to https://github.com/fabric8io/fabric8/issues/6290 or https://github.com/fabric8io/fabric8/issues/6310?

**Comment by gashcrumb** [comment]
We did have an issue with using the right hostname when the console has to use it's own proxy, but that should be sorted now.  Have you seen this with an updated console by any chance?

**Comment by iscra** [comment]
No, just switched to using default namespace for now.
