### ISSUE TITLE
Error trying to run new build forge command

### ISSUE THREAD

**Issue by stephanosbacon** [fabric8io/fabric8#6295]
I have fabric8 running in minishift on osx.  I have created a microservice project with a pipeline that just does a maven deploy, and I was futzing around with how to add a new pipeline or change it so it deploys a pod and all that.

I tried the new build option in the devops forge category, called the new build ms1a and got the following:

java.lang.RuntimeException: Failed to create BuildConfig from generated BuildConfig: {
  "apiVersion" : "v1",
  "kind" : "BuildConfig",
  "metadata" : {
    "annotations" : { },
    "labels" : {
      "name" : "ms1a"
    },
    "name" : "ms1a"
  },
  "spec" : {
    "source" : {
      "git" : {
        "uri" : "http://172.30.171.8:80/gogsadmin/ms1.git"
      },
      "images" : [ ],
      "secrets" : [ ],
      "type" : "Git"
    },
    "triggers" : [ {
      "github" : {
        "secret" : "secret101"
      },
      "type" : "github"
    }, {
      "generic" : {
        "secret" : "secret101"
      },
      "type" : "generic"
    } ]
  }
}. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/oapi/v1/namespaces/default/buildconfigs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.api.Controller.onApplyError(Controller.java:1284)
	at io.fabric8.kubernetes.api.Controller.doCreateBuildConfig(Controller.java:834)
	at io.fabric8.kubernetes.api.Controller.applyBuildConfig(Controller.java:822)
	at io.fabric8.forge.devops.NewBuildCommand.execute(NewBuildCommand.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.devops.NewBuildCommand_$$_javassist_f7208945-cb96-42f4-be8e-a2ea4fdeb1af.execute(NewBuildCommand_$$_javassist_f7208945-cb96-42f4-be8e-a2ea4fdeb1af.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.execute(SingleCommandControllerImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_c36f7379-79a7-4fa2-a4a5-4e28fc93c3ca.execute(CommandController_$$_javassist_c36f7379-79a7-4fa2-a4a5-4e28fc93c3ca.java)
	at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:380)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:279)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:275)
	at io.fabric8.forge.rest.CommandsResource$6.call(CommandsResource.java:583)
	at io.fabric8.forge.rest.git.RepositoryResource$15.call(RepositoryResource.java:800)
	at io.fabric8.forge.rest.git.GitLockManager.withLock(GitLockManager.java:45)
	at io.fabric8.forge.rest.git.RepositoryResource.gitOperation(RepositoryResource.java:753)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteoperation(RepositoryResource.java:749)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:743)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:593)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:561)
	at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/oapi/v1/namespaces/default/buildconfigs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:314)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:265)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:236)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:207)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:547)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:243)
	at io.fabric8.kubernetes.api.Controller.doCreateBuildConfig(Controller.java:832)
	... 77 more
Caused by:

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/oapi/v1/namespaces/default/buildconfigs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:314)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:265)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:236)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:207)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:547)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:243)
	at io.fabric8.kubernetes.api.Controller.doCreateBuildConfig(Controller.java:832)
	at io.fabric8.kubernetes.api.Controller.applyBuildConfig(Controller.java:822)
	at io.fabric8.forge.devops.NewBuildCommand.execute(NewBuildCommand.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.devops.NewBuildCommand_$$_javassist_f7208945-cb96-42f4-be8e-a2ea4fdeb1af.execute(NewBuildCommand_$$_javassist_f7208945-cb96-42f4-be8e-a2ea4fdeb1af.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.execute(SingleCommandControllerImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_c36f7379-79a7-4fa2-a4a5-4e28fc93c3ca.execute(CommandController_$$_javassist_c36f7379-79a7-4fa2-a4a5-4e28fc93c3ca.java)
	at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:380)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:279)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:275)
	at io.fabric8.forge.rest.CommandsResource$6.call(CommandsResource.java:583)
	at io.fabric8.forge.rest.git.RepositoryResource$15.call(RepositoryResource.java:800)
	at io.fabric8.forge.rest.git.GitLockManager.withLock(GitLockManager.java:45)
	at io.fabric8.forge.rest.git.RepositoryResource.gitOperation(RepositoryResource.java:753)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteoperation(RepositoryResource.java:749)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:743)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:593)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:561)
	at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)

**Comment by jimmidyson** [comment]
Could you please share what docker image forge is running in your environment? You can see that in `kubectl descrive ...` (or in `docker ps` if you've run `eval $(minishift docker-env)`). Just want to check what ultimately base image it's using.

**Comment by jimmidyson** [comment]
Hmm looks like it's using Centos as a base image which should work fine.

**Comment by jimmidyson** [comment]
What version of minishift? Did you restart minishift (stop/start)? Sounds like a silly question but it could be that the service account token was invalidated due to some certificates being regenerated.

**Comment by stephanosbacon** [comment]
minishift version is 0.4.1.

The history is that I downloaded both gofabric8 and minishift, but did not put them in my path, using ./<whatever> to run them.  Foolishly, when I ran gofabric8 deploy, I just copy-pasted the command line from the wiki, so the reference to $(minishift ip) or whatever came up empty so fabric8 didn't work because the urls were screwed up (but note that gofabric8 validate didn't figure this out).  Anyway, once I realized what I did, I added them to my path, did a minishift delete, recreated the whole thing and it was all good.  I have not stopped and restarted the vm since then.

re docker image forge - What am I looking for? (and what would I describe?)

**Comment by jimmidyson** [comment]
> re docker image forge - What am I looking for? (and what would I describe?)

Don't worry, I've worked that out now. Thanks anyway.

Will have to look deeper.
