### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred

### ISSUE THREAD

**Issue by seanzhau** [fabric8io/fabric8#6298]
**I use kubernetes and skydns to test my fabric8,When I create application, I get the error:** 
`java.lang.RuntimeException: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
    at io.fabric8.forge.rest.main.GitCommandCompletePostProcessor.handleException(GitCommandCompletePostProcessor.java:251)
    at io.fabric8.forge.rest.main.GitCommandCompletePostProcessor.firePostCompleteActions(GitCommandCompletePostProcessor.java:187)
    at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:385)
    at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:279)
    at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:275)
    at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:600)
    at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:561)
    at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:275)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
    at org.eclipse.jetty.server.Server.handle(Server.java:524)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:745)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
    at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:141)
    at io.fabric8.kubernetes.api.Controller.applyBuildConfig(Controller.java:795)
    at io.fabric8.forge.rest.main.GitCommandCompletePostProcessor.createBuildConfig(GitCommandCompletePostProcessor.java:206)
    at io.fabric8.forge.rest.main.GitCommandCompletePostProcessor.firePostCompleteActions(GitCommandCompletePostProcessor.java:175)
    ... 52 more
Caused by: java.net.UnknownHostException: jenkinshift: unknown error
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
    at java.net.InetAddress.getAllByName(InetAddress.java:1192)
    at java.net.InetAddress.getAllByName(InetAddress.java:1126)
    at okhttp3.Dns$1.lookup(Dns.java:39)
    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
    at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
    at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at io.fabric8.kubernetes.api.Controller$JenkinShiftClient$3.intercept(Controller.java:469)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.execute(RealCall.java:60)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:234)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:225)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:559)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:134)
    ... 55 more`

**Comment by rawlingsj** [comment]
```
Caused by: java.net.UnknownHostException: jenkinshift
```

Suggests that your skydns isn't working quite as expected.  I wonder if it's worth testing your DNS using this approach to double check? https://github.com/kubernetes/kubernetes/blob/master/build/kube-dns/README.md#how-do-i-test-if-it-is-working

**Comment by seanzhau** [comment]
`# kubectl exec busybox -- nslookup kubernetes.default
Server:    172.16.0.2
Address 1: 172.16.0.2 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 172.16.0.1 kubernetes.default.svc.cluster.local`

**It looks like running well...
Maybe other problems, I get some error logs from skydns container**

`2016-08-30T07:45:26.424926000Z I0830 07:45:26.424502       1 dns.go:660] DNS Record:&{nexus.default.svc.cluster.local. 0 10 10  false 30 0  }, hash:deab1162
2016-08-30T07:45:26.425091000Z I0830 07:45:26.424582       1 dns.go:660] DNS Record:&{172.16.32.107 0 10 10  false 30 0  }, hash:525a1ddb
2016-08-30T07:45:26.425250000Z I0830 07:45:26.424626       1 dns.go:660] DNS Record:&{fabric8.default.svc.cluster.local. 0 10 10  false 30 0  }, hash:412e27a6
2016-08-30T07:45:37.302759000Z I0830 07:45:37.302014       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
2016-08-30T07:45:37.303385000Z I0830 07:45:37.302191       1 dns.go:539] records:[0xc8202c5180], retval:[{172.16.0.1 0 10 10  false 30 0  /skydns/local/cluster/svc/default/kubernetes/3561663664613235}], path:[local cluster svc default kubernetes]
2016-08-30T07:45:37.304602000Z I0830 07:45:37.303986       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
2016-08-30T07:45:37.304778000Z I0830 07:45:37.304024       1 dns.go:539] records:[0xc8202c5180], retval:[{172.16.0.1 0 10 10  false 30 0  /skydns/local/cluster/svc/default/kubernetes/3561663664613235}], path:[local cluster svc default kubernetes]
2016-08-30T07:45:37.305636000Z I0830 07:45:37.305190       1 dns.go:583] Received ReverseRecord Request:1.0.16.172.in-addr.arpa.
2016-08-30T07:45:37.503043000Z I0830 07:45:37.502025       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
2016-08-30T07:45:37.503252000Z I0830 07:45:37.502077       1 dns.go:539] records:[0xc8202c5180], retval:[{172.16.0.1 0 10 10  false 30 0  /skydns/local/cluster/svc/default/kubernetes/3561663664613235}], path:[local cluster svc default kubernetes]
2016-08-30T07:45:37.503437000Z I0830 07:45:37.502428       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false`

**Comment by ChadCorsentino** [comment]
Has this been solved yet for minikube fabric8 deployment?  I get the same errors, and cannot build apps no matter what I do.
