### ISSUE TITLE
demo failed to run because of the registry url error

### ISSUE THREAD

**Issue by Jaware** [fabric8io/fabric8#6314]
the error is as follow:
o.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://**localhost**/images/example/ha1:1.0.4/tag?tag=1.0.4&force=false&repo=10.0.0.108:80/example/ha1. Status:404. Message: Not Found. Body: no such id: example/ha1:1.0.4.............

i remember last time  i run the java jar demo,it worked,however when i deploy fabric8 to 3 kubernetes servers,it did not work,hope anyone can help me ,thanks

**Comment by jstrachan** [comment]
Where is that log from? Your terminal using maven or is it the Jenkins build log? 
Knowing which project you are building might help too. Any chance of the full build log?

**Comment by Jaware** [comment]
it is the Jenkins build log,full build log is as follows :

[Pipeline] tagImage
Tagging image:example/ha1:1.0.4 with tag:1.0.4.
[Pipeline] }
[Pipeline] // withPod
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Found Elasticsearch server, sending:{"timestamp":"2016-09-02T08:06:14.734+0000","build_number":4,"app":"ha1","build_result":"FAILURE","start_time":"2016-09-02T08:06:14.761+0000","duration":0,"env_vars":{"BUILD_DISPLAY_NAME":"#4","BUILD_ID":"4","BUILD_NUMBER":"4","BUILD_TAG":"jenkins-ha1-4","CLASSPATH":"","HUDSON_HOME":"/var/jenkins_home","HUDSON_SERVER_COOKIE":"f7950638c91954dd","JENKINS_HOME":"/var/jenkins_home","JENKINS_SERVER_COOKIE":"f7950638c91954dd","JOB_NAME":"ha1"},"build_url":"job/ha1/4/","causes":[{"short_description":"Started by user anonymous","user_name":"anonymous"}]}
Event created
io.fabric8.docker.client.DockerClientException: Failure executing: POST at: http://localhost/images/example/ha1:1.0.4/tag?tag=1.0.4&force=false&repo=10.0.0.108:80/example/ha1. Status:404. Message: Not Found. Body: no such id: example/ha1:1.0.4

	at io.fabric8.docker.client.impl.OperationSupport.requestFailure(OperationSupport.java:255)
	at io.fabric8.docker.client.impl.OperationSupport.assertResponseCodes(OperationSupport.java:239)
	at io.fabric8.docker.client.impl.OperationSupport.handleResponse(OperationSupport.java:191)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:88)
	at io.fabric8.docker.client.impl.TagImage.withTagName(TagImage.java:33)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:50)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution$1.call(TagImageStepExecution.java:41)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to 30ad991fb162(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:41)
	at io.fabric8.kubernetes.pipeline.TagImageStepExecution.run(TagImageStepExecution.java:28)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:137)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:113)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:298)
	at io.fabric8.kubernetes.pipeline.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.pipeline.Kubernetes$TagImage.withTag(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:297)
	at mavenCanaryRelease.call(/var/jenkins_home/workflow-libs/vars/mavenCanaryRelease.groovy:24)
	at WorkflowScript.run(WorkflowScript:46)
	at io.fabric8.kubernetes.pipeline.Kubernetes$Pod.inside(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:123)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:55)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:64)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:54)
	at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

**Comment by jstrachan** [comment]
which example are you building?

POSTing to http://localhost/ to tag docker images looks very wrong - any ideas how that could go so wrong @rawlingsj ?

**Comment by rawlingsj** [comment]
I'm not sure yet but wouldnt POSTing to localhost just mean the local mounted docker volume / socket?  

My first guess is this is another old f-m-p quickstart that we need to migrate to f-m-p 3.x.

The log above only starts at the tagging, would you mind adding a link to a gist of the full log please?  We're after which example / quickstart you're using and to see if the image was ever built.

**Comment by Jaware** [comment]
the java jar example, and i edited the maven plugin to the followings:
<plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
<version>3.1.17</version>
        <executions>
          <execution>
            <id>fmp</id>
            <goals>
              <goal>resource</goal>
              <goal>helm</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <images>
            <image>
              <name>${docker.image}</name>
              <build>
                <from>fabric8/java-jboss-openjdk8-jdk:1.1.7</from>
                <assembly>
                  <basedir>/app</basedir>
                  <descriptorRef>artifact</descriptorRef>
                </assembly>
                <ports>
                  <port>8080</port>
                </ports>
                <entryPoint>
                  <exec>
                    <arg>java</arg>
                    <arg>-jar</arg>
                    <arg>/app/${project.build.finalName}.jar</arg>
                  </exec>
                </entryPoint>
              </build>
            </image>
          </images>
        </configuration>
      </plugin>

**Comment by Jaware** [comment]
any solution?  😢

**Comment by rawlingsj** [comment]
Hi @Jaware I'm working on a fix at the moment, I think it's because there's a difference in assumed names.

Could you describe you exact steps to recreate please so I can test the fix before releasing?

I.e. which quickstart, was it a maven archetype, was it created from the fabric8 new project wizard, what you called it, any changes to group id or artifact it and which pipeline you selected.  That would help a lot and we'll get a fix asap.

**Comment by rawlingsj** [comment]
@Jaware I've got a fix which you could try out if you like before it's released.

If you clone you jenkins internal global library
```
git clone http://$YOUR_JENKINS_URL/workflowLibs.git
```

overrite the `vars/mavenCanaryRelease.groovy` with this one https://raw.githubusercontent.com/rawlingsj/jenkins-pipeline-library/master/vars/mavenCanaryRelease.groovy

Push back
```
git commit -a -m 'update' && git push origin master
```

And re-trigger the jenkins build

**Comment by Jaware** [comment]
sorry to see your reply too late,i will try but there is a question:http://$YOUR_JENKINS_URL/workflowLibs.git? you mean https://github.com/Jaware/jenkins-pipeline-library.git? and how can i apply it to  the jenkins deployed in fabric8?

**Comment by rawlingsj** [comment]
Ah no, it's the URL used to access Jenkins, if you've used a recent gofabric8 to install fabric8 you can get the URL with 
```
gofabric8 service jenkins -u
```
if not then I think the easiest way is to open up Jenkins using the toolbar / spanner in the top right hand corner of the fabric8 console.  Are you running on minikube / minishift / GKE / OpenShift?  I 

On my current setup with minishift I can clone the internal jenkins global library (which is running on the jenkins master) using

```
git clone http://192.168.64.28:31510/workflowLibs.git
```

**Comment by Jaware** [comment]
thanks ,it works😄

**Comment by Jaware** [comment]
but it comes a new error 😭：

[Pipeline] stage (Rolling Upgrade Staging)
Entering stage Rolling Upgrade Staging
Proceeding
[Pipeline] kubernetesApply
no kubernetes.yml found
[Pipeline] }
[Pipeline] // withPod
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Found Elasticsearch server, sending:{"timestamp":"2016-09-07T12:37:13.741+0000","build_number":6,"app":"vvqqqaaaa","build_result":"FAILURE","start_time":"2016-09-07T12:37:13.747+0000","duration":0,"env_vars":{"BUILD_DISPLAY_NAME":"#6","BUILD_ID":"6","BUILD_NUMBER":"6","BUILD_TAG":"jenkins-vvqqqaaaa-6","BUILD_URL":"http://192.168.64.3:31069/job/vvqqqaaaa/6/","CLASSPATH":"","HUDSON_HOME":"/var/jenkins_home","HUDSON_SERVER_COOKIE":"1fb464c497a515ad","HUDSON_URL":"http://192.168.64.3:31069/","JENKINS_HOME":"/var/jenkins_home","JENKINS_SERVER_COOKIE":"1fb464c497a515ad","JENKINS_URL":"http://192.168.64.3:31069/","JOB_NAME":"vvqqqaaaa","JOB_URL":"http://192.168.64.3:31069/job/vvqqqaaaa/"},"build_url":"job/vvqqqaaaa/6/","causes":[{"short_description":"Started by user anonymous","user_name":"anonymous"}]}
Event created
ERROR: Error during kubernetes apply: No resources passed into the step using the 'file' argument or found in the default target folder generated by the fabric8-maven-plugin
Finished: FAILURE

**Comment by rawlingsj** [comment]
Ah I think I know what that is. I've switched to the new fabric8-maven-plugin generates the manifests in a different folder structure. Not sure yet why I didn't hit that problem but I should be able to sort that ealily.
