### ISSUE TITLE
Create a new project fails - dns/ip confusion

### ISSUE THREAD

**Issue by omniscient** [fabric8io/fabric8#6354]
Hello.

I am on windows 10 and installed fabric8 using Vagrant 1.8.4 to overcome the ssh issues with 1.8.5 which I lost tons of time with by the way. I have VirtualBox 5.0.26 installed too.

Once I go through the steps here: https://fabric8.io/guide/getStarted/vagrant.html

I try to create a new project and I get the following error:
`SocketTimeoutException invoking http://172.30.233.200:80/api/v1/user/repos: connect timed out`

`
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: SocketTimeoutException invoking http://172.30.233.200:80/api/v1/user/repos: connect timed out
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:582)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:564)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:749)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:228)
	at com.sun.proxy.$Proxy156.createRepository(Unknown Source)
	at io.fabric8.repo.git.GitRepoClientSupport.createRepository(GitRepoClientSupport.java:101)
	at io.fabric8.forge.rest.main.GitCommandCompletePostProcessor.firePostCompleteActions(GitCommandCompletePostProcessor.java:144)
`

Notice the IP: `172.30.233.200`

If I ssh in the host or fabric8 pod, I cannot ping this IP and if I look at the config, it happens to match the gogs IP in here `http://fabric8.vagrant.f8/kubernetes/namespace/default/services/gogs`:

Here's a small config excerpt:
`
  portalIP: 172.30.233.200
  clusterIP: 172.30.233.200
`

Any idea why this won't work? How do we reconfigure this part to use the real IP or DNS?

**Comment by gunnypatel** [comment]
omniscient, were you able to find a resolution to this issue?  I'm having the same problem.

**Comment by omniscient** [comment]
@gunnypatel : No, I have abandoned the idea of running fabric8 on Windows+Vagrant...
