### ISSUE TITLE
Failed to create a application from fabric8-console - java.net.UnknownHostException: repo1.maven.org

### ISSUE THREAD

**Issue by chgangaraju** [fabric8io/fabric8#6367]
1. Setup fabric8 using [Minikube](http://fabric8.io/guide/getStarted/minikube.html)

2. Install fabric8  
 > gofabric8 version
  > gofabric8, version '0.4.64' (branch: 'master', revision: '7c295bd')
  > build date:       '20160912-08:15:02'
  > go version:       '1.6.3'

3. kubectl get pods

   > NAME                                                      READY     STATUS    RESTARTS   AGE
     exposecontroller-2168511310-er84n           1/1       Running            1          19h
     fabric8-akryx                                                 2/2       Running           2          19h
     fabric8-docker-registry-1624045968-plfqr    1/1       Running           1          19h
     fabric8-forge-1549357127-q1hju                  1/1       Running          2          19h
     gogs-395965268-3ks30                                1/1       Running          1          19h
     jenkins-3022353308-tuhyp                            1/1       Running         1          19h
     nexus-2830959440-u9el6                             1/1       Running          3          19h

4. gofabric8 deploy -y
5. go to dashboard and create application

>    org.apache.maven.wagon.TransferFailedException: Error transferring file: repo1.maven.org from http://repo1.maven.org/maven2/io/fabric8/archetypes/spring-boot-webmvc-archetype/2.2.168/spring-boot-webmvc-archetype-2.2.168.jar
	at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:174)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveArtifact(MavenDependencyResolver.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver_$$_javassist_03ce1b54-44c4-4c97-a5da-0f8c5f123508.resolveArtifact(MavenDependencyResolver_$$_javassist_03ce1b54-44c4-4c97-a5da-0f8c5f123508.java)
	at org.jboss.forge.addon.maven.projects.archetype.ui.AbstractArchetypeSelectionWizardStep.execute(AbstractArchetypeSelectionWizardStep.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.camel.commands.project.projecttypes.MicroserviceProjectArchetypeStep_$$_javassist_bf1da2e0-809c-4941-9dc2-39c86a8893c2.execute(MicroserviceProjectArchetypeStep_$$_javassist_bf1da2e0-809c-4941-9dc2-39c86a8893c2.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_b481dd28-0330-40ab-845c-5e6e0d9ab2bb.execute(CommandController_$$_javassist_b481dd28-0330-40ab-845c-5e6e0d9ab2bb.java)
	at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:335)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:279)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:275)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:600)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:561)
	at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.net.UnknownHostException: repo1.maven.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:131)
	... 96 more

**Comment by christian-posta** [comment]
So I've seen this before and it's usually to do with how the DNS is getting configured in your pods. BTW, what version of gofabric8/minikube are you using?

**Comment by chgangaraju** [comment]
➜  ~ minikube version
    minikube version: v0.8.0  

    ➜  ~ kubectl version
    Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

    ➜  ~ gofabric8 version
    gofabric8, version '0.4.64' (branch: 'master', revision: '7c295bd')
    build date: '20160912-08:15:02'
    go version: '1.6.3'

**Comment by jajansen** [comment]
Same here on 
```
$ minishift version
minishift version: 0.7.1
$ gofabric8 version
gofabric8, version 0.4.71 (branch: 'master', revision: 'e1844a8')
  build date:       '20160920-14:23:11'
  go version:       '1.6.3'
```
Running minishift on VirtualBox and Windows 10

**Comment by jstrachan** [comment]
I've never seen DNS issues with minishift/minikube and the good hypervisors (e.g. hyper-V / xhyve / kvm) though have seen issues with VirtualBox. I wonder if you could try with the recommended hypervisor for your OS?).

I wonder if you try to restart the VM? `minikube stop; minikube start` (or the same thing for minishift).

Though I prefer to use the best native hypervisor for your platform. To try out the native hypervisor:

run `minikube delete` (or `minishift delete`), then try
```
gofabric8 start
```
or for minishift
```
gofabric8 start --minishift
```

this should setup minikube / minishift with the native hypervisor for your OS - then see if you still get DNS issues.

**Comment by chgangaraju** [comment]
➜  ~ minikube stop; minikube start
     Stopping local Kubernetes cluster...
    Error stopping machine:  Machine "minikubeVM" is already stopped.
    Starting local Kubernetes cluster...
    Kubectl is now configured to use the cluster.

Facing the same issue. So deleted and started through gofabric8

    ➜  ~ minikube delete
     Deleting local Kubernetes cluster...
    Machine deleted.

     ➜   gofabric8 start
    Unable to download driver Driver install for linux not yet supported
    Downloading https://storage.googleapis.com/minikube/releases/v0.10.0/minikube-linux-amd64...Downloaded minikube
    kubectl is already available on your PATH                                                                                                                                                    
    Starting local Kubernetes cluster...

     Kubectl is now configured to use the cluster.
     Deploying fabric8 to your Kubernetes installation at https://192.168.99.100:8443 for domain vagrant.f8 in namespace default

    Loading fabric8 releases from maven repository:https://repo1.maven.org/maven2/                                                                                                               

     Starting fabric8 console deployment using 2.2.177...                         

Fabric 8 Started but still facing same issue.  `Caused by: java.net.UnknownHostException: repo1.maven.org`

**Comment by jstrachan** [comment]
I've no idea why DNS isn't working for you on linux. Do you have a HTTP proxy or something? Can you access it directly from outside of your VM?
```
curl https://repo1.maven.org/maven2/
```

**Comment by jajansen** [comment]
Maybe this ticket is related?
https://github.com/fabric8io/fabric8/issues/6085
These changes fix it for me

Op di 27 sep. 2016 om 12:39 schreef James Strachan <notifications@github.com

**Comment by shoaibjdev** [comment]
Hi,

Getting similar issue with a **gofabric8** setup on Mac

Caused by: java.net.UnknownHostException: nexus

Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file: nexus

org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.fabric8.archetypes:spring-boot-camel-xml-archetype:jar:2.2.191 from/to nexus-public-proxy-repo (http://nexus/content/groups/public/): Error transferring file: nexus

**Comment by Mistobaan** [comment]
I am getting this error too. seems that the problem comes from minikube
```
kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --hostport=8000 --port=8080
kubectl get pods --all-namespaces --show-all -a -L name | grep hello

kubectl exec ${POD_ID} curl repo1.maven.org
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (6) Could not resolve host: repo1.maven.org
```

**Comment by jstrachan** [comment]
I've seen it in the past where alpine or debian docker images have broken DNS. I wonder if you could try a pod that uses centos?
