### ISSUE TITLE
chat-letschat deployment

### ISSUE THREAD

**Issue by enxebre** [fabric8io/fabric8#6400]
When I deploy  chat-letschat

I got:
```
kubectl logs letschat-4166292497-5bcu2 letschat

> lets-chat@0.4.0 prestart /usr/src/app
> migroose

using default username: ${HUBOT_USERNAME}
Lets create a default user for id ${hubot_username} and email: fabric8-admin@googlegroups.com
Count not find user: ${HUBOT_USERNAME} so cannot create any default rooms
{ [ValidationError: User validation failed]
  stack: 'Error\n    at MongooseError.ValidationError (/usr/src/app/node_modules/mongoose/lib/error/validation.js:22:16)\n    at model.Document.invalidate (/usr/src/app/node_modules/mongoose/lib/document.js:1162:32)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1037:16\n    at validate (/usr/src/app/node_modules/mongoose/lib/schematype.js:651:7)\n    at /usr/src/app/node_modules/mongoose/lib/schematype.js:679:9\n    at Array.forEach (native)\n    at SchemaString.SchemaType.doValidate (/usr/src/app/node_modules/mongoose/lib/schematype.js:656:19)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1035:9\n    at process._tickCallback (node.js:355:11)',
  message: 'User validation failed',
  name: 'ValidationError',
  errors: 
   { username: 
      { [ValidatorError: Path `username` is invalid (${hubot_username}).]
        properties: [Object],
        stack: 'Error\n    at MongooseError.ValidatorError (/usr/src/app/node_modules/mongoose/lib/error/validator.js:25:16)\n    at validate (/usr/src/app/node_modules/mongoose/lib/schematype.js:650:13)\n    at /usr/src/app/node_modules/mongoose/lib/schematype.js:679:9\n    at Array.forEach (native)\n    at SchemaString.SchemaType.doValidate (/usr/src/app/node_modules/mongoose/lib/schematype.js:656:19)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1035:9\n    at process._tickCallback (node.js:355:11)',
        message: 'Path `username` is invalid (${hubot_username}).',
        name: 'ValidatorError',
        kind: 'regexp',
        path: 'username',
        value: '${hubot_username}' } } }
Error
    at MongooseError.ValidationError (/usr/src/app/node_modules/mongoose/lib/error/validation.js:22:16)
    at model.Document.invalidate (/usr/src/app/node_modules/mongoose/lib/document.js:1162:32)
    at /usr/src/app/node_modules/mongoose/lib/document.js:1037:16
    at validate (/usr/src/app/node_modules/mongoose/lib/schematype.js:651:7)
    at /usr/src/app/node_modules/mongoose/lib/schematype.js:679:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/usr/src/app/node_modules/mongoose/lib/schematype.js:656:19)
    at /usr/src/app/node_modules/mongoose/lib/document.js:1035:9
    at process._tickCallback (node.js:355:11)
/usr/src/app/app/models/user.js:325
                        console.error(message);
                                      ^
ReferenceError: message is not defined
    at EventEmitter.<anonymous> (/usr/src/app/app/models/user.js:325:39)
    at EventEmitter.<anonymous> (/usr/src/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:174:48)
    at EventEmitter.emit (events.js:107:17)
    at Promise.safeEmit (/usr/src/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.reject (/usr/src/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:109:15)
    at Promise.error (/usr/src/app/node_modules/mongoose/lib/promise.js:94:15)
    at Promise.resolve (/usr/src/app/node_modules/mongoose/lib/promise.js:112:24)
    at /usr/src/app/node_modules/mongoose/lib/document.js:1578:39
    at handleError (/usr/src/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:40:22)
    at _next (/usr/src/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:46:22)
    at EventEmitter.fnWrapper (/usr/src/app/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:171:15)
    at EventEmitter.<anonymous> (/usr/src/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:174:48)
    at EventEmitter.emit (events.js:107:17)
    at Promise.safeEmit (/usr/src/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
    at Promise.reject (/usr/src/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:109:15)
    at complete (/usr/src/app/node_modules/mongoose/lib/document.js:1055:15)

npm ERR! Linux 4.7.0-coreos
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.4.0 prestart: `migroose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lets-chat@0.4.0 prestart script 'migroose'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     migroose
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.7.0-coreos
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.3
npm ERR! path npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, open 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: 'npm-debug.log.7da2e9feb6af80ea1c45d89105a542fd' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

So I change values on deployment to:
```
            - name: LETSCHAT_HUBOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: letschat
                  key: hubot-password
            - name: LETSCHAT_HUBOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: letschat
                  key: hubot-username
```

So delpoyment succeeded and I can access to the letschat UI but still not getting jenkins build notifications as hubot-letschat logs says:
```
t's Chat token is empty; lets query again in 5 seconds....
parse error: Invalid numeric literal at line 1, column 4
Let's Chat token is: 
Let's Chat token is empty; lets query again in 5 seconds....
```

As https://github.com/fabric8io/hubot-lets-chat/blob/master/start.sh needs AUTH_HEADER=`echo $LETSCHAT_HUBOT_USERNAME:$LETSCHAT_HUBOT_PASSWORD | base64`
 but those variables are not set inside the container.
If I set the variables so It can get the letschat token I get:
```
Cannot load adapter lets-chat - TypeError: Cannot call method 'split' of undefined
```

**Comment by rawlingsj** [comment]
I think I know what this is - we now supply this information as a configmap.  In fact for lets chat we ought to use a secret.

**Comment by rawlingsj** [comment]
This will be available in the next release however I've raised fabric8io/fabric8/issues/6402 to update the letschat image and include persistence to keep data.  

We'll also make sure hubot + jenkins pipelines approval are working with the recent upgrades we've made.
