### ISSUE TITLE
Integration tests fails even if the pod is ready

### ISSUE THREAD

**Issue by abouchama** [fabric8io/fabric8#6473]
I used openshift origin 1.3.1 cluster (minishift 0.9.0) to create fabric8 cd-pipeline app. 
When i fabric8:import my camel project (spring-boot-camel-xml-archetype - 2.2.177 - Kubernetes mode), the job start and the app is deployed in testing env but the integration test failed even if the pod is ready & running:

The full log is available here: https://gist.github.com/abouchama/b29e93bccf49f1af597559a94cbab384

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.fabric8.KubernetesIntegrationKT
[32mInitializing Session:3880b0ea-3027-4803-8e97-65cab98c447a[m
[32mUsing Kubernetes at: https://kubernetes.default/[m
[32mCreating kubernetes resources inside namespace: default-testing[m
if you use OpenShift then type this switch namespaces:     oc project default-testing
if you use kubernetes then type this to switch namespaces: kubectl namespace default-testing
04:19:54.529 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.4.Final
[32mApplying kubernetes configuration from: file:/home/jenkins/workspace/workspace/camel-fabric8-10/target/classes/META-INF/fabric8/openshift.yml[m
[32mAdapting resources to pull images from registry: 172.30.39.135:80[m
[32mApplying service:camel-fabric8-10[m
04:19:56.857 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating a Service from 3880b0ea-3027-4803-8e97-65cab98c447a namespace default-testing name camel-fabric8-10
04:19:56.918 [main] INFO  io.fabric8.kubernetes.api.Controller - Created Service: Service(apiVersion=v1, kind=Service, metadata=ObjectMeta(annotations={fabric8.io/build-id=1, fabric8.io/build-url=http://192.168.42.111:31017/job/camel-fabric8-10/1, fabric8.io/git-branch=camel-fabric8-10-1.0.1, fabric8.io/git-commit=5db8c570c9e95e81ed381234b5cebd82f81cc692, fabric8.io/git-url=http://192.168.42.111:31769/gogsadmin/camel-fabric8-10/commit/5db8c570c9e95e81ed381234b5cebd82f81cc692, fabric8.io/iconUrl=data:text/plain;charset=UTF-8;base64,cm91dGVzLnhtbAo=, prometheus.io/port=9779, prometheus.io/scrape=true}, creationTimestamp=2016-10-20T04:19:56Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={expose=true, group=io.fabric8, project=camel-fabric8-10, provider=fabric8, version=1.0.1}, name=camel-fabric8-10, namespace=default-testing, ownerReferences=[], resourceVersion=16726, selfLink=/api/v1/namespaces/default-testing/services/camel-fabric8-10, uid=7544ade9-967c-11e6-8ee6-cefb9d2751d6, additionalProperties={}), spec=ServiceSpec(clusterIP=172.30.109.173, deprecatedPublicIPs=[], externalIPs=[], loadBalancerIP=null, loadBalancerSourceRanges=[], portalIP=172.30.109.173, ports=[ServicePort(name=http, nodePort=32766, port=80, protocol=TCP, targetPort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={})], selector={group=io.fabric8, project=camel-fabric8-10, provider=fabric8}, sessionAffinity=None, type=LoadBalancer, additionalProperties={}), status=ServiceStatus(loadBalancer=LoadBalancerStatus(ingress=[], additionalProperties={}), additionalProperties={}), additionalProperties={})
[32mApplying route for:camel-fabric8-10[m
04:19:57.030 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating Route default-testing:camel-fabric8-10 host: camel-fabric8-10.default-testing.vagrant.f8
[32mApplying DeploymentConfig.[m
04:19:57.133 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating a DeploymentConfig from 3880b0ea-3027-4803-8e97-65cab98c447a namespace default-testing name camel-fabric8-10
04:19:57.247 [main] INFO  io.fabric8.kubernetes.api.Controller - Created DeploymentConfig: DeploymentConfig(apiVersion=v1, kind=DeploymentConfig, metadata=ObjectMeta(annotations={fabric8.io/build-id=1, fabric8.io/build-url=http://192.168.42.111:31017/job/camel-fabric8-10/1, fabric8.io/docs-url=dav:http://content-repository/sites/io.fabric8/camel-fabric8-10/1.0.1, fabric8.io/git-branch=camel-fabric8-10-1.0.1, fabric8.io/git-commit=5db8c570c9e95e81ed381234b5cebd82f81cc692, fabric8.io/git-url=http://192.168.42.111:31769/gogsadmin/camel-fabric8-10/commit/5db8c570c9e95e81ed381234b5cebd82f81cc692, fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-fabric8-10&var-version=1.0.1}, creationTimestamp=2016-10-20T04:19:57Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=1, labels={group=io.fabric8, project=camel-fabric8-10, provider=fabric8, version=1.0.1}, name=camel-fabric8-10, namespace=default-testing, ownerReferences=[], resourceVersion=16735, selfLink=/oapi/v1/namespaces/default-testing/deploymentconfigs/camel-fabric8-10, uid=756cf09e-967c-11e6-8ee6-cefb9d2751d6, additionalProperties={}), spec=DeploymentConfigSpec(minReadySeconds=null, paused=null, replicas=1, revisionHistoryLimit=null, selector={group=io.fabric8, project=camel-fabric8-10, provider=fabric8}, strategy=DeploymentStrategy(annotations=null, customParams=null, labels=null, recreateParams=null, resources=ResourceRequirements(limits=null, requests=null, additionalProperties={}), rollingParams=RollingDeploymentStrategyParams(intervalSeconds=1, maxSurge=IntOrString(IntVal=null, Kind=null, StrVal=25%, additionalProperties={}), maxUnavailable=IntOrString(IntVal=null, Kind=null, StrVal=25%, additionalProperties={}), post=null, pre=null, timeoutSeconds=10800, updatePercent=null, updatePeriodSeconds=1, additionalProperties={}), type=Rolling, additionalProperties={}), template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/build-id=1, fabric8.io/build-url=http://192.168.42.111:31017/job/camel-fabric8-10/1, fabric8.io/docs-url=dav:http://content-repository/sites/io.fabric8/camel-fabric8-10/1.0.1, fabric8.io/git-branch=camel-fabric8-10-1.0.1, fabric8.io/git-commit=5db8c570c9e95e81ed381234b5cebd82f81cc692, fabric8.io/git-url=http://192.168.42.111:31769/gogsadmin/camel-fabric8-10/commit/5db8c570c9e95e81ed381234b5cebd82f81cc692, fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-fabric8-10&var-version=1.0.1}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={group=io.fabric8, project=camel-fabric8-10, provider=fabric8, version=1.0.1}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=v1, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={})], image=172.30.39.135:80/fabric8/camel-fabric8-10:1.0.1, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=Probe(exec=null, failureThreshold=3, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8081, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=180, periodSeconds=10, successThreshold=1, tcpSocket=null, timeoutSeconds=1, additionalProperties={}), name=spring-boot, ports=[ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=9779, hostIP=null, hostPort=null, name=prometheus, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=TCP, additionalProperties={})], readinessProbe=Probe(exec=null, failureThreshold=3, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8081, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=10, periodSeconds=10, successThreshold=1, tcpSocket=null, timeoutSeconds=1, additionalProperties={}), resources=ResourceRequirements(limits={cpu=Quantity(amount=1, format=null, additionalProperties={}), memory=Quantity(amount=256Mi, format=null, additionalProperties={})}, requests={cpu=Quantity(amount=200m, format=null, additionalProperties={}), memory=Quantity(amount=256Mi, format=null, additionalProperties={})}, additionalProperties={}), securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=/dev/termination-log, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=ClusterFirst, host=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=Always, securityContext=PodSecurityContext(fsGroup=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, supplementalGroups=[], additionalProperties={}), serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=30, volumes=[], additionalProperties={}), additionalProperties={}), test=false, triggers=[DeploymentTriggerPolicy(imageChangeParams=null, type=ConfigChange, additionalProperties={})], additionalProperties={}), status=DeploymentConfigStatus(availableReplicas=null, details=null, latestVersion=null, observedGeneration=null, replicas=null, unavailableReplicas=null, updatedReplicas=null, additionalProperties={}), additionalProperties={})
[33mWaiting for container:deployment.[m
[33mWaiting for container:spring-boot.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:spring-boot.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:spring-boot.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:spring-boot.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:spring-boot.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:spring-boot.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
[33mWaiting for container:deployment.[m
sh-4.2# exit
exit
[31mTimed out waiting for pods/services![m
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 305.285 sec <<< FAILURE! - in io.fabric8.KubernetesIntegrationKT
io.fabric8.KubernetesIntegrationKT  Time elapsed: 305.284 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to apply kubernetes configuration.
    at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:163)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
    at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
    at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
    at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
    at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.IllegalStateException: Failed to apply kubernetes configuration.
    at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:151)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
    at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
    at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
    at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
    at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
    at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error: 
  KubernetesIntegrationKT.io.fabric8.KubernetesIntegrationKT ? Runtime java.lang...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default-cli) @ camel-fabric8-10 ---
[INFO] Failsafe report directory: /home/jenkins/workspace/workspace/camel-fabric8-10/target/failsafe-reports
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:07 min
[INFO] Finished at: 2016-10-20T04:24:58+00:00
[INFO] Final Memory: 25M/270M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify (default-cli) on project camel-fabric8-10: There are test failures.
[ERROR] 
```

**Comment by rawlingsj** [comment]
Are there any other pods failing to start in that test environment?

I noticed recently where I recreated a namespace I'm sure I saw a failing pod trying to start that was from the old namespace, then the integration test for the new pod failed even though its was running.

**Comment by abouchama** [comment]
Hi James,

I have no pod in failing status in default-testing, or default (fabric8 pods).

When i run the job, i see the following pods running and terminating after the job was finished:

```
oc get pods -w

NAME           READY     STATUS    RESTARTS   AGE
3aa3015683af   0/1       Pending   0          0s
3aa3015683af   0/1       Pending   0         0s
3aa3015683af   0/1       ContainerCreating   0         0s
3aa3015683af   1/1       Running   0         2s
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   0/1       Pending   0         0s
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   0/1       Pending   0         0s
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   0/1       ContainerCreating   0         0s
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   1/1       Running   0         5s
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   1/1       Terminating   0         5m
3aa3015683af   1/1       Terminating   0         5m
3aa3015683af   0/1       Terminating   0         5m
3aa3015683af   0/1       Terminating   0         5m
3aa3015683af   0/1       Terminating   0         5m
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   0/1       Terminating   0         6m
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   0/1       Terminating   0         6m
buildpod-1f593cb9-209d-4e59-8e2f-af754021e8ee   0/1       Terminating   0         6m

```

**Comment by jstrachan** [comment]
@abouchama that looks like you are looking in the current namespace - the development namespace, where builds run. 

Try look in the default-testing namespace instead?
```
oc get pods -w --namespace default-testing
```

Or use the fabric8 console and click on the "Testing" environment then look at the deployments & pods etc?

**Comment by abouchama** [comment]
@jstrachan 

Here's the output:
```
$ oc get pods -w --namespace default-testing
NAME                      READY     STATUS    RESTARTS   AGE
camel-fabric8-9-1-2pjty   1/1       Running   0          18h
```

**Comment by abouchama** [comment]
By deleting the namespace` default-testing`, before running the cd-pipeline, everything works as expected.

I think it's related to updating DC in an existing namespace.

**Comment by RobinsChens** [comment]
@abouchama I have got the same problem ,do you have solved it ? If you did,please tell me

**Comment by RobinsChens** [comment]
you will see something from kube-apiserever log from your k8s master, and I solved this problem after  restarting service kube-apiserver

**Comment by abouchama** [comment]
@RobinsChens, the problem is fixed by deleting the 3 namespaces created before adding a new application and running the cd-pipeline:


```
oc delete project default-production
oc delete project default-staging
oc delete project default-testing
```

**Comment by davsclaus** [comment]
closing as assume working, reopen or log a new ticket
