### ISSUE TITLE
error building nodejs app

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8#6527]
following the latest release http://central.maven.org/maven2/io/fabric8/platform/packages/fabric8-platform/2.4.1/

we are getting an error in the nodejs pipeline, I suspect this is going to be the same for all non java apps

```
[Pipeline] buildImage
Creating tar from path: ..Building image:nodejs from path:..
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.fabric8.kubernetes.pipeline.BuildImageStepExecution$1.call(BuildImageStepExecution.java:106)
	at io.fabric8.kubernetes.pipeline.BuildImageStepExecution$1.call(BuildImageStepExecution.java:91)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at io.fabric8.kubernetes.pipeline.BuildImageStepExecution.run(BuildImageStepExecution.java:91)
	at io.fabric8.kubernetes.pipeline.BuildImageStepExecution.run(BuildImageStepExecution.java:75)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:40)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:184)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:126)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:16)
	at io.fabric8.kubernetes.pipeline.Kubernetes$BuildImage.fromPath(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:249)
	at io.fabric8.kubernetes.pipeline.Kubernetes.node(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:33)
	at io.fabric8.kubernetes.pipeline.Kubernetes$BuildImage.fromPath(jar:file:/var/jenkins_home/plugins/kubernetes-pipeline-steps/WEB-INF/lib/kubernetes-pipeline-steps.jar!/io/fabric8/kubernetes/pipeline/Kubernetes.groovy:248)
	at performCanaryRelease.call(/var/jenkins_home/jobs/nodejs/builds/1/libs/github.com/fabric8io/fabric8-pipeline-library/vars/performCanaryRelease.groovy:20)
	at WorkflowScript.run(WorkflowScript:17)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:48)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:76)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:324)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:236)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:224)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:63)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by rawlingsj** [comment]
I think we've run into issues where the [kubernetes-pipeline-plugin build image](https://github.com/jenkinsci/kubernetes-pipeline-plugin/tree/master/kubernetes-steps#building-tagging-and-pushing) can't find the dockerfile that we create in the pipeline.  

We also had a few other issues:

- the namespace which we need to get from a groovy function now that the kuberenetes-plugin config isn't creating the env vars it used to https://github.com/rawlingsj/fabric8-pipeline-library/commit/2eab76d69a518a49ca09eb54dee25c5a3549a043
- a bug where the version wasn't being retrieved correctly https://github.com/rawlingsj/fabric8-pipeline-library/commit/084d5cf118e9a9c82c0477708842c423abb80636

In order to fix the problems I had to change from using the kubernetes-pipelines-plugin build image approach and instead use a client builder image and run the native docker client commands.  This is because the jenkins job console doesn't flush until the job has finished which make investigating issues in kubernetes-pipelines-plugin very hard.

To address this I've taken @iocanel approach and created a [clientsNode](https://github.com/rawlingsj/fabric8-pipeline-library/blob/master/vars/clientsNode.groovy) (we can rename this) and I'll update our Jenkinsfiles to use it https://github.com/rawlingsj/fabric8-jenkinsfile-library/commit/eadc964aa1e32858f659b177df3f986130e7cb5e.  

Then we can run the docker commands that people are familiar with https://github.com/rawlingsj/fabric8-pipeline-library/blob/master/vars/performCanaryRelease.groovy#L26-L31 and it was easy to see what the errors were.

This means non java pipelines are working again so I'm going to release this however we can revisit the use of the clientNode vs kubernetes-pipelines-plugin build image tomorrow.

Bit more testing and I should be able to merge shortly.
