### ISSUE TITLE
at okio.Okio$3.newTimeoutException

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8#6537]
[INFO] F8: Starting Build ipservice-s2i
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 h
[INFO] Finished at: 2016-11-10T11:48:06+00:00
[INFO] Final Memory: 49M/494M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.92:build (default) on project ipservice: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.92:build failed: An error has occurred. timeout: Connection reset -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.92:build (default) on project ipservice: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.92:build failed: An error has occurred.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by jimmidyson** [comment]
Your build took `01:03 h`. Looks like the timeout should be configurable via plugin configuration - @rhuss?

**Comment by rhuss** [comment]
@RobinsChens which kind of build are you using ? Direct Docker builds or OpenShift S2I builds ? Could you provide a bit more of context information ? Also whether you expect the build to take that long.

**Comment by RobinsChens** [comment]
@rhuss i use OpenShift S2I builds
