### ISSUE TITLE
arquillian test is now crazy slow

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#6575]
it just took me 16 minutes to run a simple system test.

* used minikube to create a `microservice` project; first time the build worked great
* then updated the source code to trigger a rebuild
* it seems to now take about 15 minutes to delete a Deployment. 

Here's the log of arquillian
```
Running org.example.KubernetesIntegrationKT
[32mInitializing Session:4958d645-b51f-46fe-a389-f3722b8c3832[m
[32mUsing Kubernetes at: https://kubernetes.default/[m
[32mCreating kubernetes resources inside namespace: default-testing[m
if you use OpenShift then type this switch namespaces:     oc project default-testing
if you use kubernetes then type this to switch namespaces: kubectl namespace default-testing
17:56:07.075 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.4.Final
[32mApplying kubernetes configuration from: file:/home/jenkins/workspace/thingy1/target/classes/META-INF/fabric8/kubernetes.yml[m
[32mAdapting resources to pull images from registry: 10.0.0.27:80[m
[32mApplying service:thingy1[m
17:56:27.549 [main] INFO  io.fabric8.kubernetes.api.Controller - Deleting Service: thingy1
17:56:27.596 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating a Service from 4958d645-b51f-46fe-a389-f3722b8c3832 namespace default-testing name thingy1
17:56:27.683 [main] INFO  io.fabric8.kubernetes.api.Controller - Created Service: Service(apiVersion=v1, kind=Service, metadata=ObjectMeta(annotations={fabric8.io/git-branch=thingy1-1.0.2, fabric8.io/git-commit=01c9cabf4b984ee260a804919248b63442756a20, prometheus.io/port=9779, prometheus.io/scrape=true}, creationTimestamp=2016-11-21T17:56:27Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={expose=true, group=org.example, project=thingy1, provider=fabric8, version=1.0.2}, name=thingy1, namespace=default-testing, ownerReferences=[], resourceVersion=230191, selfLink=/api/v1/namespaces/default-testing/services/thingy1, uid=d3424a18-b013-11e6-b74d-76a810bcc560, additionalProperties={}), spec=ServiceSpec(clusterIP=10.0.0.247, deprecatedPublicIPs=[], externalIPs=[], loadBalancerIP=null, loadBalancerSourceRanges=[], portalIP=null, ports=[ServicePort(name=http, nodePort=32353, port=80, protocol=TCP, targetPort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={})], selector={group=org.example, project=thingy1, provider=fabric8}, sessionAffinity=None, type=LoadBalancer, additionalProperties={}), status=ServiceStatus(loadBalancer=LoadBalancerStatus(ingress=[], additionalProperties={}), additionalProperties={}), additionalProperties={})
[32mApplying ConfigMap:thingy1[m
17:56:27.719 [main] INFO  io.fabric8.kubernetes.api.Controller - Deleting ConfigMap: thingy1
17:56:27.744 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating a ConfigMap from 4958d645-b51f-46fe-a389-f3722b8c3832 namespace default-testing name thingy1
17:56:27.774 [main] INFO  io.fabric8.kubernetes.api.Controller - Created ConfigMap: ConfigMap(apiVersion=v1, data={application.properties=# spring application proeprties file
welcome = Hello from Kubernetes ConfigMap!!!
dummy = some value
}, kind=ConfigMap, metadata=ObjectMeta(annotations=null, creationTimestamp=2016-11-21T17:56:27Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={group=org.example, project=thingy1, provider=fabric8, version=1.0.2}, name=thingy1, namespace=default-testing, ownerReferences=[], resourceVersion=230196, selfLink=/api/v1/namespaces/default-testing/configmaps/thingy1, uid=d35367ef-b013-11e6-b74d-76a810bcc560, additionalProperties={}), additionalProperties={})
[32mApplying Deployment.[m
17:56:27.958 [main] INFO  io.fabric8.kubernetes.api.Controller - Deleting Deployment: thingy1
18:11:43.038 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating a Deployment from 4958d645-b51f-46fe-a389-f3722b8c3832 namespace default-testing name thingy1
```

**Comment by rawlingsj** [comment]
And it looks like it timed out on minishift, following the same reproducer steps:

```
55 	Nov 21, 2016 6:01:37 PM org.jboss.arquillian.container.test.impl.RunModeUtils isRunAsClient
56 	WARNING: The test method "org.example.KubernetesIntegrationKT testAppProvisionsRunningPods" will run on the client side - there is no running deployment yet. Please use the annotation @RunAsClient
57 	sh-4.2# exit
58 	exit
59 	Nov 21, 2016 6:06:38 PM org.jboss.arquillian.container.test.impl.RunModeUtils isRunAsClient
60 	WARNING: The test method "org.example.KubernetesIntegrationKT testAppProvisionsRunningPods" will run on the client side - there is no running deployment yet. Please use the annotation @RunAsClient
61 	18:06:38.271 [OkHttp https://kubernetes.default/api/v1/namespaces/default-testing/pods?labelSelector=group%3Dorg.example,project%3Dtest,provider%3Dfabric8&resourceVersion=2219&watch=true WebSocket Close Reply] INFO  i.f.k.assertions.support.PodWatcher - onClose: null
62 	Nov 21, 2016 6:06:38 PM org.jboss.arquillian.container.test.impl.RunModeUtils isRunAsClient
63 	WARNING: The test method "org.example.KubernetesIntegrationKT testAppProvisionsRunningPods" will run on the client side - there is no running deployment yet. Please use the annotation @RunAsClient
64 	Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 339.251 sec <<< FAILURE! - in org.example.KubernetesIntegrationKT
65 	testAppProvisionsRunningPods(org.example.KubernetesIntegrationKT)  Time elapsed: 301.535 sec  <<< FAILURE!
66 	java.lang.AssertionError: DeploymentConfig test did not have a pod become Ready within 300000 millis
67 		at io.fabric8.kubernetes.assertions.support.PodWatcher.waitForPodReady(PodWatcher.java:198)
68 		at io.fabric8.kubernetes.assertions.PodSelectionAssert.isPodReadyForPeriod(PodSelectionAssert.java:122)
69 		at io.fabric8.kubernetes.assertions.PodSelectionAssert.isPodReadyForPeriod(PodSelectionAssert.java:106)
70 		at org.example.KubernetesIntegrationKT.testAppProvisionsRunningPods(KubernetesIntegrationKT.java:34)
71 	

```

**Comment by jstrachan** [comment]
think this is fixed now
