### ISSUE TITLE
Jenkins build failed to fetch sources from existing git repository

### ISSUE THREAD

**Issue by shamoh** [fabric8io/fabric8#6646]
Hi.
I'm hosting project sources in Github (https://github.com/shamoh/orbis). I'm using SSH Github URL: git@github.com:shamoh/orbis.git. I have created new [deploy key](https://developer.github.com/guides/managing-deploy-keys/#deploy-keys) with read/write access on the project. The deploy key is configured as Fabric8 Secret. Facbric8 itself can checkout sources and it even committed Jenkinsfile and fabric8.yml, see the [commit](https://github.com/shamoh/orbis/commit/b665f8d587f3ea0ae678d20b5b2eb31b466a0d99).

But it seems that Jenins does not use the Secret, the project git fetch fails:

```
Started by user anonymous
 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > /usr/bin/git config remote.origin.url git@github.com:shamoh/orbis.git # timeout=10
Fetching upstream changes from git@github.com:shamoh/orbis.git
 > /usr/bin/git --version # timeout=10
 > /usr/bin/git fetch --tags --progress git@github.com:shamoh/orbis.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:shamoh/orbis.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:797)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1051)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1082)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:108)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:57)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:214)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git fetch --tags --progress git@github.com:shamoh/orbis.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1752)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1495)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:64)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:315)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:795)
	... 8 more
ERROR: null
Finished: FAILURE
```

Version of Fabric8 is 0.4.112. I'm running it on GCE.

Thanks,
Libor

**Comment by basu76** [comment]
Hi Shamoh - were you able to work around this?

**Comment by shamoh** [comment]
Hi. No, I quit experimenting with Fabrick8 then.
