### ISSUE TITLE
snapshot of fabric8-platform fails with current versions of kubernetes-client + fabric8

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8#6681]
the integration test in a pipeline fails with this:

```
ava.lang.RuntimeException: java.lang.NullPointerException
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.NullPointerException: null
	at io.fabric8.arquillian.utils.Util.displaySessionStatus(Util.java:57)
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by jstrachan** [comment]
just testing here - think its just we've not run fabric8-maven-dependencies to update the fmp releases in the quickstarts...

**Comment by rawlingsj** [comment]
Cool - will add that into the pipeline now

**Comment by jstrachan** [comment]
now I seem to get an infinite loop of this
```
09:12:28.982 [pool-2-thread-1] ERROR i.f.k.c.d.i.ReplicationControllerOperationsImpl - Error while waiting for ReplicaSet to be scaled.
io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:199)
	at io.fabric8.kubernetes.client.dsl.internal.ReplicaSetOperationsImpl$1.run(ReplicaSetOperationsImpl.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:12:29.087 [pool-2-thread-1] ERROR i.f.k.c.d.i.ReplicationControllerOperationsImpl - Error while waiting for ReplicaSet to be scaled.
io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:199)
	at io.fabric8.kubernetes.client.dsl.internal.ReplicaSetOperationsImpl$1.run(ReplicaSetOperationsImpl.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

looks like we need a fix/workaround in kube client

**Comment by jstrachan** [comment]
if it helps here's the full output of the arquillian test in the jenkins pipeline (for the `microservice` quickstart)
```
mvn org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test -Dfabric8.environment=Testing '-Dit.test=*KT' -DfailIfNoTests=null org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: Spring-Boot :: WebMVC 1.0.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:integration-test (default-cli) @ mymicro ---
[INFO] Failsafe report directory: /home/jenkins/workspace/mymicro/target/failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.example.KubernetesIntegrationKT
[32mInitializing Session:9e437e71-2caa-4144-8cc9-3a7f19a8ad38[m
[32mUsing Kubernetes at: https://kubernetes.default/[m
[32mCreating kubernetes resources inside namespace: default-testing[m
if you use OpenShift then type this switch namespaces:     oc project default-testing
if you use kubernetes then type this to switch namespaces: kubectl namespace default-testing
09:05:03.612 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.4.Final
[32mApplying kubernetes configuration from: file:/home/jenkins/workspace/mymicro/target/classes/META-INF/fabric8/kubernetes.yml[m
[32mAdapting resources to pull images from registry: 10.0.0.8:80[m
[32mApplying service:mymicro[m
09:05:23.718 [main] INFO  io.fabric8.kubernetes.api.Controller - Deleting Service: mymicro
09:05:23.790 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating a Service from 9e437e71-2caa-4144-8cc9-3a7f19a8ad38 namespace default-testing name mymicro
09:05:23.853 [main] INFO  io.fabric8.kubernetes.api.Controller - Created Service: Service(apiVersion=v1, kind=Service, metadata=ObjectMeta(annotations={fabric8.io/git-branch=mymicro-1.0.3, fabric8.io/git-commit=d9ea984c3c2633f2ef9c4e9fe34eb0f4333fe39a, prometheus.io/port=9779, prometheus.io/scrape=true}, clusterName=null, creationTimestamp=2017-01-05T09:05:23Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={expose=true, group=org.example, project=mymicro, provider=fabric8, version=1.0.3}, name=mymicro, namespace=default-testing, ownerReferences=[], resourceVersion=5606, selfLink=/api/v1/namespaces/default-testing/services/mymicro, uid=1788401d-d326-11e6-8a94-469b969c79fb, additionalProperties={}), spec=ServiceSpec(clusterIP=10.0.0.135, deprecatedPublicIPs=[], externalIPs=[], externalName=null, loadBalancerIP=null, loadBalancerSourceRanges=[], ports=[ServicePort(name=http, nodePort=null, port=80, protocol=TCP, targetPort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={})], selector={group=org.example, project=mymicro, provider=fabric8}, sessionAffinity=None, type=ClusterIP, additionalProperties={}), status=ServiceStatus(loadBalancer=LoadBalancerStatus(ingress=[], additionalProperties={}), additionalProperties={}), additionalProperties={})
[32mApplying ConfigMap:mymicro[m
09:05:23.971 [main] INFO  io.fabric8.kubernetes.api.Controller - Deleting ConfigMap: mymicro
09:05:24.006 [main] INFO  io.fabric8.kubernetes.api.Controller - Creating a ConfigMap from 9e437e71-2caa-4144-8cc9-3a7f19a8ad38 namespace default-testing name mymicro
09:05:24.028 [main] INFO  io.fabric8.kubernetes.api.Controller - Created ConfigMap: ConfigMap(apiVersion=v1, data={application.properties=# spring application properties file
welcome = Hello from Kubernetes ConfigMap!!!
dummy = some value
}, kind=ConfigMap, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=2017-01-05T09:05:24Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={group=org.example, project=mymicro, provider=fabric8, version=1.0.3}, name=mymicro, namespace=default-testing, ownerReferences=[], resourceVersion=5613, selfLink=/api/v1/namespaces/default-testing/configmaps/mymicro, uid=17a2f4d3-d326-11e6-8a94-469b969c79fb, additionalProperties={}), additionalProperties={})
[32mApplying Deployment.[m
09:05:24.257 [main] INFO  io.fabric8.kubernetes.api.Controller - Deleting Deployment: mymicro
09:05:33.537 [pool-2-thread-1] ERROR i.f.k.c.d.i.ReplicationControllerOperationsImpl - Error while waiting for ReplicaSet to be scaled.
io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:199)
	at io.fabric8.kubernetes.client.dsl.internal.ReplicaSetOperationsImpl$1.run(ReplicaSetOperationsImpl.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:05:33.645 [pool-2-thread-1] ERROR i.f.k.c.d.i.ReplicationControllerOperationsImpl - Error while waiting for ReplicaSet to be scaled.
io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:199)
	at io.fabric8.kubernetes.client.dsl.internal.ReplicaSetOperationsImpl$1.run(ReplicaSetOperationsImpl.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
09:05:33.766 [pool-2-thread-1] ERROR i.f.k.c.d.i.ReplicationControllerOperationsImpl - Error while waiting for ReplicaSet to be scaled.
io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:199)
	at io.fabric8.kubernetes.client.dsl.internal.ReplicaSetOperationsImpl$1.run(ReplicaSetOperationsImpl.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
then that exception is repeated forever for 6Mb of logs until I killed the job

**Comment by rawlingsj** [comment]
This seems to be all fixed now.
