### ISSUE TITLE
Build has recently broken, global issue on new provisioning (2.4.3, 2.4.6)

### ISSUE THREAD

**Issue by jeremy-wilson** [fabric8io/fabric8#6730]
In the last few days, something happened to the pipeline, which is causing an error across all projects. We are unable to build anything.

We were on version 2.4.3 and the issue started occuring there after we provisioned a new fabric8 instance.

We upgraded to 2.4.6 and the exact problem is still there.

Based on the output, is this a pipeline issue with https://github.com/fabric8io/fabric8-pipeline-library.git? It looks like it is pulling from the master branch of the fabric8 repo, but you guys develop off head, so is there a problem here?

Not sure if that is an issue or if it is something else. But 2.4.3 and 2.4.6 are affected. Seems to be a global issue if you provision a new instance of fabric8. A BC break somewhere?

Here is the output while trying to build the micro service starter.

```
Started by user anonymous

Cloning the remote Git repository

Cloning repository http://gogs/gogsadmin/appms.git

> /usr/bin/git init /var/jenkins_home/workspace/appms@script # timeout=10

Fetching upstream changes from http://gogs/gogsadmin/appms.git

> /usr/bin/git --version # timeout=10

> /usr/bin/git fetch --tags --progress http://gogs/gogsadmin/appms.git +refs/heads/*:refs/remotes/origin/*

> /usr/bin/git config remote.origin.url http://gogs/gogsadmin/appms.git # timeout=10

> /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10

> /usr/bin/git config remote.origin.url http://gogs/gogsadmin/appms.git # timeout=10

Fetching upstream changes from http://gogs/gogsadmin/appms.git

> /usr/bin/git fetch --tags --progress http://gogs/gogsadmin/appms.git +refs/heads/*:refs/remotes/origin/*

> /usr/bin/git rev-parse refs/remotes/origin/master^{commit} # timeout=10

> /usr/bin/git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10

Checking out Revision 5f2e4eef121baa993a58b0a676fbc4843ac294b7 (refs/remotes/origin/master)

> /usr/bin/git config core.sparsecheckout # timeout=10

> /usr/bin/git checkout -f 5f2e4eef121baa993a58b0a676fbc4843ac294b7

First time build. Skipping changelog.

Loading library github.com/fabric8io/fabric8-pipeline-library@master

Creating git repository in /var/jenkins_home/caches/git-a328a55fee5293c8cf80d5616db2c459

> /usr/bin/git init /var/jenkins_home/caches/git-a328a55fee5293c8cf80d5616db2c459 # timeout=10

Setting origin to https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10

Fetching & pruning origin...

Fetching upstream changes from origin

> /usr/bin/git --version # timeout=10

> /usr/bin/git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* --prune

Getting remote branches...

Seen branch in repository origin/master

Seen branch in repository origin/new-k8s-plugin

Seen branch in repository origin/versionUpdate19ec510d-bd9c-4a06-ac3f-ef8c88713309

Seen branch in repository origin/versionUpdate48f84442-8af6-4eff-bca8-d5d38617c219

Seen branch in repository origin/versionUpdate6284b17a-caad-48ba-9ec2-3b6597e3417c

Seen branch in repository origin/versionUpdate6db75789-0c00-4ef9-9e47-724a1295104b

Seen branch in repository origin/versionUpdatef811e9aa-50f1-4294-b1e9-9c05eda33131

Seen 7 remote branches

Checking branch master

Cloning the remote Git repository

Cloning repository https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git init /var/jenkins_home/workspace/appms@libs # timeout=10

Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git --version # timeout=10

> /usr/bin/git fetch --tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*

> /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10

> /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10

> /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10

Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git fetch --tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*

Checking out Revision 506936619369f3635228b736646b95d8db70b3c9 (master)

> /usr/bin/git config core.sparsecheckout # timeout=10

> /usr/bin/git checkout -f 506936619369f3635228b736646b95d8db70b3c9

First time build. Skipping changelog.

[Pipeline] End of Pipeline

org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use new io.fabric8.openshift.client.DefaultOpenShiftClient

at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectNew(StaticWhitelist.java:185)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onNewInstance(SandboxInterceptor.java:130)

at org.kohsuke.groovy.sandbox.impl.Checker$3.call(Checker.java:191)

at org.kohsuke.groovy.sandbox.impl.Checker.checkedConstructor(Checker.java:188)

at org.kohsuke.groovy.sandbox.impl.Checker$checkedConstructor.callStatic(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)

at io.fabric8.Fabric8Commands.isOpenShift(Fabric8Commands.groovy:554)

at io.fabric8.Fabric8Commands$isOpenShift.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)

at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)

at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)

at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)

at mavenTemplate.call(/var/jenkins_home/jobs/appms/builds/1/libs/github.com/fabric8io/fabric8-pipeline-library/vars/mavenTemplate.groovy:14)

at mavenNode.call(/var/jenkins_home/jobs/appms/builds/1/libs/github.com/fabric8io/fabric8-pipeline-library/vars/mavenNode.groovy:8)

at WorkflowScript.run(WorkflowScript:31)

at ___cps.transform___(Native Method)

at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:48)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)

at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)

at com.cloudbees.groovy.cps.Next.step(Next.java:58)

at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)

at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:163)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:324)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:78)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:236)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:224)

at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:63)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)

at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

Finished: FAILURE
```

**Comment by jeremy-wilson** [comment]
Looks like an update was made 4 days ago, which is the time it would have broken.
