### ISSUE TITLE
Fabric8 new application build fails in Minikube: Unable to find valid certification path

### ISSUE THREAD

**Issue by ilterpehlivan** [fabric8io/fabric8#6843]
Started by user anonymous
2 	Replayed #3
3 	Loading library github.com/fabric8io/fabric8-pipeline-library@v2.2.311
4 	Creating git repository in /var/jenkins_home/caches/git-a328a55fee5293c8cf80d5616db2c459
5 	 > /usr/bin/git init /var/jenkins_home/caches/git-a328a55fee5293c8cf80d5616db2c459 # timeout=10
6 	Setting origin to https://github.com/fabric8io/fabric8-pipeline-library.git
7 	 > /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
8 	Fetching origin...
9 	Fetching upstream changes from origin
10 	 > /usr/bin/git --version # timeout=10
11 	 > /usr/bin/git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/*
12 	 > /usr/bin/git rev-parse v2.2.311^{commit} # timeout=10
13 	 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
14 	Fetching changes from the remote Git repository
15 	 > /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10
16 	Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git
17 	 > /usr/bin/git --version # timeout=10
18 	 > /usr/bin/git fetch --tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*
19 	Checking out Revision d8af29f8af7a498331a244d245fb321003ef110d (v2.2.311)
20 	 > /usr/bin/git config core.sparsecheckout # timeout=10
21 	 > /usr/bin/git checkout -f d8af29f8af7a498331a244d245fb321003ef110d
22 	 > /usr/bin/git rev-list d8af29f8af7a498331a244d245fb321003ef110d # timeout=10
23 	Replacing contents of vars/releaseProject.groovy
24 	Replacing contents of vars/updatePropertyVersion.groovy
25 	Replacing contents of vars/deployProject.groovy
26 	Replacing contents of vars/clientsNode.groovy
27 	Replacing contents of src/io/fabric8/Fabric8Commands.groovy
28 	Replacing contents of vars/tagImages.groovy
29 	Replacing contents of vars/waitUntilPullRequestMerged.groovy
30 	Replacing contents of vars/mavenIntegrationTest.groovy
31 	Replacing contents of vars/mavenNode.groovy
32 	Replacing contents of vars/performCanaryRelease.groovy
33 	Replacing contents of vars/promoteArtifacts.groovy
34 	Replacing contents of vars/goNode.groovy
35 	Replacing contents of vars/pushPomPropertyChangePROrganisation.groovy
36 	Replacing contents of vars/goTemplate.groovy
37 	Replacing contents of vars/stageProject.groovy
38 	Replacing contents of vars/bumpFabric8Versions.groovy
39 	Replacing contents of vars/deleteGitHubBranch.groovy
40 	Replacing contents of vars/stageExtraImages.groovy
41 	Replacing contents of vars/deployRemoteKubernetes.groovy
42 	Replacing contents of vars/genWebsiteDocs.groovy
43 	Replacing contents of vars/goRelease.groovy
44 	Replacing contents of vars/releaseNode.groovy
45 	Replacing contents of vars/mavenTemplate.groovy
46 	Replacing contents of vars/deployRemoteOpenShift.groovy
47 	Replacing contents of vars/runSystemTests.groovy
48 	Replacing contents of vars/getNewVersion.groovy
49 	Replacing contents of vars/waitUntilArtifactSyncedWithCentral.groovy
50 	Replacing contents of vars/dropProject.groovy
51 	Replacing contents of vars/gitTag.groovy
52 	Replacing contents of vars/mergeAndWaitForPullRequest.groovy
53 	Replacing contents of vars/pushParentPomVersionChangePR.groovy
54 	Replacing contents of vars/dropRelease.groovy
55 	Replacing contents of vars/mavenCanaryRelease.groovy
56 	Replacing contents of vars/releaseTemplate.groovy
57 	Replacing contents of vars/pushPomPropertyChangePR.groovy
58 	Replacing contents of vars/dockerNode.groovy
59 	Replacing contents of src/io/fabric8/Utils.groovy
60 	Replacing contents of vars/combineTemplates.groovy
61 	Replacing contents of vars/approve.groovy
62 	Replacing contents of vars/restGetURL.groovy
63 	Replacing contents of vars/getKubernetesJson.groovy
64 	Replacing contents of vars/clientsTemplate.groovy
65 	Replacing contents of vars/dockerTemplate.groovy
66 	Replacing contents of vars/mavenUpdateOrganisationDependencies.groovy
67 	Replacing contents of vars/promoteImages.groovy
68 	[Pipeline] End of Pipeline
69 	io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
70 		at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
71 		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:190)
72 		at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:150)
73 		at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:51)
74 		at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:35)
75 		at io.fabric8.kubernetes.client.BaseClient.isAdaptable(BaseClient.java:132)
76 		at io.fabric8.kubernetes.client.Client$isAdaptable.call(Unknown Source)
77 		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
78 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
79 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
80 		at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
81 		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
82 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
83 		at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
84 		at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$0.callStatic(Unknown Source)
85 		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
86 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
87 		at io.fabric8.Fabric8Commands.isOpenShift(Fabric8Commands.groovy:554)
88 		at io.fabric8.Fabric8Commands$isOpenShift.call(Unknown Source)
89 		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
90 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
91 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
92 		at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
93 		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
94 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
95 		at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
96 		at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)
97 		at clientsTemplate.call(/var/jenkins_home/jobs/demonodeapp/builds/4/libs/github.com/fabric8io/fabric8-pipeline-library/vars/clientsTemplate.groovy:12)
98 		at clientsNode.call(/var/jenkins_home/jobs/demonodeapp/builds/4/libs/github.com/fabric8io/fabric8-pipeline-library/vars/clientsNode.groovy:7)
99 		at WorkflowScript.run(WorkflowScript:4)
100 		at ___cps.transform___(Native Method)
101 		at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
102 		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
103 		at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)
104 		at sun.reflect.GeneratedMethodAccessor204.invoke(Unknown Source)
105 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
106 		at java.lang.reflect.Method.invoke(Method.java:498)
107 		at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
108 		at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
109 		at com.cloudbees.groovy.cps.Next.step(Next.java:58)
110 		at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
111 		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
112 		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
113 		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
114 		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
115 		at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
116 		at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:163)
117 		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:328)
118 		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:80)
119 		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:240)
120 		at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:228)
121 		at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:63)
122 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
123 		at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
124 		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
125 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
126 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
127 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
128 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
129 		at java.lang.Thread.run(Thread.java:745)
130 	Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
131 		at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
132 		at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
133 		at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
134 		at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
135 		at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
136 		at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
137 		at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
138 		at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
139 		at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
140 		at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
141 		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
142 		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
143 		at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
144 		at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
145 		at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
146 		at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
147 		at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
148 		at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
149 		at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
150 		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
151 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
152 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
153 		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
154 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
155 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
156 		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
157 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
158 		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
159 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
160 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
161 		at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:65)
162 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
163 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
164 		at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
165 		at okhttp3.RealCall.execute(RealCall.java:60)
166 		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:235)
167 		at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
168 		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:183)
169 		at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:150)
170 		at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:51)
171 		at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:35)
172 		at io.fabric8.kubernetes.client.BaseClient.isAdaptable(BaseClient.java:132)
173 		at io.fabric8.kubernetes.client.Client$isAdaptable.call(Unknown Source)
174 		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
175 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
176 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
177 		at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
178 		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
179 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
180 		at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
181 		at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$0.callStatic(Unknown Source)
182 		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
183 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
184 		at io.fabric8.Fabric8Commands.isOpenShift(Fabric8Commands.groovy:554)
185 		at io.fabric8.Fabric8Commands$isOpenShift.call(Unknown Source)
186 		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
187 		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
188 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
189 		at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
190 		at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
191 		at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
192 		at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
193 		at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)
194 		... 29 more
195 	Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
196 		at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
197 		at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
198 		at sun.security.validator.Validator.validate(Validator.java:260)
199 		at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
200 		at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
201 		at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
202 		at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
203 		... 87 more
204 	Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
205 		at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
206 		at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
207 		at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
208 		at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
209 		... 93 more
210 	Finished: FAILURE

**Comment by ilterpehlivan** [comment]
same as #6829 ..Closing this one
