### ISSUE TITLE
Not able to build project locally in fabric8

### ISSUE THREAD

**Issue by hermanshafiq** [fabric8io/fabric8#6846]
getting exception tried alot to figure it out but failed every time.. any one here for help please

```
Started by user anonymous

Cloning the remote Git repository

Cloning repository http://gogs/gogsadmin/hello-micro.git

> /usr/bin/git init /var/jenkins_home/workspace/hello-micro@script # timeout=10

Fetching upstream changes from http://gogs/gogsadmin/hello-micro.git

> /usr/bin/git --version # timeout=10

> /usr/bin/git fetch --tags --progress http://gogs/gogsadmin/hello-micro.git +refs/heads/*:refs/remotes/origin/*

> /usr/bin/git config remote.origin.url http://gogs/gogsadmin/hello-micro.git # timeout=10

> /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10

> /usr/bin/git config remote.origin.url http://gogs/gogsadmin/hello-micro.git # timeout=10

Fetching upstream changes from http://gogs/gogsadmin/hello-micro.git

> /usr/bin/git fetch --tags --progress http://gogs/gogsadmin/hello-micro.git +refs/heads/*:refs/remotes/origin/*

> /usr/bin/git rev-parse refs/remotes/origin/master^{commit} # timeout=10

> /usr/bin/git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10

Checking out Revision 54d62a65d0fc046b94322c4328f9ba81c9ce11cc (refs/remotes/origin/master)

> /usr/bin/git config core.sparsecheckout # timeout=10

> /usr/bin/git checkout -f 54d62a65d0fc046b94322c4328f9ba81c9ce11cc

First time build. Skipping changelog.

Loading library github.com/fabric8io/fabric8-pipeline-library@v2.2.311

> /usr/bin/git rev-parse --is-inside-work-tree # timeout=10

Setting origin to https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10

Fetching origin...

Fetching upstream changes from origin

> /usr/bin/git --version # timeout=10

> /usr/bin/git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/*

> /usr/bin/git rev-parse v2.2.311^{commit} # timeout=10

Cloning the remote Git repository

Cloning repository https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git init /var/jenkins_home/workspace/hello-micro@libs/github.com/fabric8io/fabric8-pipeline-library # timeout=10

Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git --version # timeout=10

> /usr/bin/git fetch --tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*

> /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10

> /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10

> /usr/bin/git config remote.origin.url https://github.com/fabric8io/fabric8-pipeline-library.git # timeout=10

Fetching upstream changes from https://github.com/fabric8io/fabric8-pipeline-library.git

> /usr/bin/git fetch --tags --progress https://github.com/fabric8io/fabric8-pipeline-library.git +refs/heads/*:refs/remotes/origin/*

Checking out Revision d8af29f8af7a498331a244d245fb321003ef110d (v2.2.311)

> /usr/bin/git config core.sparsecheckout # timeout=10

> /usr/bin/git checkout -f d8af29f8af7a498331a244d245fb321003ef110d

First time build. Skipping changelog.

[Pipeline] End of Pipeline

io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.

at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)

at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:190)

at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:150)

at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:51)

at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:35)

at io.fabric8.kubernetes.client.BaseClient.isAdaptable(BaseClient.java:132)

at io.fabric8.kubernetes.client.Client$isAdaptable.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)

at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)

at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)

at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$0.callStatic(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)

at io.fabric8.Fabric8Commands.isOpenShift(Fabric8Commands.groovy:554)

at io.fabric8.Fabric8Commands$isOpenShift.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)

at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)

at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)

at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)

at mavenTemplate.call(/var/jenkins_home/jobs/hello-micro/builds/1/libs/github.com/fabric8io/fabric8-pipeline-library/vars/mavenTemplate.groovy:14)

at mavenNode.call(/var/jenkins_home/jobs/hello-micro/builds/1/libs/github.com/fabric8io/fabric8-pipeline-library/vars/mavenNode.groovy:8)

at WorkflowScript.run(WorkflowScript:31)

at ___cps.transform___(Native Method)

at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)

at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)

at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)

at com.cloudbees.groovy.cps.Next.step(Next.java:58)

at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)

at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)

at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:163)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:328)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:80)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:240)

at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:228)

at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:63)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)

at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)

at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)

at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)

at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)

at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)

at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)

at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)

at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)

at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)

at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)

at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)

at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)

at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)

at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)

at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)

at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)

at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)

at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)

at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:65)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)

at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)

at okhttp3.RealCall.execute(RealCall.java:60)

at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:235)

at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)

at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:183)

at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:150)

at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:51)

at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:35)

at io.fabric8.kubernetes.client.BaseClient.isAdaptable(BaseClient.java:132)

at io.fabric8.kubernetes.client.Client$isAdaptable.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)

at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)

at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)

at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$0.callStatic(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)

at io.fabric8.Fabric8Commands.isOpenShift(Fabric8Commands.groovy:554)

at io.fabric8.Fabric8Commands$isOpenShift.call(Unknown Source)

at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)

at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)

at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)

at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)

at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)

at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)

at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)

... 29 more

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)

at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)

at sun.security.validator.Validator.validate(Validator.java:260)

at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)

at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)

at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)

at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)

... 87 more

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)

at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)

... 93 more

Finished: FAILURE
```

**Comment by javawolfpack** [comment]
This appears to be the same as this issue: 
https://github.com/fabric8io/fabric8/issues/6845
