### ISSUE TITLE
java.lang.IllegalStateException: Failed to apply kubernetes configuration.

### ISSUE THREAD

**Issue by chbe8475** [fabric8io/fabric8#6853]
I have an installation of fabric8 which is rather old. Version 2.2.163. I am running on kubernetes 1.4.7
It has been running smoothly for a while and I have 4 developers building and running micro services on this installation.
Since a couple of days our jenkins pipelines are failing. We are using default pipelines from fabric8 without any modification.
The canary release stage is successfull, but the integration testing fails with this error:

`[31mTimed out waiting for pods/services![m
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 318.947 sec <<< FAILURE! - in
se.prv.mypages.contractserver.KubernetesIntegrationKT
se.prv.mypages.contractserver.KubernetesIntegrationKT  Time elapsed: 318.942 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to apply kubernetes configuration.`

Usually this means that the pod did not start successfully and is probably restarting all the time. But in this case the pod is started. I can communicate with it using the REST API which it implements.

Since we are using the other stages (staging and production) I really would like to pass this test and have the CD continue.

This seems to be a re-occuring problem since it pops up in the issue list every now and then:
https://github.com/fabric8io/fabric8/issues/6473
https://github.com/fabric8io/fabric8/issues/6131

None of the solutions works for me this time.

Any ideas on where I should look? Any recent changes which might have affected my installation?
Help is much appreciated.

Thanks,
Christer

**Comment by jstrachan** [comment]
we hit something similar lately - we found the kubernetes client was not properly exposing the actual error message from kubernetes. I wonder could you try a more recent kubernetes client / fabric8 release? we may need to cut a new fabric8 release if that doesnt help...

**Comment by jstrachan** [comment]
could you try with fabric8 version `2.2.210` please? thats got a recent kubernetes client inside which hopefully won't gobble the real reason that kubernetes rejected the apply

**Comment by chbe8475** [comment]
Which is the easiest/preferred way to install a more recent fabric8 ontop of the existing one?

**Comment by jstrachan** [comment]
for now if you just update your pom.xml to use the new version it should then use the new version when its running the integration test - when the problem's happening. Maybe upgrading the fabric8-maven-plugin may help too (in case that brings in an older kubernetes-client)

**Comment by chbe8475** [comment]
I updated both fabric8 version and the fabric8-maven-plugin to the latest version (2.2.210 and 3.3.5)

I got the same error. 

And I also geo this warning a bit earlier:

`2017-05-10;13:05:14.192 [main] WARN  i.f.k.api.environments.Environments - Failed to parse environment YAML for staging. Reason: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "key" (class io.fabric8.kubernetes.api.environments.Environment), not marked as ignorable (4 known properties: "name", "order", "namespace", "clusterAPiServer"])
 at [Source: [B@673be18f; line: 4, column: 13] (through reference chain: io.fabric8.kubernetes.api.environments.Environment["key"]). YAML: name: GUI-Dev environment
namespace: default-staging
order: 2
key: staging
label: Staging

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "key" (class io.fabric8.kubernetes.api.environments.Environment), not marked as ignorable (4 known properties: "name", "order", "namespace", "clusterAPiServer"])
 at [Source: [B@673be18f; line: 4, column: 13] (through reference chain: io.fabric8.kubernetes.api.environments.Environment["key"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)`

My guess I we can ignore this warning for now.

**Comment by chbe8475** [comment]
A related question.
While I am doing my tests with different experiments I always have to wait the 300 seconds until the integration test fails.
I tried to change this in the KubernetesIntegrationKT class like this:

`assertThat(client).deployments().pods().isPodReadyForPeriod(6000L, 6000L);`

But that has no effect at all. Any ideas on how to change this timeout?

**Comment by chbe8475** [comment]
I have now migrated the fabric8 environment to a later version. Still no luck. Problem still exists.
I am still doing some testing with different configurations. I'll get back here if I find a solution.

**Comment by jstrachan** [comment]
I've got a fix in the PR above for the parsing issue of environments.

On the timeout issue; I'm wondering if the 300s delay is actually the underlying arquillian framework pausing rather than that assertion. Looking at the code those timeouts definitely get passed in and look OK to me. Wonder if its worth trying to debug your test and seeing where the pause happens (e.g. does your assertion even get invoked)?

Still not sure on what the underlying reason for gobbling up the kubernetes apply exception message though. Maybe a debug could help figure that out too - the clue may be in the exception and it may just be the fabric8-arquillian code thats not logging it correctly?

**Comment by chbe8475** [comment]
Could it be that the namespaces in the pipeline has changed names since my very old installation?

After my migration the integration tests suddenly worked (after some manually changes, approval of scripts and stuff). But when I did kubectl get pods in the namespace default-testing I did not see my pod. Using kubectl get namespaces I found out that there was a new namespace created named default-test. And in that namespace I found my pod.

So my theory is that while jenkins deployed my pod in default-testing, the integration test was looking in default-test.

I have run the tests using a new, empty application. I will now try to get one of the existing application developed by my team to work as well. I guess I need to have it to switch from default-testing to default-test somehow.

**Comment by chbe8475** [comment]
I edited the fabric8.yml file and changed name of the namespaces. Now it is working again. The Jenkins gui is not showing me the different steps in the pipeline though, but everything is working ok.

@jstrachan is there a guide somewhere that could help me in debugging my tests as you proposed?
