### ISSUE TITLE
Fabric8 Gogs not starting with persistent volume claims

### ISSUE THREAD

**Issue by soloman747** [fabric8io/fabric8#6914]
Gogs is not starting with persistent volume claims on Openshift Origin v1.5.1. 
Fabric8 build version:
gofabric8, version 0.4.138 (branch: 'master', revision: '8c0b80c3')
  build date:       '20170801-15:44:47'
  go version:       '1.8.1'

Receiving the following in the logs:

  | mkdir: cannot create directory '/app/gogs/data/git': Permission denied
-- | --
  | mkdir: cannot create directory '/app/gogs/data/ssh/': Permission denied
  | /opt/gogs/start.sh: line 24: cd: /app/gogs/data/ssh/: No such file or directory
  | panic: open gogs.rsa: permission denied
  | goroutine 1 [running]:
  | panic(0x519120, 0xc4200c9f20)
  | /usr/local/go/src/runtime/panic.go:500 +0x1a1
  | main.main()
  | /home/jdyson/go/src/github.com/fabric8io/docker-gogs/cmds/ssh-hostkeygen/ssh-hostkeygen.go:41 +0x2c1
  | 2017/08/01 19:17:52 Creating admin user:  true
  | 2017/08/01 19:17:52 [T] Custom path: /opt/gogs/custom
  | 2017/08/01 19:17:52 [T] Log path: /app/gogs/data/logs
  | 2017/08/01 19:17:52 [I] Gogs: Go Git Service
  | 2017/08/01 19:17:52 [.../gogs/models/repo.go:121 NewRepoContext()] [E] Fail to set git user.email(exit status 255): error: could not lock config file /app/gogs/data/.gitconfig: Permission denied

**Comment by pravinarr** [comment]
Did anyone found a solution to this problem. I am facing this same issue when I start the gogs.
