### ISSUE TITLE
Cannot install gogs and web show "There are no teams currently available." with kubernetes

### ISSUE THREAD

**Issue by tlytg456** [fabric8io/fabric8#6968]
Thanks all first,

Sorry I post the issue to the fabric8 console page, So I post the question here again

I install kubernetes in 3 VMs and I want to install the fabric8 via gofabric8.
But now the gogs cannot start correctly.
root@opt1:~# kubectl get pods
```
NAME                                       READY     STATUS             RESTARTS   AGE
configmapcontroller-5494c4f9c4-fssfz       1/1       Running            1          19h
exposecontroller-6f8fc9f67-pljzc           1/1       Running            18         18h
fabric8-7b6f4bf584-znwrw                   2/2       Running            2          19h
fabric8-docker-registry-6996457b46-4vn4c   1/1       Running            1          19h
fabric8-forge-86868586bd-8b2pf             1/1       Running            1          19h
gogs-649cb66d55-796w4                      0/1       Terminating        5          17h
gogs-649cb66d55-cnvwv                      0/1       CrashLoopBackOff   168        14h
gogs-649cb66d55-v5qm7                      0/1       Terminating        39         17h
ingress-nginx-687bc4bf65-dgqbv             1/1       Running            1          19h
jenkins-945b6ccd-7prhp                     1/1       Running            1          19h
nexus-78575b469b-l5696                     1/1       Running            1          19h
```
And I search log get:
```
root@opt1:~# kubectl logs gogs-649cb66d55-cnvwv 
mkdir: cannot create directory '/app/gogs/data/git': Permission denied
mkdir: cannot create directory '/app/gogs/data/ssh/': Permission denied
/opt/gogs/start.sh: line 24: cd: /app/gogs/data/ssh/: No such file or directory
panic: open gogs.rsa: permission denied

goroutine 1 [running]:
panic(0x519120, 0xc4200ef710)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/jdyson/go/src/github.com/fabric8io/docker-gogs/cmds/ssh-hostkeygen/ssh-hostkeygen.go:41 +0x2c1
2017/10/26 00:54:03 Creating admin user:  true
2017/10/26 00:54:03 [T] Custom path: /opt/gogs/custom
2017/10/26 00:54:03 [T] Log path: /app/gogs/data/logs
2017/10/26 00:54:03 [I] Gogs: Go Git Service 
2017/10/26 00:54:03 [.../gogs/models/repo.go:121 NewRepoContext()] [E] Fail to set git user.name(exit status 255): error: could not lock config file /app/gogs/data/.gitconfig: Permission denied

```
I can not run the 'gofabric8 service fabric8 --url', and it would not show the url and stock, 
so I find the fabic8 service is run, and use nodePort to pose the url to see the web, I get "There are no teams currently available."

I do not know where should I fix, and I searched that problem be happened on minikube.#189

I am look for ward to your reply. Thanks.

**Comment by pravinarr** [comment]
did anyone found a solution for this problem. I am facing this same issue.

thank you in advance

**Comment by tlytg456** [comment]
@pravinarr Hi, Can you browse the fabric8 page?

**Comment by pravinarr** [comment]
yes. I can. All other services are starting fine except this one. I am installing fabric8 using helm and by default it installs v0.9.97. If I upgrade the the latest version, same result with a different error saying Environment variable domain is missing!!.

I am new to kubernetes and fabric8. I may be doing something wrong here. Any helps much appreciated.

thanks in advance

**Comment by tlytg456** [comment]
I use gofabric8 to install it, if you use it with your pc or laptop, you can use gofabric8 to help you install a minikube and everything goes good.

if you install it in a real k8s, you need refer the domain in advance, gofabric8 can add domain when it install the all plugin.

**Comment by shuang-x-zhao-gj** [comment]
I recently was investigating fabric8, i have passed this problem, there are two ways, one is as you guys said, you can upgrade to a new version, i just tried a newer one than then 0.9.XXX, it asked DOMAIN for you, i think it should be the domain used for gogs ssh repo url, i modify the deployment to pass it, then the gogs pod can start; another way is changing your underlying storage system, i tried rbd, cephfs, rbd is not suitable for jenkins needs, and cephfs will have input/output error... maybe i didn't configure them right, so i decided to just use a simple storage class solution, i chose NFS, then gogs can start and generate files under the provisioned dir.

Hope you guys good luck with that

-Roger
