### ISSUE TITLE
Failed to command remote repo https://github.com/fabric8io/fabric8-jenkinsfile-library.git due: https://github.com/fabric8io/fabric8-jenkinsfile-library.git: cannot open git-upload-pack

### ISSUE THREAD

**Issue by sbenchekroun** [fabric8io/fabric8#6992]
hi ,
I'm working on openshift 1.5 I have just dowload the latest release of gofabric8 : 0.4.176.
 My VM need a proxy in order to resolve github.com , so I added I command in the forge pod that include the http proxy configuration, and I also added the starting command "/deployments/run-java.sh" , my command is looks like this : 

```
command:
            - /bin/bash
            - '-c'
          args:
            - >-
              git config --global http.proxy http://proxy.infra.dgfip:8080;  git
              config --global https.proxy http://proxy.infra.dgfip:8080; git
              config --global http.sslVerify false;  /deployments/run-java.sh
```
The git clone of other git repo goes well, but I have errors in the fabric8-jenkinsfile-library.git:

```

worker-1) Executing: git clone https://github.com/snowdrop/spring-boot-circuit-breaker-booster --branch v11 --recursive --depth=1 /tmp/booster-catalog47465965404042441/.boosters/spring-boot-circuit-breaker-community
--
  | Cloning into '/tmp/booster-catalog47465965404042441/.boosters/spring-boot-circuit-breaker-community'...
  | 2017-11-20 14:07:58,456 ERROR [io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary] (io.fabric8.forge:fabric8-generator,1.0.67) Failed to command remote repo https://github.com/fabric8io/fabric8-jenkinsfile-library.git due: https://github.com/fabric8io/fabric8-jenkinsfile-library.git: cannot open git-upload-pack: org.eclipse.jgit.api.errors.TransportException: https://github.com/fabric8io/fabric8-jenkinsfile-library.git: cannot open git-upload-pack
  | at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:245)
  | at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:293)
  | at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:190)
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.cloneRepo(JenkinsPipelineLibrary.java:95)
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.cloneOrPullRepo(JenkinsPipelineLibrary.java:135)
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.cloneOrPull(JenkinsPipelineLibrary.java:113)
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.<init>(JenkinsPipelineLibrary.java:65)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:119)
  | at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:92)
  | at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:78)
  | at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
  | at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:112)
  | at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:180)
  | at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)
  | at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
  | at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
  | at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
  | at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
  | at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:758)
  | at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:858)
  | at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.getParameterValues(StaticMethodInjectionPoint.java:127)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
  | at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:109)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
  | at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
  | at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
  | at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:136)
  | at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:689)
  | at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:101)
  | at org.jboss.forge.furnace.container.cdi.events.CrossContainerObserverMethod.handleEvent(CrossContainerObserverMethod.java:82)
  | at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
  | at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:109)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
  | at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
  | at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
  | at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:136)
  | at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:689)
  | at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:101)
  | at org.jboss.forge.furnace.container.cdi.events.EventManagerImpl.lambda$fireEvent$0(EventManagerImpl.java:42)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:70)
  | at org.jboss.forge.furnace.container.cdi.events.EventManagerImpl.fireEvent(EventManagerImpl.java:41)
  | at org.jboss.forge.furnace.container.cdi.lifecycle.WeldAddonLifecycleProvider.postStartup(WeldAddonLifecycleProvider.java:118)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable.firePostStartup(AddonRunnable.java:142)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable.access$400(AddonRunnable.java:38)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:96)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:86)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable.run(AddonRunnable.java:85)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/fabric8io/fabric8-jenkinsfile-library.git: cannot open git-upload-pack
  | at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:566)
  | at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:326)
  | at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
  | at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
  | at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1236)
  | at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:234)
  | ... 67 more
  | Caused by: java.net.UnknownHostException: github.com
  | at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
  | at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  | at java.net.Socket.connect(Socket.java:589)
  | at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
  | at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
  | at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
  | at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
  | at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
  | at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
  | at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
  | at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
  | at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
  | at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
  | at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
  | at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
  | at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
  | at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
  | at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:99)
  | at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:202)
  | at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:504)
  | ... 72 more
  | 2017-11-20 14:07:58,463 ERROR [io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary] (io.fabric8.forge:fabric8-generator,1.0.67) Failed to clone jenkins workflow repo from : https://github.com/fabric8io/fabric8-jenkinsfile-library.git. java.lang.RuntimeException: Failed to command remote repo https://github.com/fabric8io/fabric8-jenkinsfile-library.git due: https://github.com/fabric8io/fabric8-jenkinsfile-library.git: cannot open git-upload-pack: java.lang.RuntimeException: Failed to command remote repo https://github.com/fabric8io/fabric8-jenkinsfile-library.git due: https://github.com/fabric8io/fabric8-jenkinsfile-library.git: cannot open git-upload-pack
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.cloneRepo(JenkinsPipelineLibrary.java:101)
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.cloneOrPullRepo(JenkinsPipelineLibrary.java:135)
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.cloneOrPull(JenkinsPipelineLibrary.java:113)
  | at io.fabric8.forge.generator.pipeline.JenkinsPipelineLibrary.<init>(JenkinsPipelineLibrary.java:65)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:119)
  | at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:92)
  | at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:78)
  | at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
  | at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:112)
  | at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:180)
  | at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)
  | at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
  | at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
  | at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
  | at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
  | at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:758)
  | at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:858)
  | at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.getParameterValues(StaticMethodInjectionPoint.java:127)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
  | at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:109)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
  | at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
  | at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
  | at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:136)
  | at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:689)
  | at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:101)
  | at org.jboss.forge.furnace.container.cdi.events.CrossContainerObserverMethod.handleEvent(CrossContainerObserverMethod.java:82)
  | at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
  | at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:109)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
  | at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
  | at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
  | at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
  | at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
  | at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:136)
  | at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:689)
  | at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:101)
  | at org.jboss.forge.furnace.container.cdi.events.EventManagerImpl.lambda$fireEvent$0(EventManagerImpl.java:42)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:70)
  | at org.jboss.forge.furnace.container.cdi.events.EventManagerImpl.fireEvent(EventManagerImpl.java:41)
  | at org.jboss.forge.furnace.container.cdi.lifecycle.WeldAddonLifecycleProvider.postStartup(WeldAddonLifecycleProvider.java:118)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable.firePostStartup(AddonRunnable.java:142)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable.access$400(AddonRunnable.java:38)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:96)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable$2.call(AddonRunnable.java:86)
  | at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
  | at org.jboss.forge.furnace.impl.addons.AddonRunnable.run(AddonRunnable.java:85)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | 2017-11-20 14:07:58,475 INFO  [io.fabric8.forge.generator.Fabric8GeneratorInitializer] (io.fabric8.forge:fabric8-generator,1.0.67) Using Jenkinsfile library at: target/jenkinsfileLibrary
  | Note: checking out '59e354bb6458e2907e0dfaccf184e281be6d3021'.
  | You are in 'detached HEAD' state. You can look around, make experimental
  | changes and commit them, and you can discard any commits you make in this
  | state without impacting any branches by performing another checkout.
  | If you want to create a new branch to retain commits you create, you may
  | do so (now or later) by using -b with the checkout command again. Example:
  | git checkout -b new_branch_name

```

Any help please?

**Comment by sbenchekroun** [comment]
Please can any one Help ? Any news ??

**Comment by rawlingsj** [comment]
There's also another error in the stacktrace `java.net.UnknownHostException: github.com`

So it looks like there's a dns issue on your cluster maybe?

**Comment by sbenchekroun** [comment]
Yes indeed, my cluster uses a a DNS that cannot resolve : "github.com", but it also uses a Company Proxy in order to clone the github repository  . 

You thing that, in this case, fabric8 is trying to resolve the DNS name of github instade of cloning the repository : fabric8-jenkinsfile-library.git   (NB: the clone works on the other repository by fabric8) ?

**Comment by sbenchekroun** [comment]
I found a solution for this problem: I add the proxy configuration in JAVA_OPTIONS as an environment variable inside the pods, now I'm facing another problem in the forge:

```
2017-11-23 12:57:27,095 SEVERE [io.openshift.booster.catalog.BoosterCatalogService] (Thread-41) Error while indexing: Cannot create property=supportedDeploymentTypes for JavaBean=Booster [id=null, githubRepo=bucharest-gold/nodejs-rest-http-secured, gitRef=v1.0.0, buildProfile=null, description=No description available, boosterDescriptorPath=.openshiftio/booster.yaml, mission=null, runtime=null, version=null, contentPath=null, metadata={}]
--
  | in 'reader', line 1, column 1:
  | githubRepo: bucharest-gold/nodej ...
  | ^
  | Unable to find property 'supportedDeploymentTypes' on class: io.openshift.booster.catalog.Booster
  | in 'reader', line 3, column 27:
  | supportedDeploymentTypes: zip
  | ^
  | at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
  | at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
  | at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:346)
  | at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
  | at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:143)
  | at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:129)
  | at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
  | at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:465)
  | at io.openshift.booster.catalog.BoosterCatalogService.indexBooster(BoosterCatalogService.java:221)
  | at io.openshift.booster.catalog.BoosterCatalogService.access$000(BoosterCatalogService.java:57)
  | at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:152)
  | at io.openshift.booster.catalog.BoosterCatalogService$1.visitFile(BoosterCatalogService.java:137)
  | at java.nio.file.Files.walkFileTree(Files.java:2670)
  | at java.nio.file.Files.walkFileTree(Files.java:2742)
  | at io.openshift.booster.catalog.BoosterCatalogService.indexBoosters(BoosterCatalogService.java:136)
  | at io.openshift.booster.catalog.BoosterCatalogService.doIndex(BoosterCatalogService.java:115)
  | at io.openshift.booster.catalog.BoosterCatalogService.lambda$index$0(BoosterCatalogService.java:98)
  | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'supportedDeploymentTypes' on class: io.openshift.booster.catalog.Booster
  | at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
  | at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
  | at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:323)
  | at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:241)
  | ... 18 more

```

any idea, where this could came from ?
