### ISSUE TITLE
Cannot run CI pipeline 

### ISSUE THREAD

**Issue by pravinarr** [fabric8io/fabric8#7019]
I have installed fabric8 platform in kubernetes + AWS using helm.

After installing it, when I tried to create new application, it successfully created repository in the gogs but it throws exception in jenkins job creation step 

when i see the error log in jenkins-forge pod it says 
```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: http://jenkinshift/oapi/v1/namespaces/default/buildconfigs. Message: error: HTTP POST returned status code returned: 500.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:268)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:208)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:644)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:300)
	at io.fabric8.kubernetes.api.Controller.doCreateBuildConfig(Controller.java:796)
	... 55 more
```

and when I checked the error log in jenkins pod, it says file not found exception

```
Caused by: javax.xml.transform.TransformerException: java.io.FileNotFoundException: /var/jenkins_home/jobs/hello/config.xml (No such file or directory)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(TransformerImpl.java:521)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:336)
	at jenkins.util.xml.XMLUtils._transform(XMLUtils.java:214)
	at jenkins.util.xml.XMLUtils.safeTransform(XMLUtils.java:81)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:274)
	... 59 more
Caused by: java.io.FileNotFoundException: /var/jenkins_home/jobs/hello/config.xml (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:213)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:101)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(TransformerImpl.java:494)
	... 63 more
```

when i tried to look at the permissions of the folder "/var/jenkins_home/jobs",
`
drwxr-xr-x   3 root    root     4096 Feb  2 21:56 jobs`

Can anyone help me what is the problem here. I am new to fabric8 and Kubernetes , I may be doing something wrong here. Any help appreciated.

thanks in Advance

**Comment by hip911** [comment]
I'm on the same path like you, trying out fabric8, so there might be a nicer solution.

By giving rights on the node to the jenkins-jobs PV the issue went away.

**Comment by livelyRyan** [comment]
This problem is caused by fabric8's own.
Try to run this command `chmod 777 /var/jenkins_home/jobs` to solve it.
