### ISSUE TITLE
Tests breaking on Kubernetes-client 3.1.12

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8#7053]
Some of the tests are breaking on updating kubernetes-client dependency to 3.1.12. 

logs of breaking tests:
```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.fabric8.kubernetes.api.pipelines.JobEnvironmentTest
Running io.fabric8.kubernetes.api.pipelines.OpenShiftPipelineTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.22 sec <<< FAILURE! - in io.fabric8.kubernetes.api.pipelines.OpenShiftPipelineTest
testPipelinesFromConfigMap(io.fabric8.kubernetes.api.pipelines.OpenShiftPipelineTest)  Time elapsed: 0.033 sec  <<< ERROR!
java.lang.NoClassDefFoundError: io/fabric8/mockwebserver/dsl/TimesOnceableOrHttpHeaderable
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.onStart(KubernetesMockServer.java:69)
	at io.fabric8.mockwebserver.DefaultMockServer.startInternal(DefaultMockServer.java:84)
	at io.fabric8.mockwebserver.DefaultMockServer.start(DefaultMockServer.java:96)
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.init(KubernetesMockServer.java:61)
	at io.fabric8.openshift.client.server.mock.OpenShiftServer.before(OpenShiftServer.java:31)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.ClassNotFoundException: io.fabric8.mockwebserver.dsl.TimesOnceableOrHttpHeaderable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.onStart(KubernetesMockServer.java:69)
	at io.fabric8.mockwebserver.DefaultMockServer.startInternal(DefaultMockServer.java:84)
	at io.fabric8.mockwebserver.DefaultMockServer.start(DefaultMockServer.java:96)
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.init(KubernetesMockServer.java:61)
	at io.fabric8.openshift.client.server.mock.OpenShiftServer.before(OpenShiftServer.java:31)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testPipelinesWithNoConfigMap(io.fabric8.kubernetes.api.pipelines.OpenShiftPipelineTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NoClassDefFoundError: io/fabric8/mockwebserver/dsl/TimesOnceableOrHttpHeaderable
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.onStart(KubernetesMockServer.java:69)
	at io.fabric8.mockwebserver.DefaultMockServer.startInternal(DefaultMockServer.java:84)
	at io.fabric8.mockwebserver.DefaultMockServer.start(DefaultMockServer.java:96)
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.init(KubernetesMockServer.java:61)
	at io.fabric8.openshift.client.server.mock.OpenShiftServer.before(OpenShiftServer.java:31)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testPipelinesFromConfigMapWithCaching(io.fabric8.kubernetes.api.pipelines.OpenShiftPipelineTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NoClassDefFoundError: io/fabric8/mockwebserver/dsl/TimesOnceableOrHttpHeaderable
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.onStart(KubernetesMockServer.java:69)
	at io.fabric8.mockwebserver.DefaultMockServer.startInternal(DefaultMockServer.java:84)
	at io.fabric8.mockwebserver.DefaultMockServer.start(DefaultMockServer.java:96)
	at io.fabric8.kubernetes.server.mock.KubernetesMockServer.init(KubernetesMockServer.java:61)
	at io.fabric8.openshift.client.server.mock.OpenShiftServer.before(OpenShiftServer.java:31)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by piyush1594** [comment]
As #7054 is merged, we are good to close this.
